"""Docs: https://vedicreader.github.io/fossickcdp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cdp.ipynb.

# %% auto #0
__all__ = ['PostCapture', 'CDPSession', 'setup_chrome_daemon', 'automation_browser']

# %% ../nbs/01_cdp.ipynb #93f16b3aa77ce8ef
import asyncio, json, base64, time, subprocess, sys, shutil, os, threading, httpx, socket, tempfile
from fastcore.all import patch, store_attr, AttrDict, Path
from fastcdp.core import CDP
from .core import save_path as _cache, compile_pattern, paginate_api, to_md, get_options, fetch, fetch_all

# %% ../nbs/01_cdp.ipynb #c2fbe20ba5bde574
@patch
async def _record_loop(self:CDP, fps, quality, sid):
    "Receive screencast frames and pipe to ffmpeg, duplicating frames to maintain real-time playback"
    i = 1.0 / fps
    async with self.on('Page.screencastFrame') as q:
        await self.page.startScreencast(sid=sid, format='jpeg', quality=quality, everyNthFrame=1)
        lt,ld = time.monotonic(), None
        try:
            while self._ffmpeg.poll() is None:
                try:
                    frame = await asyncio.wait_for(q.get(), timeout=i)
                    p = frame['params']
                    data = base64.b64decode(p['data'])
                    now = time.monotonic()
                    if ld:
                        n_dup = max(1, round((now - lt) / i))
                        for _ in range(n_dup): self._ffmpeg.stdin.write(ld)
                    ld, lt = data, now
                    await self.page.screencastFrameAck(sid=sid, sessionId=p['sessionId'])
                except asyncio.TimeoutError:
                    if ld:
                        self._ffmpeg.stdin.write(ld)
                        lt = time.monotonic()
        except asyncio.CancelledError:
            if ld: self._ffmpeg.stdin.write(ld)
        except BrokenPipeError: pass

# %% ../nbs/01_cdp.ipynb #bab7b5f5753b9eb1
@patch
async def start_recording(self:CDP, path=None, fps=25, quality=80, sid=None):
    "Start recording the active page to an mp4 file via ffmpeg"
    path = path or _cache('recording.mp4')
    self._ffmpeg = subprocess.Popen(
        ['ffmpeg', '-y', '-f', 'image2pipe', '-framerate', str(fps), '-i', '-',
         '-c:v', 'libsvtav1', '-crf', '35', '-preset', '8', '-movflags', '+faststart', path],
        stdin=subprocess.PIPE, stderr=subprocess.PIPE)
    self._rec_task = asyncio.create_task(self._record_loop(fps, quality, sid))

# %% ../nbs/01_cdp.ipynb #9496c94403bff11f
@patch
async def stop_recording(self:CDP, sid=None):
    "Stop recording and finalize the mp4 file"
    try: await self.page.stopScreencast(sid=sid)
    except RuntimeError: pass
    self._rec_task.cancel()
    try: await self._rec_task
    except asyncio.CancelledError: pass
    if self._ffmpeg.stdin: self._ffmpeg.stdin.close()
    self._ffmpeg.wait()

# %% ../nbs/01_cdp.ipynb #29c0632ab4804e98
class PostCapture(AttrDict): pass

# %% ../nbs/01_cdp.ipynb #cfdf94a8
async def _connect_cdp(port):
    'Try 127.0.0.1 then localhost to find the Chrome DevTools endpoint and connect'
    last_err = None
    for h in ('127.0.0.1', 'localhost'):
        try:
            async with httpx.AsyncClient() as c:
                url = (await c.get(f'http://{h}:{port}/json/version')).json()['webSocketDebuggerUrl']
            return await CDP.connect(wsconn=url)
        except Exception as e: last_err = e
    raise ConnectionRefusedError(f'no DevTools endpoint on port {port}') from last_err

# %% ../nbs/01_cdp.ipynb #7729f820
def _decode(b): return b.decode('utf-8', errors='replace') if isinstance(b, bytes) else b

def _parse_body(raw):
    "Parse a string body as JSON if possible, else return as-is"
    if raw is None: return None
    if isinstance(raw, (dict, list)): return raw
    try: return json.loads(raw)
    except (ValueError, TypeError): return raw

def _port_open(port):
    for host in ('localhost', '127.0.0.1'):
        try:
            with socket.create_connection((host, port), timeout=1): return True
        except OSError: pass
    return False

class CDPSession:
    "Sync-facing CDP session. Lazily connects to Chrome on first use."
    def __init__(self, port=9222, profile_dir=None):
        store_attr()
        self._cdp = None
        self._loop = asyncio.new_event_loop()
        self._thread = threading.Thread(target=self._loop.run_forever, daemon=True)
        self._thread.start()

    def _run(self, coro):
        "Submit coro to self._loop running in its background thread; block until done"
        return asyncio.run_coroutine_threadsafe(coro, self._loop).result()

    def _active_sid(self) -> str:
        "Return session ID for the active page, attaching to the first available tab if needed"
        if (res := self._run(self._cdp.active_page())) is not None: return res[1]
        pgs = [t for t in self._run(self._cdp('Target.getTargets')) if t['type'] == 'page']
        if not pgs:
            tid = self._run(self._cdp('Target.createTarget', url='about:blank'))
            if isinstance(tid, dict): tid = tid['targetId']
        else: tid = pgs[0]['targetId']
        return self._run(self._cdp.attach(tid))

    def ensure_connected(self):
        if self._cdp is None or not self._cdp.is_open:
            try: self._cdp = self._run(_connect_cdp(self.port))
            except Exception as ex:
                print(f"CDP connection failed on port {self.port}: {ex}. Attempting to launch Chrome...")
                self.launch()
                self._cdp = self._run(_connect_cdp(self.port))
        return self._active_sid()

    def close(self):
        if self._cdp and self._cdp.is_open: self._run(self._cdp.close())
        self._cdp = None

    def __enter__(self): return self
    def __exit__(self, *_): self.close()
    def __repr__(self): return f"CDPSession(port={self.port},connected={self._cdp is not None})"

# %% ../nbs/01_cdp.ipynb #a1d8b60a
_plat_loc = dict(
    darwin=[Path('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'),
            Path('/Applications/Chromium.app/Contents/MacOS/Chromium')],
    win32=[Path(os.environ.get('LOCALAPPDATA','')) / 'Google/Chrome/Application/chrome.exe',
           Path(os.environ.get('PROGRAMFILES','')) / 'Google/Chrome/Application/chrome.exe',
           Path(os.environ.get('PROGRAMFILES(X86)','')) / 'Google/Chrome/Application/chrome.exe'],
    linux=['google-chrome', 'google-chrome-stable', 'chromium-browser', 'chromium'])

def _linux_loc():
    for name in _plat_loc['linux']:
        p = Path(shutil.which(name) or Path('/usr/bin')/name)
        if p.exists(): return p
    return None

def _find_chrome(chrome_path=None):
    "Find Chrome/Chromium binary across platforms; raises FileNotFoundError if absent"
    if chrome_path: return chrome_path
    sp = sys.platform
    return _linux_loc() if sp == 'linux' else next(str(p) for p in _plat_loc[sp] if p.exists())

def _default_profile_dir():
    "Platform-appropriate CDP debug profile directory"
    if sys.platform == 'darwin': return str(Path.home()/'Library/Application Support/ChromeDebug')
    if sys.platform == 'win32': return str(Path(os.environ.get('LOCALAPPDATA', str(Path.home())))/'ChromeDebug')
    return str(Path.home()/'.config/chrome-debug')

@patch
def launch(self:CDPSession, wait=10, chrome_path=None) -> 'CDPSession':
    "Launch Chrome with remote debugging on self.port"
    chrome = _find_chrome(chrome_path)
    args = [chrome, f'--remote-debugging-port={self.port}',
            f'--user-data-dir={self.profile_dir or _default_profile_dir()}']
    subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(wait):
        time.sleep(1)
        if _port_open(self.port): return self
    return self

# %% ../nbs/01_cdp.ipynb #3c6d6cc5b391097f
from importlib.resources import files as _pkg_files

# %% ../nbs/01_cdp.ipynb #9f1e0c5b
def _launchd_registered(label): return subprocess.run(['launchctl', 'list', label], capture_output=True).returncode == 0

def _get_chrome_info(port:int=9222, chrome_path=None, profile_dir=None):
    "Return a dict of info needed to launch Chrome with CDP on macOS"
    return AttrDict(port=port, chrome=_find_chrome(chrome_path), label=f'com.fossick.chrome-debug-{port}',
        profile_dir=profile_dir or _default_profile_dir(), origins=f'http://localhost:{port},http://127.0.0.1:{port}')

def _mac_chrome(port:int=9222, chrome_path=None, profile_dir=None, uninstall:bool=False):
    "Set up a launchd agent to start Chrome with CDP on login. Idempotent. macOS only."
    ci, domain = _get_chrome_info(port, chrome_path, profile_dir), f'gui/{os.getuid()}'
    plist = Path.home() / f'Library/LaunchAgents/{ci.label}.plist'
    if uninstall:
        subprocess.run(['launchctl', 'bootout', f'{domain}/{ci.label}'], check=False)
        plist.unlink(missing_ok=True)
        return True
    log = str(Path.home() / f'Library/Logs/chrome-debug-{port}.log')
    pp = _pkg_files('fossick').joinpath('chrome_debug.plist')
    t = pp.read_text().format(log=log, **ci)
    plist.mk_write(t)
    if _launchd_registered(ci.label):
        subprocess.run(['launchctl', 'bootout', f'{domain}/{ci.label}'], check=False)
        for _ in range(20):
            time.sleep(0.1)
            if not _launchd_registered(ci.label): break
    r = subprocess.run(['launchctl', 'bootstrap', domain, str(plist)])
    if r.returncode == 5:
        # Service still in bootstrap namespace (e.g. prior interrupted run); force bootout and retry
        subprocess.run(['launchctl', 'bootout', f'{domain}/{ci.label}'], check=False)
        time.sleep(1.0)
        subprocess.run(['launchctl', 'bootstrap', domain, str(plist)], check=True)
    elif r.returncode:
        raise subprocess.CalledProcessError(r.returncode, r.args)
    return True

def _linux_chrome(port:int=9222, chrome_path=None, profile_dir=None, uninstall:bool=False):
    "Set up a systemd user service to start Chrome with CDP on login. Idempotent. Linux only."
    ci = _get_chrome_info(port, chrome_path, profile_dir)
    svc = Path.home() / f'.config/systemd/user/chrome-debug-{port}.service'
    if uninstall:
        subprocess.run(['systemctl', '--user', 'disable', '--now', svc.stem], check=False)
        svc.unlink(missing_ok=True)
        return True
    svc.mk_write(_pkg_files('fossick').joinpath('chrome_debug.service').read_text().format(**ci))
    subprocess.run(['systemctl', '--user', 'enable', '--now', svc.stem], check=True)
    return True

def _win_chrome(port:int=9222, chrome_path=None, profile_dir=None, uninstall:bool=False):
    "Set up a scheduled task to start Chrome with CDP on login. Idempotent. Windows only."
    ci, task = _get_chrome_info(port, chrome_path, profile_dir), f'ChromeDebug-{port}'
    if uninstall:
        subprocess.run(['schtasks', '/delete', '/tn', task, '/f'], check=False)
        return True
    with tempfile.NamedTemporaryFile(suffix='.xml', delete=False, mode='w', encoding='utf-8') as f:
        f.write(_pkg_files('fossick').joinpath('chrome_debug_task.xml').read_text().format(**ci))
        tmp = f.name
    subprocess.run(['schtasks', '/create', '/tn', task, '/xml', tmp, '/f'], check=True)
    Path(tmp).unlink(missing_ok=True)
    return True

def setup_chrome_daemon(port:int=9222, chrome_path=None, profile_dir=None, uninstall:bool=False) -> bool:
    "Install (or uninstall) a system service that starts Chrome with remote debugging at login"
    sp = sys.platform
    fn = _mac_chrome if sp == 'darwin' else _linux_chrome if sp == 'linux' else _win_chrome if sp == 'win32' else None
    if fn: return fn(port, chrome_path, profile_dir, uninstall)
    else: raise NotImplementedError(f'daemon setup not supported on {sp}')

# %% ../nbs/01_cdp.ipynb #fbf88ea695688618
async def _sniff_async(cdp, pattern, timeout, url, posts_only, record, record_path, sid, screenshot_path):
    staged, shot_n, rx = {}, [0], compile_pattern(pattern)
    await cdp.network.enable(sid=sid)
    if record: await cdp.start_recording(record_path, sid=sid)
    async def _handle_req(msg):
        p = msg['params']
        req = p.get('request', {})
        m = req.get('method', '')
        if posts_only and m != 'POST': return
        ru = req.get('url', '')
        if not rx.search(ru): return
        rid = p['requestId']
        staged[rid] = dict(url=ru, method=m, request_headers=dict(req.get('headers', {})), screenshot_path=None,
            request_body=_parse_body(req.get('postData')), response_body=None, timestamp=p.get('timestamp', 0.0))
        if screenshot_path:
            try:
                res = await cdp.page.captureScreenshot(format='png', sid=sid)
                base, n = Path(screenshot_path), shot_n[0]
                name = f'{base.stem}_{n}{base.suffix or '.png'}'
                shot_n[0] += 1
                sp = (base.parent / name) if base.is_absolute() else _cache(name)
                sp.write_bytes(base64.b64decode(res))
                staged[rid]['screenshot_path'] = str(sp)
            except Exception as e: print(f"screenshot failed: {e}")

    async with cdp.on('Network.requestWillBeSent') as req_q:
        async with cdp.on('Network.loadingFinished') as done_q:
            if url:
                nav = asyncio.create_task(cdp.goto(url, sid=sid, timeout=timeout))
                while not nav.done():
                    await asyncio.sleep(0.1)
                    while not req_q.empty(): await _handle_req(req_q.get_nowait())
                try: await nav
                except Exception: pass
            else:
                end = time.monotonic() + timeout
                while time.monotonic() < end:
                    await asyncio.sleep(0.1)
                    while not req_q.empty(): await _handle_req(req_q.get_nowait())
            await asyncio.sleep(0.5)
            while not req_q.empty(): await _handle_req(req_q.get_nowait())
            while not done_q.empty():
                msg = done_q.get_nowait()
                rid = msg['params']['requestId']
                if rid not in staged: continue
                try:
                    resp = await cdp.network.getResponseBody(requestId=rid, sid=sid)
                    body = resp.get('body', '')
                    if resp.get('base64Encoded'): body = base64.b64decode(body).decode('utf-8', errors='replace')
                    staged[rid]['response_body'] = _parse_body(body)
                except Exception: pass
    if record: await cdp.stop_recording(sid=sid)
    return [PostCapture(**d) for d in staged.values()]

# %% ../nbs/01_cdp.ipynb #b5ada56f39c386a6
@patch
def sniff(self:CDPSession, pattern='.*', timeout=30, url=None,
          record=False, record_path=None, posts_only=False,
          screenshot_path=None) -> list:
    "Sniff HTTP requests from Chrome. Passive (user browses) if url=None, active if url given."
    sid = self.ensure_connected()
    if record and record_path is None: record_path = str(_cache('recording.mp4'))
    return self._run(_sniff_async(self._cdp, pattern, timeout, url, posts_only, record, record_path, sid, screenshot_path))

# %% ../nbs/01_cdp.ipynb #fc94a18d
@patch
def to_paginate_args(self:CDPSession, capture:PostCapture) -> dict:
    "Convert a PostCapture into kwargs ready to unpack into paginate_api()"
    return dict(url=capture.url, payload=capture.request_body, method='POST', headers=capture.request_headers)

@patch
def replay(self:CDPSession, cap:PostCapture, body:dict=None, headers:dict=None) -> dict:
    "Replay a captured request with optional body/header overrides. Returns {url, status, html, data}."
    merged_body = {**cap.request_body, **(body or {})} if isinstance(cap.request_body, dict) else cap.request_body
    return fetch(cap.url, method='POST', payload=merged_body, headers={**cap.request_headers, **(headers or {})})

# %% ../nbs/01_cdp.ipynb #fd38e37e
@patch
def goto(self:CDPSession, url:str, timeout:int=30) -> None:
    "Navigate the active page to url"
    sid = self.ensure_connected()
    async def _nav():
        await self._cdp.page.navigate(url=url, sid=sid)
        end = time.monotonic() + timeout
        while time.monotonic() < end:
            await asyncio.sleep(0.5)
            try:
                r = await self._cdp.runtime.evaluate(expression='document.readyState', returnByValue=True, sid=sid)
                if (r.get('value', '') if isinstance(r, dict) else r) == 'complete': break
            except: break
    self._run(_nav())

# %% ../nbs/01_cdp.ipynb #3f3e8ee6
@patch
def source(self:CDPSession) -> dict:
    "Return current page as {'html': ..., 'url': ...} — pass directly to to_md()"
    sid = self.ensure_connected()
    async def _get():
        def _val(r): return r.get('value', '') if isinstance(r, dict) else (r or '')
        html = await self._cdp.runtime.evaluate(expression='document.documentElement.outerHTML', returnByValue=True, sid=sid)
        url = await self._cdp.runtime.evaluate(expression='window.location.href', returnByValue=True, sid=sid)
        return {'html': _val(html), 'url': _val(url)}
    return self._run(_get())

# %% ../nbs/01_cdp.ipynb #148af5ee
def automation_browser(port=9222, profile_dir=None) -> 'CDPSession':
    "CDPSession with a persistent debug profile — sessions and cookies survive across runs"
    return CDPSession(port=port, profile_dir=profile_dir)
