"""web search made easy

Docs: https://vedicreader.github.io/fossickcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['http_get', 'http_post', 'save_path', 'arun', 'clean_md', 'html2md', 'to_md', 'fetch', 'crawl', 'get_options',
           'fetch_all', 'get_pdf', 'read_arxiv', 'lookup_doi', 'url2nb', 'pdf2nb', 'read_gh_repo', 'read_gh_file',
           'compile_pattern', 'find_xhr', 'paginate_api', 'search_yt', 'read_yt', 'download_yt', 'repo_root',
           'mv_skill_md']

# %% ../nbs/00_core.ipynb #764d37b8
import json
from fastcore.all import Path, L, timed_cache, globtastic, parallel, joins, run, first, AttrDict, ifnone, fdelegates, bind
from fastcore.xdg import xdg_cache_home
from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type
from diskcache import Index
import re, httpx, shutil, time, os
import lxml.etree as etree
from scrapling import Selector
from scrapling.fetchers import AsyncFetcher, StealthyFetcher, DynamicFetcher
from urllib.parse import urljoin, urlparse, urlencode
import yt_dlp
from litesearch import *

# %% ../nbs/00_core.ipynb #98c2724e
@retry(wait=wait_exponential(1,30, min=2),stop=stop_after_attempt(4),
       retry=retry_if_exception_type((httpx.TimeoutException, IOError)))
def http_get(url, **kw):
    r = httpx.get(url, timeout=30, **kw)
    if r.status_code == 429: raise IOError(f"Rate limited (429): {url}")
    return r

@retry(wait=wait_exponential(1,30, min=2),stop=stop_after_attempt(4),
       retry=retry_if_exception_type((httpx.TimeoutException, IOError)))
def http_post(url, **kw):
    r = httpx.post(url, timeout=30, **kw)
    if r.status_code == 429: raise IOError(f"Rate limited (429): {url}")
    return r

def save_path(path=None):
    "Get cache path for `name` (e.g. 'arxiv' or 'fetch')"
    p = xdg_cache_home()/'.fossick'
    if path: p /= path
    p.parent.mkdir(parents=True, exist_ok=True)
    return p

# %% ../nbs/00_core.ipynb #5bc304cabff363f0
def arun(coro) -> any:
	'Run an async coroutine from sync code, even if already inside an event loop'
	import asyncio
	try: asyncio.get_running_loop()
	except RuntimeError: return L(asyncio.run(coro))
	import concurrent.futures
	with concurrent.futures.ThreadPoolExecutor() as pool: return L(pool.submit(asyncio.run, coro).result())

# %% ../nbs/00_core.ipynb #af8e28a1
def _html(x): return getattr(x, 'html', None) or (x['html'] if isinstance(x, dict) else x)
def _decode(b): return b.decode('utf-8', errors='replace') if isinstance(b, bytes) else b
def _wrap_md(text, tag): return f'\n<{tag}>\n{text}\n</{tag}>\n' if text else ''

def clean_md(text, rm_comments=True, rm_details=True):
    "Remove comments and `<details>` sections from `text`"
    if rm_comments: text = re.sub(r'\n?<!--.*?-->\n?', '', text, flags=re.DOTALL)
    if rm_details: text = re.sub(r'\n?<details>.*?</details>\n?', '', text, flags=re.DOTALL)
    return text

def html2md(s:str, ignore_links=True):
    "Convert `s` from HTML to markdown"
    import html2text
    o = html2text.HTML2Text(bodywidth=5000)
    o.ignore_links, o.mark_code, o.ignore_images = ignore_links, True, True
    return o.handle(s)

def to_md(page_or_html, # Page dict (from fetch/crawl) or raw HTML string
          sel:str=None, # CSS selector to extract before conversion; returns '' if no match
          multi:bool=False, # Return all selector matches joined
          wrap_tag:str=None, # Wrap each multi-result in <wrap_tag>...</wrap_tag>; only used when multi=True
          ignore_links:bool=True,
          rm_comments:bool=True,
          rm_details:bool=True,
         ) -> str:
    "Convert a Page dict or HTML string to clean markdown"
    html = _html(page_or_html)
    _md = lambda h: clean_md(html2md(str(h), ignore_links), rm_comments, rm_details)
    if sel:
	    els = Selector(html).css(sel)
	    mds = L(els).map(lambda m: _md(m.get()))
	    if multi: return joins('\n',mds.map(lambda m: _wrap_md(m, wrap_tag) if wrap_tag else m))
	    html = str(mds[0]) if mds else ''
    return _md(html)

# %% ../nbs/00_core.ipynb #02092330
def _get_page(url, method='GET', payload=None, heavy=False, stealthy=False, **kw):
    if method.upper() == 'POST': return arun(AsyncFetcher.post(url, json=payload, **kw))[0]
    if payload: kw['params'] = payload
    if not (heavy or stealthy): return arun(AsyncFetcher.get(url, **kw))[0]
    f = DynamicFetcher.async_fetch if heavy else StealthyFetcher.async_fetch
    return arun(f(url, **kw))[0]

# %% ../nbs/00_core.ipynb #02355c8f
def fetch(url:str,                # URL to fetch
          sel:str=None,           # CSS selector to extract (None = full page)
          method:str='GET',       # HTTP method; 'POST' sends payload as JSON body
          payload:dict=None,      # POST body (JSON) or GET query params
          heavy:bool=False,       # Full JS rendering via headless browser
          stealthy:bool=False,    # Anti-bot stealth fetcher (Cloudflare etc.)
          capture_xhr:bool=False, # Intercept XHR/fetch calls; forces heavy=True
          cache:bool=False,       # Cache successful responses to disk by URL+sel
          force:bool=False,       # If True, forces re-fetch even if cached result exists
          **kw,                   # Extra kwargs passed to scrapling (e.g. verify, headers)
         ) -> dict:
    "Fetch `url`, return Page dict {url, status, html, data, xhr} where html is raw response body"
    _key = f"{url}\x00{sel or ''}"
    if force and _key in _fetch_cache: del _fetch_cache[_key]
    if cache and _key in _fetch_cache: return _fetch_cache[_key]
    heavy = heavy or capture_xhr
    if capture_xhr: kw.setdefault('capture_xhr', '.*')
    page = _get_page(url, method=method, payload=payload, heavy=heavy, stealthy=stealthy, **kw)
    html = page.html_content
    if sel: html = str(el.get()) if (el:=page.css(sel).first) else ''
    try: data = json.loads(_decode(page.body))
    except (ValueError, TypeError): data = None
    except Exception as ex: data = f"Error parsing JSON: {ex}"
    xhr = []
    if capture_xhr:
        for x in page.captured_xhr:
            ct = next((v for k,v in dict(x.headers).items() if 'content-type' in k.lower()), '')
            b = _decode(x.body)
            try: d = json.loads(b)
            except (ValueError, TypeError): d = b
            xhr.append(AttrDict(url=x.url,content_type=ct, data=d))
    setattr(page, 'data', ifnone(data, html))
    setattr(page, 'xhr', xhr)
    setattr(page, 'html', html)
    if cache and page.status == 200: _fetch_cache[_key] = page
    return page

# %% ../nbs/00_core.ipynb #4eb76a6d
def crawl(start_url:str,               # URL to start from
          sel:str=None,                # CSS selector to extract per page
          follow_sel:str='a[href]',    # CSS selector for links to follow
          same_domain:bool=True,       # Only follow links on same domain
          max_pages:int=10,            # Max pages to visit
          delay:float=0,               # Seconds to wait between requests (polite crawling)
          heavy:bool=False,
          stealthy:bool=False,
          **kw,                        # Extra kwargs passed to scrapling (e.g. verify, timeout)
         ) -> list:
    "Crawl from `start_url`, following `follow_sel` links, return list of Page dicts"
    bd = urlparse(start_url).netloc
    v,q,res = set(),[start_url],[]
    while q and len(v) < max_pages:
        url = q.pop(0)
        if url in v: continue
        v.add(url)
        if delay and res: time.sleep(delay)
        try:
            pg = fetch(url, heavy=heavy, stealthy=stealthy, **kw)
            if pg.status != 200: continue
            page = Selector(pg.html)
            if sel: pg.html = str(el.get()) if (el:= page.css(sel).first) else ''
            res.append(pg)
            for link in page.css(follow_sel):
                href = link.attrib.get('href', '')
                if not href or href.startswith(('#', 'javascript:', 'mailto:')): continue
                abs_url = urljoin(url, href)
                if same_domain and urlparse(abs_url).netloc != bd: continue
                if abs_url not in v: q.append(abs_url)
        except Exception as ex:
	        print(f"Error fetching {url}: {ex}. Continuing crawl.")
	        continue
    return res

# %% ../nbs/00_core.ipynb #e4fa208c
def get_options(page_or_html,  # Page dict (from fetch) or raw HTML string
                sel:str         # CSS selector for the <select> element
               ) -> list:
    "Extract options from a <select> element; returns [{'value': ..., 'text': ...}]"
    return [{'value': el.attrib.get('value', el.text or ''), 'text': (el.text or '').strip()}
            for el in Selector(_html(page_or_html)).css(f'{sel} option')]

def fetch_all(urls:list,           # URLs to fetch
              sel:str=None,         # CSS selector to extract per page (None = full page)
              concurrency:int=8,    # Max parallel fetches
              heavy:bool=False,
              stealthy:bool=False,
              **kw                  # Extra kwargs passed to fetch()
             ) -> list:
    "Fetch a list of URLs in parallel; returns Page dicts in the same order as urls"
    return parallel(fetch, urls, sel=sel, heavy=heavy, stealthy=stealthy, threadpool=True, n_workers=concurrency, **kw)

# %% ../nbs/00_core.ipynb #2e71536ab2d8458a
def get_pdf(url:str):
    "Fetch PDF from URL and return as PdfDocument"
    r = _get_page(url)
    if r.status_code != 200: raise Exception(f"Failed to fetch PDF: {r.status_code}")
    return PdfDocument.from_bytes(r.content)

# %% ../nbs/00_core.ipynb #82eab014
_arxin = Index(str(save_path('arxiv_cache.db')))
_fetch_cache = {}
def _fetch_arxiv_meta(arxiv_id:str):
    "Fetch and parse arxiv metadata for a given ID; result is cached to disk"
    r = http_get(f'https://export.arxiv.org/api/query?id_list={arxiv_id}')
    if r.status_code != 200: raise Exception(f"Failed to fetch arxiv data: {r.status_code}")
    ns = {'a': 'http://www.w3.org/2005/Atom'}
    entry = etree.fromstring(r.content).find('a:entry', ns)
    if entry is None: raise Exception("No paper found")
    def txt(tag): return entry.find(f'a:{tag}', ns).text
    pu = first(L(entry.findall('a:link',ns)).filter(lambda l: l.get('title')=='pdf').map(lambda l: l.get('href')))
    au = L(entry.findall('a:author', ns)).map(lambda a: a.find('a:name', ns).text)
    return dict(title=txt('title').strip(), summary=txt('summary').strip(),
                published=txt('published'), link=txt('id'), pdf_url=pu, authors=au)

# %% ../nbs/00_core.ipynb #fb92f757aee11a3a
def read_arxiv(url:str, # arxiv PDF URL, or arxiv abstract URL, or arxiv ID
               save_pdf:bool=True, # if True, saves the downloaded PDF to disk
               save_dir:str='.', # directory in which to save the PDF
               force:bool=False # if True, forces re-download of PDF even if it exists on disk
               ):
    "Get paper information from arxiv URL or ID, optionally saving PDF to disk"
    arxiv_id = url.rsplit('/', 1)[-1]
    ver = re.search(r'v(\d+)$', arxiv_id)
    ver_sfx = f'v{ver.group(1)}' if ver else ''
    arxiv_id = re.sub(r'v\d+$', '', arxiv_id)
    pdf_path = Path(save_dir)/f'{arxiv_id}{ver_sfx}.pdf'
    if not force and arxiv_id in _arxin:
        res = dict(_arxin[arxiv_id])
        if save_pdf and pdf_path.exists(): res['pdf_path'] = pdf_path
        return res
    res = dict(_fetch_arxiv_meta(arxiv_id))
    if not res['pdf_url']: raise Exception("No PDF URL found in arxiv metadata")
    doc = get_pdf(res['pdf_url']) if not pdf_path.exists() else PdfDocument(str(pdf_path))
    if save_pdf:
        if not pdf_path.exists():
            pdf_path.parent.mkdir(parents=True, exist_ok=True)
            doc.save(str(pdf_path), compress=True, garbage_collect=True)
        res['pdf_path'] = pdf_path
    res |= dict(source=doc.to_markdown_all())
    _arxin[arxiv_id] = {k: v for k, v in res.items() if k != 'pdf_path'}
    return res

# %% ../nbs/00_core.ipynb #ae50b94929790ea9
def _crossref_search(**params):
    "Search Crossref API; returns parsed response dict"
    return fetch(f'https://api.crossref.org/works?{urlencode(params)}', verify=False).data or {}

_crossref = bind(_crossref_search, **{'select': 'DOI,title', 'rows': 1})

def lookup_doi(title:str  # Paper title to search
               ) -> str|None:
    "Return doi.org URL for first Crossref match on `title`"
    items = _crossref(**{'query.title': title}).get('message', {}).get('items', [])
    doi = items[0].get('DOI') if items else None
    return f"https://doi.org/{doi}" if doi else None

# %% ../nbs/00_core.ipynb #630cc1578fbce0a0
from fastcore.nbio import Notebook, mk_cell, new_nb, os

# %% ../nbs/00_core.ipynb #9920b4c93b17df75
def _nb_stem(url):
	"Derive a filesystem-safe notebook stem from a URL"
	path = urlparse(url).path.rsplit('/', 1)[-1].split('.')[0]
	stem = path or urlparse(url).netloc.split('.')[0]
	return re.sub(r'[^\w-]', '_', stem)[:50]

def _md2cells(md):
	"Split markdown into cells; [code]...[/code] blocks from html2text become code cells"
	def _text_segs(t):
		if re.search(r'\n#{1,3} ', t): return L(re.split(r'\n(?=#{1,3} )', t)).filter(str.strip).map(str.strip)
		return L(t.strip()).filter(str.strip)
	code_re = re.compile(r'\[code\]\n\n(.*?)\n\[/code\]', re.DOTALL)
	segments, last_end = [], 0
	for m in code_re.finditer(md):
		text = md[last_end:m.start()].strip()
		if text: segments += [('markdown', s) for s in _text_segs(text)]
		code = re.sub(r'^    ', '', m.group(1), flags=re.MULTILINE).strip()
		if code: segments += [('code', code)]
		last_end = m.end()
	if text := md[last_end:].strip(): segments += [('markdown', s) for s in _text_segs(text)]
	cells = []
	for i, (kind, content) in enumerate(segments):
		if kind == 'code': cells.append(mk_cell(content, 'code'))
		else:
			cells.append(mk_cell(content, 'markdown'))
			if i+1 >= len(segments) or segments[i+1][0] != 'code': cells.append(mk_cell(''))
	return cells

@fdelegates(fetch)
def url2nb(url, nb_path=None, **kwargs):
	"Convert any URL (PDF, arxiv, or HTML page) to a Jupyter notebook"
	if url.endswith('.pdf'): return pdf2nb(url, nb_path=nb_path, **kwargs)
	if 'arxiv.org' in url:
		res = read_arxiv(url)
		return pdf2nb(str(res['pdf_path']), nb_path=nb_path)
	md = to_md(fetch(url, **kwargs))
	nb_path = Path(nb_path or f'{_nb_stem(url)}.ipynb')
	Notebook(new_nb(cells=_md2cells(md)), path=nb_path).save()
	return nb_path

@fdelegates(fetch)
def pdf2nb(url_or_path, nb_path=None, image_dir='images', **kwargs):
	"Convert PDF to a Jupyter notebook; one markdown cell per page + empty code cell"
	url_or_path = str(url_or_path)
	if not url_or_path.endswith('.pdf'): return None
	if url_or_path.startswith('http'):
		pdf = PdfDocument.from_bytes(fetch(url_or_path, **kwargs).body)
		stem = url_or_path.rsplit('/', 1)[-1].replace('.pdf', '')
	else: pdf, stem = PdfDocument(url_or_path), Path(url_or_path).stem
	nb_path = Path(nb_path or f'{stem}.ipynb').resolve()
	cwd = os.getcwd()
	try:
		os.chdir(nb_path.parent)
		Path(image_dir).mkdir(exist_ok=True)
		pages = L(range(pdf.page_count())).map(
			lambda i: pdf.to_markdown(i, preserve_layout=True, include_images=True,
			                          embed_images=False, image_output_dir=image_dir))
	finally: os.chdir(cwd)
	cells = pages.map(lambda p: [mk_cell(p, 'markdown'), mk_cell('')]).concat()
	Notebook(new_nb(cells=cells), path=nb_path).save()
	return nb_path

# %% ../nbs/00_core.ipynb #9776e017
def _gh_ssh(url:str): # GitHub URL, SSH remote, or bare `user/repo`
    'Convert GitHub URL to SSH remote; pass through if already SSH; return None if not GitHub'
    if url.startswith('git@github.com:'): return url
    if m := re.match(r'https://github\.com/([^/]+)/([^/]+)', url):
        return f'git@github.com:{m.group(1)}/{m.group(2)}.git'

def _get_git_repo(gh_ssh:str):
    'Clone or update a GitHub repo to local cache; return Path'
    repo_name = gh_ssh.rsplit('/', 1)[-1].removesuffix('.git')
    repo_dir = save_path('git_clones')/repo_name
    if repo_dir.exists():
        try:
            run(['git', '-C', str(repo_dir), 'fetch'])
            branch = run(['git', '-C', str(repo_dir), 'symbolic-ref', 'refs/remotes/origin/HEAD']).split('/')[-1]
            run(['git', '-C', str(repo_dir), 'reset', '--hard', f'origin/{branch}'])
            return repo_dir
        except IOError: shutil.rmtree(repo_dir)
    repo_dir.parent.mkdir(parents=True, exist_ok=True)
    run(['git', 'clone', gh_ssh, str(repo_dir)])
    return repo_dir

@timed_cache(seconds=3600)
def read_gh_repo(path_or_url:str,  # GitHub URL, SSH address, or local path
                 globs:tuple=None,  # file glob patterns (default: README*, pyproject.toml, *.py)
                 limit:int=None,    # max files to return
                 as_list:bool=False # return list of Paths instead of {path: content} dict
                ):
    'Read files from a GitHub repo filtered by glob patterns'
    ssh = _gh_ssh(path_or_url)
    repo_dir = _get_git_repo(ssh) if ssh else Path(path_or_url)
    if globs is None: globs = ('README*', 'pyproject.toml', '*.py')
    files = L(p for g in globs for p in globtastic(repo_dir, file_glob=g, func=Path)).unique()
    if limit: files = files[:limit]
    if as_list: return files
    return {str(p): p.read_text(errors='ignore') for p in files}

def read_gh_file(url:str # GitHub blob URL of the file to read
                 ):
	'Read raw contents of a file from its GitHub URL'
	raw_url = re.sub(r'https://github\.com/([^/]+)/([^/]+)/blob/([^/]+)/(.+)',
	                 r'https://raw.githubusercontent.com/\1/\2/refs/heads/\3/\4', url)
	if (r:=http_get(raw_url)).status_code != 200: raise Exception(f"Failed to fetch {raw_url}: {r.status_code}")
	return r.text

# %% ../nbs/00_core.ipynb #26747505
def compile_pattern(pattern):
	"Compile pattern as regex; if invalid (e.g. bare glob like *foo*), convert via fnmatch first"
	try: return re.compile(pattern)
	except re.error:
		import fnmatch
		return re.compile(fnmatch.translate(pattern))

def find_xhr(url:str,             # URL to visit with browser
             pattern:str='*',     # Glob or regex pattern to filter captured XHR URLs
             json_only:bool=True, # Return only JSON responses
             **kw,                # Extra kwargs passed to fetch (verify, network_idle, etc.)
            ) -> list:
    "Visit `url` with a headless browser, return [{url, content_type, data}] for each XHR/fetch call made"
    kw.setdefault('network_idle', True)
    rx = compile_pattern(pattern)
    xhr = fetch(url, capture_xhr=True, **kw).xhr
    filtered = [x for x in xhr if rx.search(x.url)]
    if json_only: return [x for x in filtered if 'json' in x.content_type]
    return filtered

# %% ../nbs/00_core.ipynb #90674c61
def paginate_api(url:str,                      # API endpoint URL
                 payload:dict=None,            # Request body (POST) or params (GET)
                 page_field:str='pageNumber',  # Payload key to increment for each page
                 size_field:str='pageSize',    # Payload key for page size (detects last page)
                 results_field:str=None,       # Response key with items list (auto-detect if None)
                 method:str='POST',            # HTTP method
                 max_pages:int=10,
                 page_size=24,                 # Page size to request (only used if not in payload)
                 page_start:int=1,             # Starting page number (default 1)
                 save:bool=False,              # If True, saves each page's items to disk
                 save_file:str='{url}_page_{page}.json', # Filepath pattern for saving (only used if save=True)
                 force:bool=False,             # If True, forces re-fetching even if saved file exists
                 **kw,                         # Extra kwargs passed to fetch() (verify, headers, etc.)
                ) -> list:
    "Paginate through a JSON API, collecting all results. Auto-detects the items list in response."
    payload = dict(payload or {})
    page_size = payload.get(size_field, page_size)
    all_items = []
    for page_num in range(page_start, max_pages + page_start):
        sf = save_file.format(url=urlparse(url).netloc, page=page_num)
        if not force and Path(sf).exists():
            print(f"Page {page_num} already saved, skipping fetch")
            with open(sf) as f: all_items.extend(json.load(f)); continue
        pg = fetch(url, method=method, payload={**payload, page_field: page_num}, **kw)
        if pg.status != 200: break
        data = pg.data
        if data is None: break
        if isinstance(data, list): items = data
        elif results_field:
            raw = data.get(results_field, [])
            items = list(raw.values()) if isinstance(raw, dict) else raw
        else:
            lists = {k: v for k, v in data.items() if isinstance(v, list)}
            items = max(lists.values(), key=len) if lists else []
        if not items: break
        all_items.extend(items)
        if len(items) < page_size: break
        if save: Path(sf).write_text(json.dumps(items, indent=2))
    return all_items

# %% ../nbs/00_core.ipynb #a5faf465
_yt_cache = Index(str(save_path('yt_cache.db')))

def _yt_id(url:str) -> str:
    "Extract 11-char video ID from any YouTube URL or pass through bare ID"
    if m := re.search(r'(?:v=|youtu\.be/|/shorts/|/embed/)([A-Za-z0-9_-]{11})(?![A-Za-z0-9_-])', url): return m.group(1)
    return url

def _parse_vtt(vtt:str) -> str:
    "Strip VTT timing lines and cue tags, deduplicate adjacent lines, return plain text"
    lines = []
    for line in vtt.splitlines():
        if (re.match(r'^\d{2}:\d{2}', line) or '-->' in line
                or re.match(r'^(WEBVTT|Kind:|Language:|NOTE)', line)
                or not line.strip()): continue
        text = re.sub(r'<[^>]+>', '', line).strip()
        if text and (not lines or lines[-1] != text): lines.append(text)
    return ' '.join(lines)

# %% ../nbs/00_core.ipynb #121b6c36
def search_yt(q:str, n:int=10) -> L:
    "Search YouTube; returns L of dicts: id, title, url, duration, view_count, channel, description, thumbnail"
    try:
        with yt_dlp.YoutubeDL({'quiet': True, 'extract_flat': True}) as ydl:
            info = ydl.extract_info(f'ytsearch{n}:{q}', download=False)
        return L({'id': e.get('id'),
                  'title': e.get('title'),
                  'url': e.get('url') or f'https://www.youtube.com/watch?v={e.get("id")}',
                  'duration': e.get('duration'),
                  'view_count': e.get('view_count'),
                  'channel': e.get('channel'),
                  'description': e.get('description'),
                  'thumbnail': next((t['url'] for t in reversed(e.get('thumbnails', [])) if 'url' in t), None)}
                 for e in info.get('entries', []))
    except Exception as e:
        print(f'search_yt error: {e}')
        return L()

# %% ../nbs/00_core.ipynb #7b7605a3
def read_yt(url:str, force:bool=False) -> dict:
    "Fetch YouTube metadata + English transcript (auto-captions); result disk-cached by video ID"
    vid = _yt_id(url)
    if not force and vid in _yt_cache: return _yt_cache[vid]
    with yt_dlp.YoutubeDL({'quiet': True, 'skip_download': True}) as ydl:
        info = ydl.extract_info(f'https://www.youtube.com/watch?v={vid}', download=False)
    caps = info.get('automatic_captions', {})
    en_caps = caps.get('en') or caps.get('en-orig') or []
    vtt_url = next((c['url'] for c in en_caps if c.get('ext') == 'vtt'), None)
    source = ''
    if vtt_url:
        r = http_get(vtt_url)
        if r.status_code == 200: source = _parse_vtt(r.text)
    res = dict(title=info.get('title', ''),
               channel=info.get('channel') or info.get('uploader', ''),
               description=info.get('description', ''),
               duration=info.get('duration'),
               upload_date=info.get('upload_date'),
               source=source)
    _yt_cache[vid] = res
    return res

# %% ../nbs/00_core.ipynb #ae3a464c
def download_yt(url:str, format:str='audio', save_dir:str='.', quality:str=None) -> Path:
    "Download YouTube media; format='audio'|'video'|yt-dlp format string. Returns Path to saved file."
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    outtmpl = str(save_dir / '%(title)s.%(ext)s')
    if format == 'audio':
        opts = {'quiet': True, 'format': 'bestaudio/best', 'outtmpl': outtmpl,
                'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3',
                                    'preferredquality': quality or '192'}]}
    elif format == 'video':
        opts = {'quiet': True, 'format': 'bestvideo+bestaudio/best', 'outtmpl': outtmpl,
                'merge_output_format': 'mp4'}
    else:
        opts = {'quiet': True, 'format': format, 'outtmpl': outtmpl}
    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=True)
        stem = Path(ydl.prepare_filename(info)).stem
    ext = 'mp3' if format == 'audio' else ('mp4' if format == 'video' else '*')
    candidates = sorted(save_dir.glob(f'{stem}*.{ext}'))
    return candidates[0] if candidates else save_dir / f'{stem}.{ext}'

# %% ../nbs/00_core.ipynb #a23a6173
def repo_root() -> Path:
    'Find the root of the current git repository, or None if not in a repo.'
    return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def mv_skill_md(dry_run=True, dir=None) -> None:
    'Copy bundled SKILL.md to skill directories.'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    if not (src := base.joinpath('SKILL.md')).exists(): return
    root = dir or repo_root() or '.'
    ts = [Path(root)/'.agents/skills/fossick/SKILL.md', Path('.claude/skills/fossick/SKILL.md')]
    if dry_run: print(f'Would copy {src} to: {list(map(str,ts))}')
    else:
        [p.mk_write(src.read_text(encoding='utf-8')) for p in ts]
        print(f'Installed → {list(map(str,ts))}')
