"""fetching , github, arxiv, url2md and more

Docs: https://vedicreader.github.io/fossick/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['http_get', 'http_post', 'fossick_cache', 'syncy', 'html2md', 'to_md', 'http_page', 'get_page', 'fetch',
           'browser_session', 'crawl', 'get_options', 'fetch_all', 'get_pdf', 'read_arxiv', 'lookup_doi', 'clean_md',
           'ocr_parse', 'pdf2md', 'url2nb', 'pdf2nb', 'read_gh_repo', 'read_gh_file', 'compile_pattern', 'find_xhr',
           'replay_xhr', 'paginate_api', 'download_files', 'search_yt', 'read_yt', 'download_yt', 'repo_root',
           'mv_skill_md']

# %% ../nbs/00_core.ipynb #e4a80ed3a7db03d0
import json, asyncio, threading
from fastcore.all import Path,L,timed_cache,globtastic,parallel,run,first,AttrDict,ifnone,fdelegates,bind,patch,setattrs
from fastcore.xdg import xdg_cache_home
import re, shutil, time, os, base64
from contextlib import contextmanager, nullcontext
from collections import deque
import lxml.etree as etree
from scrapling import Selector
from scrapling.engines.toolbelt.custom import Response
from urllib.parse import urlparse, urlencode
from functools import cache

# %% ../nbs/00_core.ipynb #b7683b88563710b3
def fossick_cache(path=None):
    "Get cache path for `name` (e.g. 'arxiv' or 'fetch')"
    p = xdg_cache_home()/'.fossick'
    if path: p /= path
    p.parent.mkdir(parents=True, exist_ok=True)
    return p

# %% ../nbs/00_core.ipynb #ba561b54822b02d0
_loop = None
def _bridge():
    "The one background event loop the package drives async work on, started on first use."
    global _loop
    if _loop is None:
        _loop = asyncio.new_event_loop()
        threading.Thread(target=_loop.run_forever, daemon=True).start()
    return _loop

def syncy(coro, tout=60):
    "Run `coro` on the shared background loop from sync code, even inside a running loop."
    return asyncio.run_coroutine_threadsafe(coro, _bridge()).result(timeout=tout)

@patch
def mk_bytes(self:Path, data, mode=511, uid=-1, gid=-1):
	"Make all parent dirs of `self`, and write `data`"
	self.parent.mkdir(exist_ok=True, parents=True, mode=mode)
	self.write_bytes(data)
	if uid!=-1 or gid!=-1: os.chown(self, uid, gid)

# %% ../nbs/00_core.ipynb #b6562f33262bfafc
def _wrap_md(text, tag): return f'\n<{tag}>\n{text}\n</{tag}>\n' if text else ''

def _html(res_or_html):
    'Extract HTML string from a Page dict or return input if already a string'
    if isinstance(res_or_html, str): return res_or_html
    elif isinstance(res_or_html, Response):
	    return res_or_html.html if getattr(res_or_html,'html', None) is not None else res_or_html.html_content
    return None

def html2md(s:str, ignore_links=True, ignore_images=False):
    'Convert `s` from HTML to markdown'
    import html2text
    from readability import Document
    o = html2text.HTML2Text(bodywidth=5000)
    o.ignore_links, o.mark_code, o.ignore_images = ignore_links, True, ignore_images
    return o.handle(Document(s).summary(keep_all_images=True)) if s.strip() else ''

def to_md(res_or_html,  # Page dict (from fetch/crawl) or raw HTML string
          sel:str=None,  # CSS selector to extract before conversion; returns '' if no match
          multi:bool=False,  # Return all selector matches joined
          wrap_tag:str=None,  # Wrap each multi-result in <wrap_tag>...</wrap_tag>; only used when multi=True
          ignore_links:bool=True,
          ignore_images:bool=False,
          ) -> str:
    'Convert a Page dict or HTML string to clean markdown'
    html = _html(res_or_html)
    _md = lambda h: html2md(str(h), ignore_links, ignore_images)
    if sel:
	    els = Selector(html).css(sel)
	    mds = L(els).map(lambda m: _md(m.get()))
	    if multi: return '\n'.join(mds.map(lambda m: _wrap_md(m, wrap_tag) if wrap_tag else m))
	    html = str(mds[0]) if mds else ''
    return _md(html)

# %% ../nbs/00_core.ipynb #9f5a399cf870a5d1
@cache
def _fetcher():
    """scrapling's plain-HTTP Fetcher, imported on first request. It pulls curl_cffi and
    playwright's generated bindings — 0.21s of import for something only http_page and
    replay_xhr touch."""
    from scrapling.fetchers import Fetcher
    return Fetcher

def http_page(url, method='GET', payload=None, verify=False, **kw) -> Response:
	F, kw = _fetcher(), dict(verify=verify) | kw
	if method.upper() == 'POST': return F.post(url, json=payload, **kw)
	if method.upper() == 'PUT': return F.put(url, json=payload, **kw)
	if payload: kw['params'] = payload
	if method.upper() == 'DELETE': return F.delete(url, **kw)
	if method.upper() == 'GET': return F.get(url, **kw)
	else: raise ValueError(f"Unsupported method: {method}")

def get_page(url, method='GET', payload=None, heavy=False, stealthy=False, session=False, **kw) -> Response:
	"Fetch `url`. `session=True` (or a port int) drives the persistent debug Chrome via CDP, reusing its logged-in cookies."
	assert method.upper() in ('GET', 'POST'), 'Only GET and POST methods are supported'
	if session:
		from fossick.cdp import cdp_ws, cdp_cookies
		port = 9223 if session is True else int(session)
		kw.setdefault('cdp_url', cdp_ws(port))
		if (ck := cdp_cookies(url, port=port)): kw.setdefault('cookies', ck)
		kw.pop('verify', None)
		if not stealthy: heavy = True
	if not (heavy or stealthy): return http_page(url, method, payload, **kw)
	from scrapling.fetchers import StealthyFetcher, DynamicFetcher
	f = DynamicFetcher.async_fetch if heavy else StealthyFetcher.async_fetch
	return syncy(f(url, **kw))

http_get = bind(get_page, method='GET', verify=True, timeout=30)
http_post = bind(get_page, method='POST', timeout=30)

# %% ../nbs/00_core.ipynb #4c84bd2931cbee8e
_BLOCK_MARKERS = ('cf-chl', 'just a moment', 'attention required', 'checking your browser',
                  'cf-browser-verification', 'cf-turnstile', 'access denied', 'enable javascript',
                  'g-recaptcha', 'h-captcha', 'captcha-delivery',   # captcha *widgets*, not the bare word 'captcha'
                  "making sure you're not a bot", 'id="anubis')     # Anubis proof-of-work wall

def _blocked(page) -> bool:
    "Heuristic: did this response hit a bot wall / challenge page (so we should escalate)?"
    if page is None: return True
    st = getattr(page, 'status', 200)
    if st in (401, 403, 429, 503, 530): return True
    html = getattr(page, 'html', None) or getattr(page, 'html_content', '') or ''
    low = html.lower()
    if any(m in low for m in _BLOCK_MARKERS): return True
    return st == 200 and len(html.strip()) < 200

def _finish(page, sel=None, capture_xhr=False) -> Response:
    "Attach `.html` (raw or `sel`-extracted) and `.xhr` to a scrapling Response"
    html = page.html_content
    if sel: html = str(el.get()) if (el:=page.css(sel).first) else ''
    xhr = []
    if capture_xhr:
        for x in page.captured_xhr:
            ct = x.headers.get('content-Type', '')
            try: d = x.json()
            except: d = x.text or x.body.decode(errors='replace')
            xhr.append(AttrDict(url=x.url, content_type=ct, data=d))
    setattr(page, 'xhr', xhr)
    setattr(page, 'html', html)
    return page

_AUTO_TIERS = (dict(), dict(heavy=True), dict(stealthy=True), dict(stealthy=True, session=True))

def _fetch_auto(url, sel=None, tiers=_AUTO_TIERS, **kw) -> Response:
    "Escalate plain -> heavy -> stealthy -> stealthy+debug-Chrome until a non-blocked response; sets `.tier`."
    page = None
    for opts in tiers:
        try: page = fetch(url, sel=sel, **opts, **kw)
        except Exception: page = None; continue
        if not _blocked(page):
            setattr(page, 'tier', '+'.join(k for k, v in opts.items() if v) or 'plain')
            return page
    if page is not None: setattr(page, 'tier', 'blocked')
    return page

def fetch(url:str,                # URL to fetch
          sel:str=None,           # CSS selector to extract (None = full page)
          method:str='GET',       # HTTP method; 'POST' sends payload as JSON body
          payload:dict=None,      # POST body (JSON) or GET query params
          heavy:bool=False,       # Full JS rendering via headless browser
          stealthy:bool=False,    # Anti-bot stealth fetcher (Cloudflare etc.)
          capture_xhr:bool=False, # Capture XHR calls made by the page (only works with heavy or stealthy)
          session:bool=False,     # Route through the persistent debug Chrome (reuses its logged-in cookies); True or a port int
          auto:bool=False,        # Auto-escalate plain->heavy->stealthy->session on bot-block detection
          **kw,                   # Extra kwargs passed to scrapling (e.g. verify, headers)
         ) -> Response:
    'Fetch `url`, return a Response with `.html` (raw or `sel`-extracted), `.xhr`, `.status`.'
    if auto: return _fetch_auto(url, sel=sel, method=method, payload=payload, capture_xhr=capture_xhr, **kw)
    heavy = heavy or capture_xhr
    if capture_xhr: kw.setdefault('capture_xhr', '.*')
    page = get_page(url, method=method, payload=payload, heavy=heavy, stealthy=stealthy, session=session, **kw)
    return _finish(page, sel, capture_xhr)

@contextmanager
def browser_session(stealthy:bool=False, headless:bool=True, **init_kw):
    "Open ONE browser and yield a `fetch(url, sel=None, **)` func that reuses it across calls (skips per-URL relaunch)."
    from scrapling.fetchers import AsyncDynamicSession, AsyncStealthySession
    init_kw.pop('verify', None)
    Sess = AsyncStealthySession if stealthy else AsyncDynamicSession
    s = Sess(headless=headless, **init_kw)
    syncy(s.__aenter__())
    try:
        def _f(u, sel=None, **fkw): return _finish(syncy(s.fetch(u, **fkw)), sel)
        yield _f
    finally: syncy(s.__aexit__(None, None, None))


# %% ../nbs/00_core.ipynb #c7bbdc6057317dca
def crawl(start_url:str,               # URL to start from
          sel:str=None,                # CSS selector to extract per page
          follow_sel:str='a[href]',    # CSS selector for links to follow
          same_domain:bool=True,       # Only follow links on same domain
          max_pages:int=10,            # Max pages to visit
          delay:float=0,               # Seconds to wait between requests (polite crawling)
          heavy:bool=False, # Full JS rendering via headless browser
          stealthy:bool=False, # Anti-bot stealth fetcher (Cloudflare etc.)
          reuse:bool=True,  # For heavy/stealthy crawls, keep one browser open across pages
          **kw,                        # Extra kwargs passed to scrapling (e.g. verify, timeout)
         ) -> list:
    'Crawl from `start_url`, following `follow_sel` links, return list of Page dicts'
    bd, v, q, res = urlparse(start_url).netloc, set(), deque([start_url]), []
    use_sess = reuse and (heavy or stealthy)
    ctx = browser_session(stealthy=stealthy, **kw) if use_sess else nullcontext(None)
    with ctx as sess:
        while q and len(v) < max_pages:
            url = q.popleft()
            if url in v: continue
            v.add(url)
            if delay and res: time.sleep(delay)
            try:
                pg: Response = sess(url) if sess else fetch(url, heavy=heavy, stealthy=stealthy, **kw)
                if pg.status != 200: continue
                if sel: pg.html = str(el.get()) if (el:= pg.css(sel).first) else ''
                res.append(pg)
                for link in pg.css(follow_sel):
                    href = link.attrib.get('href', '')
                    if not href or href.startswith(('#', 'javascript:', 'mailto:')): continue
                    abs_url = pg.urljoin(href)
                    if same_domain and urlparse(abs_url).netloc != bd: continue
                    if abs_url not in v: q.append(abs_url)
            except Exception as ex:
                print(f"Error fetching {url}: {ex}. Continuing crawl.")
                continue
    return res

# %% ../nbs/00_core.ipynb #498a122a6d567879
def get_options(page_or_html,  # Page dict (from fetch) or raw HTML string
                sel:str         # CSS selector for the <select> element
               ) -> list:
    "Extract options from a <select> element; returns [{'value': ..., 'text': ...}]"
    return [{'value': el.attrib.get('value', el.text or ''), 'text': (el.text or '').strip()}
            for el in Selector(_html(page_or_html)).css(f'{sel} option')]

def fetch_all(urls:list,           # URLs to fetch
              sel:str=None,         # CSS selector to extract per page (None = full page)
              concurrency:int=8,    # Max parallel fetches
              heavy:bool=False, # Full JS rendering via headless browser
              stealthy:bool=False, # Anti-bot stealth fetcher (Cloudflare etc.)
              **kw                  # Extra kwargs passed to fetch()
             ) -> list:
    "Fetch a list of URLs in parallel; returns Page dicts in the same order as urls"
    return parallel(fetch, urls, sel=sel, heavy=heavy, stealthy=stealthy, threadpool=True, n_workers=concurrency, **kw)

# %% ../nbs/00_core.ipynb #a808c2b15c3cec10
from liteparse import LiteParse
from pdf_oxide import PdfDocument

# %% ../nbs/00_core.ipynb #80f691ca933d706
def _is_pdf(b) -> bool:
    "True when `b` starts with the %PDF- magic bytes (allowing leading whitespace/junk)."
    return isinstance(b, bytes) and b'%PDF-' in b[:1024]

def get_pdf(url_or_path:str, # URL or local path to PDF
            save_path=None, # optional path to save the PDF (directory or full path)
            **scrapling_kw # extra kwargs passed to scrapling fetcher (e.g. verify, headers, timeout)
            ) -> PdfDocument|None:
    """Fetch PDF from URL or path and return as PdfDocument, or None if it is not a PDF.

    Identity comes from the %PDF- magic bytes, not the URL suffix. arXiv serves its PDFs from
    extensionless URLs (`arxiv.org/pdf/1706.03762v7`), so a suffix check rejected every paper
    fossick is most used to read."""
    pth = Path(url_or_path) if not url_or_path.startswith('http') else None
    if pth: src = pth.read_bytes() if pth.exists() else None
    else: src = r.body if (r:=get_page(url_or_path, **scrapling_kw)).status == 200 else None
    if not _is_pdf(src): return None
    if save_path:
        pth = p/url_or_path.rsplit('/', 1)[-1].split('?')[0] if (p:=Path(save_path)).is_dir() else p
        if not pth.suffix: pth = pth.with_suffix('.pdf')
        pth.mk_bytes(src)
    return PdfDocument.from_bytes(src)

# %% ../nbs/00_core.ipynb #da946b97ed964105
@cache
def _arxiv_index():
    "Disk cache for arXiv metadata, opened on first use rather than at import."
    from diskcache import Index
    return Index(str(fossick_cache('arxiv_cache.db')))

def _fetch_arxiv_meta(arxiv_id:str, **kw):
    "Fetch and parse arxiv metadata for a given ID; result is cached to disk"
    r = http_get(f'https://export.arxiv.org/api/query?id_list={arxiv_id}', **kw)
    if r.status != 200: raise Exception(f"Failed to fetch arxiv data: {r.status}")
    ns = {'a': 'http://www.w3.org/2005/Atom'}
    entry = etree.fromstring(r.body).find('a:entry', ns)
    if entry is None: raise Exception("No paper found")
    def txt(tag): return entry.find(f'a:{tag}', ns).text
    pu = first(L(entry.findall('a:link',ns)).filter(lambda l: l.get('title')=='pdf').map(lambda l: l.get('href')))
    au = L(entry.findall('a:author', ns)).map(lambda a: a.find('a:name', ns).text)
    return dict(title=txt('title').strip(), summary=txt('summary').strip(),
                published=txt('published'), link=txt('id'), pdf_url=pu, authors=list(au))

# %% ../nbs/00_core.ipynb #d2ed0fcb31d735a8
def _arxiv_key(url:str) -> tuple:
    "Split an arXiv URL/ID into its bare id and version suffix, e.g. '1706.03762', 'v7'."
    aid = url.rsplit('/', 1)[-1]
    ver = re.search(r'v(\d+)$', aid)
    return re.sub(r'v\d+$', '', aid), (f'v{ver.group(1)}' if ver else '')

def read_arxiv(url:str, # arxiv PDF URL, or arxiv abstract URL, or arxiv ID
               save_pdf:bool=True, # if True, saves the downloaded PDF to disk
               save_dir:str='.', # directory in which to save the PDF
               source:bool=False, # if True, also extract the paper's full text into `source`
               force:bool=False, # if True, forces re-download even if cached
               **kw # http_get kwargs (e.g. verify=False to skip SSL verification, headers=... etc.)
               )-> dict:
    """Paper metadata from an arXiv URL or ID: `title, authors, summary, published, link, pdf_url,
    pdf_path` and, with `source=True`, the full text in `source`. The live `PdfDocument` comes back
    under `doc` when this call downloaded one.

    Only JSON-able fields are cached — a `PdfDocument` is a live handle, not cache content."""
    arxiv_id, ver_sfx = _arxiv_key(url)
    key, idx = f'{arxiv_id}{ver_sfx}', _arxiv_index()
    if force: idx.pop(key, None)
    res = dict(idx[key]) if key in idx else None
    pdf_path = Path(save_dir)/f'{key}.pdf' if save_pdf else None
    if res is None:
        res = dict(_fetch_arxiv_meta(arxiv_id, **kw))   # kw belongs to the request, not the result
        if not res['pdf_url']: raise Exception("No PDF URL found in arxiv metadata")
        res['pdf_path'] = None
    have = bool(res.get('pdf_path')) and Path(res['pdf_path']).exists()
    doc, want_src = None, source and not res.get('source')
    if (save_pdf and not have) or want_src:
        doc = get_pdf(res['pdf_url'], save_path=pdf_path, **kw)
        if doc is None: raise Exception(f"Could not download the PDF for {key} from {res['pdf_url']}")
        if pdf_path: res['pdf_path'] = str(pdf_path)
    if want_src: res['source'] = pdf2md(doc, out_path=Path(save_dir)/f'{key}.ipynb')
    idx[key] = res
    return dict(res, doc=doc)

# %% ../nbs/00_core.ipynb #bb7d64207baa24dd
def _crossref_search(**params):
    "Search Crossref API; returns parsed response dict"
    return fetch(f'https://api.crossref.org/works?{urlencode(params)}', verify=False).json() or {}

_crossref = bind(_crossref_search, **{'select': 'DOI,title', 'rows': 1})

def lookup_doi(title:str  # Paper title to search
               ) -> str|None:
    "Return doi.org URL for first Crossref match on `title`"
    items = _crossref(**{'query.title': title}).get('message', {}).get('items', [])
    doi = items[0].get('DOI') if items else None
    return f"https://doi.org/{doi}" if doi else None

# %% ../nbs/00_core.ipynb #cd60649f4b02946
from fastcore.nbio import Notebook, mk_cell, new_nb, os

# %% ../nbs/00_core.ipynb #cbdc59dfa84bac04
def _nb_stem(url):
	"Derive a filesystem-safe notebook stem from a URL"
	path = urlparse(url).path.rsplit('/', 1)[-1].split('.')[0]
	stem = path or urlparse(url).netloc.split('.')[0]
	return re.sub(r'[^\w-]', '_', stem)[:50]

def clean_md(md):
	md = re.sub(r'([a-z])-\n([a-z])', r'\1\2', md)
	md = re.sub(r'([a-z])-\n([A-Z])', r'\1-\2', md)
	md = re.sub(r'^ +', '', md, flags=re.M)
	md = re.sub(r' {2,}', ' ', md)
	return re.sub(r'\n{3,}', '\n\n', md)

def _text_segs(t): return [c.strip() for c in re.split(r'\n(?=#{1,3} )', t) if c.strip()]

def _md2cells(md):
	'Split markdown into cells; [code]...[/code] blocks from html2text become code cells'
	code_re = re.compile(r'\[code\]\n\n(.*?)\n\[/code\]', re.DOTALL)
	segments, last_end = [], 0
	for m in code_re.finditer(md):
		text = md[last_end:m.start()].strip()
		if text: segments += [('markdown', s) for s in _text_segs(text)]
		code = re.sub(r'^    ', '', m.group(1), flags=re.MULTILINE).strip()
		if code: segments += [('code', code)]
		last_end = m.end()
	if text := md[last_end:].strip(): segments += [('markdown', s) for s in _text_segs(text)]
	cells = []
	for i, (kind, content) in enumerate(segments):
		if kind == 'code': cells.append(mk_cell(content, 'code'))
		else: cells.append(mk_cell(content, 'markdown'))
	return cells

def ocr_parse(pdf:PdfDocument, # PdfDocument object
              **kw  # extra kwargs passed to LiteParse (e.g. dpi, num_workers, extract_links)
) -> str:
	lp = LiteParse(ocr_enabled=True, dpi=300, num_workers=4, extract_links=True, **kw)
	md = lp.parse(pdf.to_bytes()).text
	md = clean_md(md)
	return md

@fdelegates(ocr_parse)
def pdf2md(pdf:PdfDocument,  # PdfDocument object
           out_path:str|Path,  # Path to notebook file (used to determine image output dir)
           image_dir='images',  # subdir for extracted images
           preserve_layout=False,  # preserrve layout in pdf-oxide
           ocr_selection:str='auto'  # choosing ocr (auto, off, on). auto uses pdf-oxide's ocr detection
           ) -> str:
	'PdfDocument to markdown; if OCR is required, uses LiteParse for better formatting'
	if ocr_selection == 'on': return ocr_parse(pdf)
	cwd = os.getcwd()
	out_path = Path(out_path).resolve()
	try:                                     # restore cwd even when pdf-oxide raises
		os.chdir(out_path.parent)
		imdir = Path(out_path.stem) / image_dir
		Path(imdir).mkdir(exist_ok=True, parents=True)
		md = clean_md(pdf.to_markdown_all(preserve_layout, include_images=True,
		                                  embed_images=False, image_output_dir=str(imdir)))
	finally: os.chdir(cwd)
	if ocr_selection == 'off': return md
	if '> [OCR REQUIRED' in md.strip(): return ocr_parse(pdf)
	return md

@fdelegates(fetch)
def url2nb(url, # URL to convert (PDF, arxiv, or HTML page)
           nb_path=None, # optional path to save the notebook; defaults to <url-stem>.ipynb
           force=False, # if True, forces re-download and conversion even if notebook exists
           **kwargs # extra kwargs passed to fetch() (e.g. verify=False to skip SSL verification)
)-> Path:
	'Convert any URL (PDF, arxiv, or HTML page) to a Jupyter notebook'
	if url.endswith('.pdf'): return pdf2nb(url, nb_path=nb_path, **kwargs)
	nb_path = Path(nb_path or f'{_nb_stem(url)}.ipynb')
	if nb_path.exists() and not force: return nb_path
	if 'arxiv.org' in url:
		res = read_arxiv(url, save_dir=str(nb_path.parent))
		return pdf2nb(res['pdf_path'], nb_path=nb_path, force=force, **kwargs)
	md = to_md(fetch(url, **kwargs))
	Notebook(new_nb(cells=_md2cells(md)), path=nb_path).save()
	return nb_path

@fdelegates(fetch)
def pdf2nb(u_or_p,  # URL or local path to PDF
           nb_path=None,  # optional path to save the notebook; defaults to <pdf-stem>.ipynb
           force=False,  # if True, forces re-download and conversion even if notebook exists
           ocr_selection:str='auto',  # choosing ocr (auto, off, on). auto uses pdf-oxide's ocr detection
           **kwargs,  # extra kwargs passed to fetch() (e.g. verify=False to skip SSL verification)
           ) -> Path:
	'Convert PDF to a Jupyter notebook; one markdown cell per page + empty code cell'
	stem = Path(u_or_p).stem if not u_or_p.startswith('http') else u_or_p.rsplit('/', 1)[-1].split('.')[0]
	pth = nb_path or f'{stem}.ipynb'
	nb_path = Path(pth).resolve()
	if nb_path.exists() and not force: return nb_path
	pdf = get_pdf(u_or_p, **kwargs)
	if not pdf: raise Exception("Failed to fetch or parse PDF")
	text = pdf2md(pdf, out_path=nb_path, ocr_selection=ocr_selection)
	Notebook(new_nb(cells=_md2cells(text)), path=nb_path).save()
	return nb_path

# %% ../nbs/00_core.ipynb #b3518187d2621cbc
def _gh_remotes(url:str) -> L: # GitHub URL or SSH remote
    'Clone URLs for a GitHub repo, HTTPS first so a public repo needs no key. Empty if not GitHub.'
    if url.startswith('git@github.com:'): return L(url)
    if m := re.match(r'https?://github\.com/([^/]+)/([^/]+?)(?:\.git)?(?:/|$)', url):
        return L(f'https://github.com/{m[1]}/{m[2]}.git', f'git@github.com:{m[1]}/{m[2]}.git')
    return L()

def _get_git_repo(remotes):
    'Clone or update a GitHub repo to local cache; return Path'
    remotes = L(remotes)
    repo_dir = fossick_cache('git_clones') / remotes[0].rsplit('/', 1)[-1].removesuffix('.git')
    if repo_dir.exists():
        try:
            run(['git', '-C', str(repo_dir), 'fetch'])
            branch = run(['git', '-C', str(repo_dir), 'symbolic-ref', 'refs/remotes/origin/HEAD']).split('/')[-1]
            run(['git', '-C', str(repo_dir), 'reset', '--hard', f'origin/{branch}'])
            return repo_dir
        except IOError: shutil.rmtree(repo_dir)
    repo_dir.parent.mkdir(parents=True, exist_ok=True)
    for r in remotes:                       # HTTPS, then SSH: a private repo still works with a key
        try:
            run(['git', 'clone', r, str(repo_dir)])
            return repo_dir
        except IOError as e: err = e
    raise err

@timed_cache(seconds=3600)
def read_gh_repo(path_or_url:str,  # GitHub URL, SSH address, or local path
                 globs:tuple=None,  # file glob patterns (default: README*, pyproject.toml, *.py)
                 limit:int=None,    # max files to return
                 as_list:bool=False # return list of Paths instead of {path: content} dict
                )-> dict:
    'Read files from a GitHub repo filtered by glob patterns'
    rs = _gh_remotes(path_or_url)
    repo_dir = _get_git_repo(rs) if rs else Path(path_or_url)
    if globs is None: globs = ('README*', 'pyproject.toml', '*.py')
    files = L(p for g in globs for p in globtastic(repo_dir, file_glob=g, func=Path)).unique()
    if limit: files = files[:limit]
    if as_list: return files
    return {str(p): p.read_text(errors='ignore') for p in files}

def read_gh_file(url:str # GitHub blob URL of the file to read
                 ):
	'Read raw contents of a file from its GitHub URL'
	raw_url = re.sub(r'https://github\.com/([^/]+)/([^/]+)/blob/([^/]+)/(.+)',
	                 r'https://raw.githubusercontent.com/\1/\2/refs/heads/\3/\4', url)
	if (r:=http_get(raw_url)).status != 200: raise Exception(f"Failed to fetch {raw_url}: {r.status}")
	if 'html' not in (r.headers.get('content-type') or ''): return r.body.decode(r.encoding or 'utf-8', 'replace')
	return to_md(r)

# %% ../nbs/00_core.ipynb #38ab5369106489f5
def compile_pattern(pattern):
	"Compile pattern as regex; if invalid (e.g. bare glob like *foo*), convert via fnmatch first"
	try: return re.compile(pattern)
	except re.error:
		import fnmatch
		return re.compile(fnmatch.translate(pattern))

def find_xhr(url:str,             # URL to visit with browser
             pattern:str='*',     # Glob or regex pattern to filter captured XHR URLs
             session:bool=False,  # Use the persistent debug Chrome (authenticated) instead of a throwaway browser
             port:int=9223,       # debug Chrome port (only when session=True)
             tail:int=3,          # seconds to keep listening after navigation (only when session=True)
             **kw,                # Extra kwargs passed to fetch (verify, network_idle, etc.)
            ) -> list:
    "Visit `url`, return [{url, content_type, data, capture}] for each XHR/fetch call made. `capture` replays via `replay_xhr`."
    rx = compile_pattern(pattern)
    if session:
        from fossick.cdp import cdp_connect, syncy
        async def _run():
            cdp = await cdp_connect(port=port)
            return await cdp.calls(url=url, pattern=pattern, tail=tail)
        out = []
        for r in syncy(_run()).values():
            rb = r.get('response_body')
            if isinstance(rb, dict):
                rb = base64.b64decode(rb.get('body','')).decode(errors='replace') if rb.get('base64Encoded') else rb.get('body','')
            try: d = json.loads(rb) if rb else None
            except Exception: d = rb
            ct = {k.lower(): v for k, v in (r.get('headers') or {}).items()}.get('content-type', '')
            out.append(AttrDict(url=r['url'], content_type=ct, data=d, capture=r))
        return out
    kw.setdefault('network_idle', True)
    xhr = fetch(url, capture_xhr=True, **kw).xhr
    return [x for x in xhr if rx.search(x.url)]

def replay_xhr(capture:dict,        # a request dict from cdp.calls() or find_xhr(session=True)[i].capture
               data=None,           # override request body (str/dict); defaults to the captured body
               port:int=9223,       # debug Chrome port to pull cookies from
               use_cookies:bool=True, # attach the browser's cookies for this domain (keeps auth)
               **kw,                # Extra kwargs passed to the underlying Fetcher (headers, params, verify)
              ) -> Response:
    "Replay a browser-captured request as a fast plain-HTTP call, authenticated via the debug Chrome's cookies."
    url = capture['url']
    method = (capture.get('method') or 'GET').upper()
    headers = {k: v for k, v in (capture.get('headers') or {}).items()
               if k.lower() not in ('content-length', 'host', 'connection', 'accept-encoding', 'cookie')}
    if use_cookies:
        from fossick.cdp import cdp_cookies
        if (ck := cdp_cookies(url, port=port, as_dict=True)): kw.setdefault('cookies', ck)
    kw.setdefault('headers', headers)
    kw.setdefault('verify', False)
    body = data if data is not None else capture.get('postData')
    F = _fetcher()
    if method == 'GET': return F.get(url, **kw)
    if isinstance(body, str):
        try: body = json.loads(body)
        except: return F.post(url, data=body, **kw)
    return F.post(url, json=body, **kw)

# %% ../nbs/00_core.ipynb #338919730d042a3c
def paginate_api(url:str,                      # API endpoint URL
                 payload:dict=None,            # Request body (POST) or params (GET)
                 page_field:str='pageNumber',  # Payload key to increment for each page
                 size_field:str='pageSize',    # Payload key for page size (detects last page)
                 results_field:str=None,       # Response key with items list (auto-detect if None)
                 method:str='POST',            # HTTP method
                 max_pages:int=10,
                 page_size=24,                 # Page size to request (only used if not in payload)
                 page_start:int=1,             # Starting page number (default 1)
                 save:bool=False,              # If True, saves each page's items to disk
                 save_file:str='{url}_page_{page}.json', # Filepath pattern for saving (only used if save=True)
                 force:bool=False,             # If True, forces re-fetching even if saved file exists
                 **kw,                         # Extra kwargs passed to fetch() (verify, headers, etc.)
                ) -> list:
    "Paginate through a JSON API, collecting all results. Auto-detects the items list in response."
    payload = dict(payload or {})
    page_size = payload.get(size_field, page_size)
    all_items = []
    for page_num in range(page_start, max_pages + page_start):
        sf = save_file.format(url=urlparse(url).netloc, page=page_num)
        if not force and Path(sf).exists():
            print(f"Page {page_num} already saved, skipping fetch")
            with open(sf) as f: all_items.extend(json.load(f)); continue
        if (pg:= fetch(url, method=method, payload={**payload, page_field: page_num}, **kw)).status != 200: break
        try: data = pg.json()
        except: break
        if isinstance(data, list): items = data
        elif results_field:
            raw = data.get(results_field, [])
            items = list(raw.values()) if isinstance(raw, dict) else raw
        else:
            lists = {k: v for k, v in data.items() if isinstance(v, list)}
            items = max(lists.values(), key=len) if lists else []
        if not items: break
        all_items.extend(items)
        if len(items) < page_size: break
        if save: Path(sf).write_text(json.dumps(items, indent=2))
    return all_items

# %% ../nbs/00_core.ipynb #c430c05b6017e310
def download_files(url:str,
                   pattern:str='*',          # Glob or regex to match download hrefs
                   save_dir:str='.',         # Directory to save files
                   follow:bool=False,        # Crawl linked pages looking for more files
                   follow_sel:str='a[href]', # Selector for page links to follow when crawling
                   file_sel:str='a[href]',   # Selector to scan for download links on each page
                   same_domain:bool=True,
                   max_pages:int=10,
                   delay:float=0,
                   force:bool=False,         # Re-download even if file already exists
                   heavy:bool=False,
                   stealthy:bool=False,
                   **kw,                     # Extra kwargs passed to fetch/http_get (e.g. verify)
                  ) -> list[Path]:
    "Download all hrefs matching pattern from url; optionally crawl linked pages first"
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    rx = compile_pattern(pattern)
    pages = (crawl(url, follow_sel=follow_sel, same_domain=same_domain, max_pages=max_pages, delay=delay,
       heavy=heavy, stealthy=stealthy, **kw) if follow else [fetch(url, heavy=heavy, stealthy=stealthy, **kw)])
    saved, seen = [], set()
    for pg in pages:
        for a in pg.css(file_sel):
            href = a.attrib.get('href', '')
            if not rx.search(href): continue
            abs_url = pg.urljoin(href)
            if abs_url in seen: continue
            seen.add(abs_url)
            fname = save_dir / abs_url.rsplit('/', 1)[-1].split('?')[0]
            if fname.exists() and not force: saved.append(fname); continue
            if (r:=get_page(abs_url, verify=kw.get('verify', False))).status == 200: fname.write_bytes(r.body)
            saved.append(fname)
    return saved

# %% ../nbs/00_core.ipynb #7976427343ad1143
@cache
def _ytdl():
    "Import yt_dlp on first use. Eager import cost 0.16s of fossick's 0.35s import for 3 functions."
    import yt_dlp
    return yt_dlp

@cache
def _yt_index():
    "Disk cache for `read_yt`, opened on first use rather than at import."
    from diskcache import Index
    return Index(str(fossick_cache('yt_cache.db')))

def _yt_id(url:str) -> str:
    "Extract 11-char video ID from any YouTube URL or pass through bare ID"
    if m := re.search(r'(?:v=|youtu\.be/|/shorts/|/embed/)([A-Za-z0-9_-]{11})(?![A-Za-z0-9_-])', url): return m.group(1)
    return url

def _parse_vtt(vtt:str) -> str:
    "Strip VTT timing lines and cue tags, deduplicate adjacent lines, return plain text"
    lines = []
    for line in vtt.splitlines():
        if (re.match(r'^\d{2}:\d{2}', line) or '-->' in line
                or re.match(r'^(WEBVTT|Kind:|Language:|NOTE)', line)
                or not line.strip()): continue
        text = re.sub(r'<[^>]+>', '', line).strip()
        if text and (not lines or lines[-1] != text): lines.append(text)
    return ' '.join(lines)

# %% ../nbs/00_core.ipynb #1be381421eca318f
def search_yt(q:str, # search query
              n:int=10 # number of results to return
) -> list:
    "Search YouTube; returns L of dicts: id, title, url, duration, view_count, channel, description, thumbnail"
    try:
        with _ytdl().YoutubeDL({'quiet': True, 'extract_flat': True}) as ydl:
            return ydl.extract_info(f'ytsearch{n}:{q}', download=False).get('entries',[])
    except Exception as e:
        print(f'search_yt error: {e}')
        return []

# %% ../nbs/00_core.ipynb #449cd78d676e612f
def read_yt(url:str, # YouTube URL or video ID
            force:bool=False # if True, forces re-fetching even if cached
) -> dict:
    'Fetch YouTube metadata + English transcript (auto-captions); result disk-cached by video ID'
    vid, cache = _yt_id(url), _yt_index()
    if not force and vid in cache: return cache[vid]
    with _ytdl().YoutubeDL({'quiet': True, 'skip_download': True}) as ydl:
        info = ydl.extract_info(f'https://www.youtube.com/watch?v={vid}', download=False)
    caps = info.get('automatic_captions', {})
    en_caps = caps.get('en') or caps.get('en-orig') or []
    vtt_url = next((c['url'] for c in en_caps if c.get('ext') == 'vtt'), None)
    source = ''
    if vtt_url:
        r = http_get(vtt_url)
        # `.status` not `.status_code`, and `.body` not `.text`: a Response parses its body as HTML,
        # so `.text` on a text/vtt payload is empty. Decode the raw bytes instead.
        if r.status == 200: source = _parse_vtt(r.body.decode(errors='replace'))
    res = dict(title=info.get('title', ''),
               channel=info.get('channel') or info.get('uploader', ''),
               description=info.get('description', ''),
               duration=info.get('duration'),
               upload_date=info.get('upload_date'),
               source=source)
    cache[vid] = res
    return res

# %% ../nbs/00_core.ipynb #8e8fd7de49827232
def download_yt(url:str, # YouTube URL or video ID
                format:str='audio', # 'audio'|'video'|yt-dlp format string
                save_dir:str='.', # directory to save file
                quality:str=None # preferred audio quality (e.g. '192' for 192kbps, only used if format='audio')
) -> Path:
    'Download YouTube media; format=\'audio\'|\'video\'|yt-dlp format string. Returns Path to saved file.'
    save_dir = Path(save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    outtmpl = str(save_dir / '%(title)s.%(ext)s')
    if format == 'audio':
        opts = {'quiet': True, 'format': 'bestaudio/best', 'outtmpl': outtmpl,
                'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3',
                                    'preferredquality': quality or '192'}]}
    elif format == 'video':
        opts = {'quiet': True, 'format': 'bestvideo+bestaudio/best', 'outtmpl': outtmpl,
                'merge_output_format': 'mp4'}
    else:
        opts = {'quiet': True, 'format': format, 'outtmpl': outtmpl}
    with _ytdl().YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=True)
        stem = Path(ydl.prepare_filename(info)).stem
    ext = 'mp3' if format == 'audio' else ('mp4' if format == 'video' else '*')
    candidates = sorted(save_dir.glob(f'{stem}*.{ext}'))
    return candidates[0] if candidates else save_dir / f'{stem}.{ext}'

# %% ../nbs/00_core.ipynb #a23a6173
def repo_root() -> Path:
    'Find the root of the current git repository, or None if not in a repo.'
    return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def mv_skill_md(dry_run=True, dir=None) -> None:
    'Copy bundled SKILL.md to skill directories.'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    if not (src := base.joinpath('SKILL.md')).exists(): return
    root = dir or repo_root() or '.'
    ts = [Path(root)/'.agents/skills/fossick/SKILL.md', Path('.claude/skills/fossick/SKILL.md')]
    if dry_run: print(f'Would copy {src} to: {list(map(str,ts))}')
    else:
        [p.mk_write(src.read_text(encoding='utf-8')) for p in ts]
        print(f'Installed → {list(map(str,ts))}')
