"""what to ask, and which sources are worth reading

Docs: https://vedicreader.github.io/fossick/quality.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_quality.ipynb.

# %% auto #0
__all__ = ['MULTI_LABEL_SUFFIXES', 'DOMAIN_RULES', 'INTENT_CUES', 'SPAM_MIRRORS', 'LEAD_INS', 'FILLER', 'host',
           'registrable_domain', 'norm_url', 'domain_matches', 'blocked_matches', 'classify', 'site_domains',
           'drop_spam', 'facets', 'plan', 'interleave', 'authority_rerank', 'cap_per_domain', 'shingles', 'jaccard',
           'cluster_sources', 'independence', 'snippet_similarity', 'diversity', 'curate']

# %% ../nbs/06_quality.ipynb #b57cdbf4
import math, re
from collections import Counter
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from fastcore.all import ifnone


# %% ../nbs/06_quality.ipynb #0170b1df
#: Three-label registry suffixes (`bbc.co.uk`, not `co.uk`). Approximate PSL for countries we care about.
MULTI_LABEL_SUFFIXES = frozenset({
    'ac.at', 'co.at', 'gv.at', 'or.at', 'priv.at',
    'com.au', 'net.au', 'org.au', 'edu.au', 'gov.au', 'asn.au', 'id.au',
    'com.br', 'com.cn', 'edu.cn', 'gov.cn', 'net.cn', 'org.cn',
    'com.hk', 'edu.hk', 'gov.hk', 'org.hk',
    'co.in', 'edu.in', 'firm.in', 'gen.in', 'gov.in', 'ind.in', 'net.in', 'org.in',
    'ac.jp', 'co.jp', 'ed.jp', 'go.jp', 'ne.jp', 'or.jp',
    'com.mx', 'com.my', 'edu.my',
    'ac.nz', 'co.nz', 'net.nz', 'org.nz', 'govt.nz',
    'com.sg', 'edu.sg', 'gov.sg',
    'com.tr', 'com.ua',
    'ac.uk', 'co.uk', 'gov.uk', 'ltd.uk', 'me.uk', 'net.uk', 'org.uk', 'plc.uk', 'sch.uk',
    'co.za', 'org.za', 'gov.za',
})

def host(url:str) -> str:
    "The lowercase hostname of `url`, without `www.` or a trailing dot. `''` when there isn't one."
    try: h = urlsplit(url if '//' in ifnone(url,'') else f'//{ifnone(url,"")}').hostname or ''
    except ValueError: return ''
    h = h.strip().rstrip('.').lower()
    return h[4:] if h.startswith('www.') else h

def registrable_domain(url:str) -> str:
    "Site behind `url` (`docs.python.org`→`python.org`, `bbc.co.uk`→`bbc.co.uk`). IP/single-label unchanged."
    h = host(url)
    if not h or re.fullmatch(r'[\d.]+|\[[0-9a-f:]+\]', h): return h
    labels = [x for x in h.split('.') if x]
    if len(labels) < 3: return '.'.join(labels)
    return '.'.join(labels[-3:] if '.'.join(labels[-2:]) in MULTI_LABEL_SUFFIXES else labels[-2:])


# %% ../nbs/06_quality.ipynb #3243a53b
#: Click/tracking params — drop so the same article from six shares is one key.
_TRACKING = re.compile(r'^(utm_|fbclid|gclid|dclid|msclkid|yclid|mkt_tok|mc_[ce]id|igshid|'
                       r'vero_id|oly_(anon|enc)_id|_ga$|ref$|source$)')

_DFLT_PORT = {'http': 80, 'https': 443, 'ftp': 21}

def norm_url(u:str) -> str:
    "Dedup key: no scheme/fragment/tracking/`www.`/default port/trailing slash; query sorted."
    try: s = urlsplit(u)
    except ValueError: return u
    try: port = s.port
    except ValueError: port = None
    h = (s.hostname or '').rstrip('.').lower()
    h = h[4:] if h.startswith('www.') else h
    if ':' in h: h = f'[{h}]'                                   # ipv6 literal
    if port is not None and port != _DFLT_PORT.get(s.scheme.lower()): h = f'{h}:{port}'
    qs = sorted((k, v) for k, v in parse_qsl(s.query, keep_blank_values=True) if not _TRACKING.match(k))
    return urlunsplit(('', h, s.path.rstrip('/') or '/', urlencode(qs), ''))


# %% ../nbs/06_quality.ipynb #04f248d1
#: Boost/demote domains per intent — authority is not global.
DOMAIN_RULES = {
    'docs': dict(
        boost=('docs.', 'developer.', 'devdocs.', 'api.', 'github.com', 'readthedocs.io',
               'readthedocs.org', 'rust-lang.org', 'python.org', 'mozilla.org', 'w3.org',
               'ietf.org', 'rfc-editor.org'),
        demote=('medium.com', 'dev.to', 'reddit.com', 'stackoverflow.com', 'youtube.com',
                'geeksforgeeks.org', 'w3schools.com', 'tutorialspoint.com'),
    ),
    'policy': dict(
        boost=('.gov', '.gov.au', '.gov.uk', '.govt.nz', '.gov.in', '.gov.sg', '.gov.za',
               '.gc.ca', '.europa.eu', '.int', '.mil', '.edu', '.ac.uk', '.edu.au',
               'legislation.gov.uk', 'abcb.gov.au', 'standards.org.au', 'standards.org',
               'iso.org', 'nist.gov', 'oecd.org', 'who.int', 'eur-lex.europa.eu'),
        demote=('scribd.com', 'researchgate.net', 'slideshare.net', 'academia.edu', 'medium.com',
                'youtube.com', 'quora.com', 'pinterest.com', 'hipages.com.au', 'oneflare.com.au',
                'airtasker.com', 'serviceseeking.com.au', 'checkatrade.com', 'houzz.com',
                'angi.com', 'thumbtack.com'),
    ),
    'release': dict(
        boost=('github.com', 'blog.', 'news.', 'anthropic.com', 'openai.com', 'blog.google',
               'ai.google.dev', 'ai.meta.com', 'nvidia.com', 'microsoft.com', 'apple.com',
               'mistral.ai', 'tailscale.com'),
        demote=('youtube.com', 'medium.com', 'reddit.com', 'linkedin.com', 'facebook.com'),
    ),
    'security': dict(
        boost=('nvd.nist.gov', 'cve.org', 'cve.mitre.org', 'github.com/advisories', 'security.',
               'cert.', 'kb.cert.org', 'openwall.com', '.gov'),
        demote=('youtube.com', 'medium.com', 'reddit.com', 'linkedin.com'),
    ),
    'community': dict(
        boost=('reddit.com', 'news.ycombinator.com', 'stackexchange.com', 'stackoverflow.com',
               'forum.', 'forums.', 'community.', 'discourse.'),
        demote=('pinterest.com', 'quora.com', 'answers.com'),
    ),
}

def domain_matches(domain:str, rule:str) -> bool:
    "Match `docs.` (label), `.gov.au` (suffix), or exact/subdomain — never bare startswith."
    if not domain or not rule: return False
    if rule.endswith('.'): return domain.startswith(rule)
    # `.gov.uk` has to match the registry itself as well as everything under it, or the rule
    # covers every UK government department except gov.uk.
    if rule.startswith('.'): return domain == rule[1:] or domain.endswith(rule)
    if '/' in rule: return domain == rule.split('/', 1)[0]
    return domain == rule or domain.endswith(f'.{rule}')

def blocked_matches(domain:str, rule:str) -> bool:
    "True if host is in the blocked list (exact or subdomain)."
    return bool(domain) and (domain == rule or domain.endswith(f'.{rule}'))


# %% ../nbs/06_quality.ipynb #3e1b3546
#: Cue words per intent class. Matched on word boundaries against the lowercased query.
INTENT_CUES = {
    'docs':      ('docs', 'documentation', 'api reference', 'reference manual', 'man page',
                  'how do i use', 'syntax', 'parameters', 'sdk', 'changelog api'),
    'policy':    ('regulation', 'regulations', 'regulatory', 'compliance', 'legislation', 'statute',
                  'law', 'laws', 'legal', 'permit', 'permits', 'planning permission', 'building code',
                  'building codes', 'building regulations', 'standard', 'standards', 'certification',
                  'licence', 'license required', 'zoning', 'council approval', 'tax rules'),
    'release':   ('release notes', 'changelog', 'release date', 'latest version', 'new version',
                  'announced', 'announcement', 'ships with', 'now available', 'launch'),
    'security':  ('cve', 'vulnerability', 'vulnerabilities', 'advisory', 'exploit', 'patch',
                  'security fix', 'zero day', 'rce'),
    'community': ('reddit', 'forum', 'hacker news', 'opinions', 'experiences', 'anyone else',
                  'worth it', 'real world', 'in practice', 'complaints', 'reviews from'),
}

_cue_rx = None
def _cue_pats():
    "One compiled pattern per class, built once."
    global _cue_rx
    if _cue_rx is None:
        _cue_rx = {k: re.compile('|'.join(rf'(?<![a-z0-9]){re.escape(c)}(?![a-z0-9])' for c in cues))
                   for k, cues in INTENT_CUES.items()}
    return _cue_rx

def classify(q:str) -> str:
    "Intent class from cue table, or None when cues disagree/tie."
    ql = (q or '').lower()
    hits = {k: len(rx.findall(ql)) for k, rx in _cue_pats().items()}
    hits = {k: n for k, n in hits.items() if n}
    if not hits: return None
    top = max(hits.values())
    winners = [k for k, n in hits.items() if n == top]
    return winners[0] if len(winners) == 1 else None


# %% ../nbs/06_quality.ipynb #c3423b47
#: Sites that republish other people's answers. Removed rather than demoted: they add nothing over the
#: original, and fused metasearch actively promotes them — being optimised for every engine at once is
#: what they are for, and RRF reads that as consensus.
SPAM_MIRRORS = (
    # Stack Overflow / Q&A scrapers
    'newbedev.com', 'stackoom.com', 'stackovergo.com', 'syntaxfix.com', 'copyprogramming.com',
    'devcodef1.com', 'exceptionshub.com', 'code-examples.net', 'i-harness.com',
    'fixmycodeerror.com', 'stacklesson.com', 'itecnote.com', 'codeprozone.com',
    # GitHub issue / readme mirrors
    'githubmemory.com', 'gitmemory.com', 'issueexplorer.com', 'bleepcoder.com', 'gitanswer.com',
    # Documentation mirrors
    'w3cub.com', 'devdoc.net',
)

_SITE_OP = re.compile(r'\bsite:([a-z0-9][a-z0-9.-]*)', re.I)

def site_domains(q:str, include=()) -> list:
    "Domains from `site:` ops in `q` plus any explicit `include` list."
    ds = [d.lower().rstrip('.') for d in _SITE_OP.findall(q or '')]
    ds += [str(d).strip().lower() for d in (include or []) if str(d).strip()]
    return sorted(set(ds))

def _url(h) -> str: return h.get('href') or h.get('url') or '' if isinstance(h, dict) else str(h)

def drop_spam(hits:list, blocked=(), allowed=()) -> tuple:
    "Remove hits from mirror domains. Returns `(kept, removed_domains)`; `allowed` rescues a domain."
    rules = tuple(SPAM_MIRRORS) + tuple(str(d).strip().lower() for d in blocked if str(d).strip())
    ok = tuple(str(d).strip().lower() for d in allowed if str(d).strip())
    kept, removed = [], []
    for h in hits:
        d = host(_url(h))
        if d and not any(blocked_matches(d, r) for r in ok) and any(blocked_matches(d, r) for r in rules):
            removed.append(d); continue
        kept.append(h)
    return kept, sorted(set(removed))


# %% ../nbs/06_quality.ipynb #8d2f9b2d
#: Conversational lead-ins stripped before splitting.
LEAD_INS = (r"i (?:want|need|would like|wanna|have) to", r"i(?:'m| am) (?:looking|trying) to",
            r"can you (?:tell me|help me|find|look up)", r"(?:please )?(?:tell me|help me|find me)",
            r"how (?:do|can|would) i", r"what (?:do|should) i", r"i (?:want|need)",
            r"give me", r"looking for")

#: Filler phrases with no search signal.
FILLER = (r"what (?:is|are|was|were) (?:the |a |an )?", r"things to consider(?: are)?",
          r"i (?:want|need) to know", r"(?:on|about|for|with) (?:it|this|that|them|these)",
          r"tell me", r"please", r"kindly", r"etc\.?", r"and so on", r"as well", r"also",
          r"in general", r"or not")

#: Words that carry no topic. Kept small on purpose: a stopword list that eats domain terms is worse
#: than none at all.
_STOP = frozenset("""a an the and or but of in on at to for from by with without into over under
    my your our their its his her this that these those it they i we you is are was were be been
    am do does did have has had can could should would will shall may might must not no if then
    than as so such about very more most much many some any all each every other another""".split())

_LEAD_RX = re.compile(r'^\s*(?:' + '|'.join(LEAD_INS) + r')\s+', re.I)
_FILL_RX = re.compile(r'\b(?:' + '|'.join(FILLER) + r')\b', re.I)
_SPLIT_RX = re.compile(r'\s*(?:[,;?]|\band\b|\bplus\b|\balso\b|\bas well as\b)\s*', re.I)
_WORD_RX = re.compile(r"[^\W_]+(?:['-][^\W_]+)*", re.UNICODE)

def _content(s:str) -> list:
    "The words in `s` that carry topic, in order, deduped."
    out, seen = [], set()
    for w in _WORD_RX.findall(_FILL_RX.sub(' ', s or '').lower()):
        if w in _STOP or w in seen: continue
        seen.add(w); out.append(w)
    return out

def facets(q:str) -> list:
    "The clauses of `q` as content-word lists, lead-in stripped. `[]` when there is nothing to split."
    parts = [p for p in _SPLIT_RX.split(_LEAD_RX.sub('', q or '').strip()) if p.strip()]
    return [c for p in parts if (c := _content(p))] if len(parts) > 1 else []

def plan(q:str,                  # the question as asked
         max_queries:int=4,      # total searches including the original; 1 disables planning
         min_words:int=6,        # below this a query has no room for two questions
         rewrite=None,           # optional `f(q) -> list[str]`, e.g. a model. Overrides the heuristic.
        ) -> list:
    "Split multi-part `q` into searches; always `[q]` first. Abstains when no second question."
    q = (q or '').strip()
    if not q: return []
    if rewrite is not None:
        extra = [str(s).strip() for s in (rewrite(q) or []) if str(s).strip()]
        return _dedup([q, *extra])[:max(1, max_queries)]
    if max_queries < 2 or len(q.split()) < min_words or site_domains(q): return [q]
    cs = facets(q)
    if len(cs) < 2: return [q]
    topic, out = cs[0], [q]
    for c in cs[1:]:
        if set(c) <= set(topic): continue                  # says nothing the subject did not
        out.append(' '.join(topic + [w for w in c if w not in topic]))
    return _dedup(out)[:max_queries]

def _dedup(qs:list) -> list:
    out, seen = [], set()
    for s in qs:
        if (k := ' '.join(s.lower().split())) not in seen: seen.add(k); out.append(s)
    return out

def interleave(lists:list, key=None) -> list:
    "Round-robin merge of result lists; dedup by `key` (default norm_url)."
    key = key or (lambda h: norm_url(h.get('href') or h.get('url') or ''))
    out, seen = [], {}
    for row in zip(*(list(l) + [None] * (max(map(len, lists), default=0) - len(l)) for l in lists)) \
            if lists else []:
        for h in row:
            if h is None: continue
            k = key(h)
            if k in seen: seen[k].setdefault('queries', []).extend(
                x for x in (h.get('queries') or []) if x not in seen[k].get('queries', []))
            else:
                seen[k] = dict(h); out.append(seen[k])
    return out


# %% ../nbs/06_quality.ipynb #884e65fc
def authority_rerank(hits:list, cls:str) -> tuple:
    "Stable boost/demote by DOMAIN_RULES for `cls`; lossless."
    rules = DOMAIN_RULES.get(cls or '')
    if not hits or not rules:
        return hits, dict(intent=cls, applied=False, boosted=[], demoted=[])
    boosted, demoted, scored = [], [], []
    for i, h in enumerate(hits):
        d = host(_url(h))
        s = (len(hits) - i) * 0.01                       # keep the incoming order as the tiebreak
        if any(domain_matches(d, r) for r in rules['boost']):  s += 10.0; boosted.append(d)
        if any(domain_matches(d, r) for r in rules['demote']): s -= 6.0;  demoted.append(d)
        scored.append((s, i, h))
    out = [h for _, _, h in sorted(scored, key=lambda t: (-t[0], t[1]))]
    return out, dict(intent=cls, applied=[_url(h) for h in out] != [_url(h) for h in hits],
                     boosted=sorted(set(boosted)), demoted=sorted(set(demoted)),
                     top_before=host(_url(hits[0])), top_after=host(_url(out[0])))

def cap_per_domain(hits:list, max_per:int=2) -> tuple:
    "Stable per-domain soft cap: overflow keeps relative order in the tail."
    if max_per < 1 or len(hits) < 3: return hits, 0
    head, tail, seen = [], [], Counter()
    for h in hits:
        d = registrable_domain(_url(h))
        if d and seen[d] >= max_per: tail.append(h); continue
        seen[d] += 1; head.append(h)
    return head + tail, len(tail)


# %% ../nbs/06_quality.ipynb #b9ff2545
def shingles(text:str, n:int=3) -> set:
    "Word n-grams of `text`. Fewer than `n` words has no evidence and yields nothing, never a match."
    w = _WORD.findall((text or '').casefold())
    return {tuple(w[i:i+n]) for i in range(len(w) - n + 1)} if len(w) >= n else set()

def jaccard(a:set, b:set) -> float:
    "|a ∩ b| / |a ∪ b|, and 0.0 when either side is empty — absence of evidence is not similarity."
    return len(a & b) / len(a | b) if a and b else 0.0

def _union_find(n:int):
    "Iterative find with path compression: a result page is small, but recursion here buys nothing."
    parent = list(range(n))
    def find(i):
        root = i
        while parent[root] != root: root = parent[root]
        while parent[i] != root: parent[i], i = root, parent[i]
        return root
    def union(i, j):
        ri, rj = find(i), find(j)
        if ri != rj: parent[max(ri, rj)] = min(ri, rj)      # keep the earliest index as the root
    return find, union

def cluster_sources(hits:list,             # search hits or research sources
                    threshold:float=0.6,   # trigram Jaccard above which two texts are one story
                   ) -> list:
    "Union-find clusters by canonical URL + Jaccard≥threshold; representative is first in input order."
    return _analyse(hits, threshold)[0]

def _analyse(hits:list, threshold:float) -> tuple:
    "Union-find by canonical URL + Jaccard≥threshold; first member is representative."
    hits = [h for h in hits if isinstance(h, dict)]
    n = len(hits)
    if not n: return [], 0
    find, union = _union_find(n)
    keys = [norm_url(_url(h)) for h in hits]
    sigs = [shingles(_text(h)) for h in hits]
    near = 0
    for i in range(n):
        for j in range(i):
            same = bool(keys[i]) and keys[i] == keys[j]
            alike = jaccard(sigs[i], sigs[j]) >= threshold
            near += alike
            if same or alike: union(i, j)
    groups = {}
    for i in range(n): groups.setdefault(find(i), []).append(i)
    clusters = [dict(canonical=_url(hits[g[0]]), title=hits[g[0]].get('title') or '',
                     members=[_url(hits[i]) for i in g], size=len(g),
                     domains=sorted({d for i in g if (d := registrable_domain(_url(hits[i])))}))
                for g in (groups[k] for k in sorted(groups))]
    return clusters, near

def independence(hits:list, threshold:float=0.6) -> dict:
    "Cluster count / n — fraction of independent stories."
    hits = [h for h in hits if isinstance(h, dict)]
    n = len(hits)
    if not n:
        return dict(n=0, sources=0, score=0.0, clusters=[], method='none', confidence='low',
                    limitations=[])
    cl = _analyse(hits, threshold)[0]
    textual = sum(1 for h in hits if shingles(_text(h))) >= 2
    fams = {d for c in cl for d in c['domains']}
    return dict(
        n=n, sources=len(cl), clusters=cl,
        score=round(0.7 * len(cl) / n + 0.3 * (len(fams) / n if fams else 0.0), 4),
        method='url+text' if textual else 'url',
        confidence='medium' if textual and n > 1 else 'low',
        limitations=['two sites reporting one press release in their own words are not detectable '
                     'by text overlap'] + ([] if textual else
                     ['too little text to compare: only identical urls were clustered']))


# %% ../nbs/06_quality.ipynb #cd5f778f
_WORD = re.compile(r'[^\W_]+', re.UNICODE)

def _trigrams(text:str) -> set:
    w = _WORD.findall((text or '').casefold())
    return {tuple(w[i:i+3]) for i in range(len(w) - 2)} if len(w) >= 3 else set()

def snippet_similarity(a:str, b:str) -> float:
    "Jaccard over word trigrams. Text shorter than three words scores 0 — no evidence, not a match."
    x, y = _trigrams(a), _trigrams(b)
    return len(x & y) / len(x | y) if x and y else 0.0

def _text(h) -> str:
    if not isinstance(h, dict): return ''
    return ' '.join(str(h.get(k) or '') for k in ('title', 'body', 'content', 'snippet', 'md'))

def diversity(hits:list, threshold:float=0.6) -> dict:
    "Describe dominant domain, near-dups, and independent source count."
    hits = [h for h in hits if isinstance(h, dict)]
    n = len(hits)
    if not n: return dict(score=0.0, n=0, domains=0, dominant_domain=None, dup_urls=0,
                          near_dups=0, sources=0)
    doms = Counter(d for d in (registrable_domain(_url(h)) for h in hits) if d)
    seen, dup_urls = set(), 0
    for h in hits:
        k = norm_url(_url(h))
        if k in seen: dup_urls += 1
        elif k: seen.add(k)
    clusters, near = _analyse(hits, threshold)
    pairs = n * (n - 1) // 2
    dom_div, url_uniq = (len(doms) / n), 1.0 - dup_urls / n
    content = 1.0 if not pairs else 1.0 - near / pairs
    top = doms.most_common(1)[0] if doms else None
    return dict(score=round(0.5*dom_div + 0.3*max(0., url_uniq) + 0.2*max(0., content), 4),
                n=n, domains=len(doms), dup_urls=dup_urls, near_dups=near,
                sources=len(clusters),
                dominant_domain=dict(domain=top[0], share=round(top[1]/n, 4)) if top else None)


# %% ../nbs/06_quality.ipynb #2026423d
def curate(q:str,                  # the query, read for intent and `site:` constraints
           hits:list,              # search hits (dicts with `href`/`url`, `title`, `body`)
           intent:str='auto',      # an intent class, 'auto' to classify, or None to skip authority
           max_per_domain:int=2,   # per-registrable-domain cap; 0 disables
           blocked=(), allowed=(), # extra mirror domains, and rescues from the built-in list
           rerank:bool=True,       # False: describe only, return `hits` untouched
          ) -> tuple:
    "Filter/rerank/describe hits → `(hits, report)`. `site:` skips spam drop and domain cap."
    sites = site_domains(q)
    rep = dict(intent=None, site_constrained=sites, dropped=[], demoted=0, authority=None)
    if not hits:
        return hits, dict(rep, diversity=diversity([]))
    out = hits
    if rerank:
        if not sites:
            out, rep['dropped'] = drop_spam(out, blocked=blocked, allowed=allowed)
        cls = classify(q) if intent == 'auto' else intent
        out, rep['authority'] = authority_rerank(out, cls)
        rep['intent'] = cls
        if max_per_domain and not sites:
            out, rep['demoted'] = cap_per_domain(out, max_per_domain)
    else:
        rep['intent'] = classify(q) if intent == 'auto' else intent
    rep['diversity'] = diversity(out)
    return out, rep

