"""which sources are worth reading: registrable domains, authority by intent, spam mirrors, and result-set diversity

Docs: https://vedicreader.github.io/fossick/quality.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_quality.ipynb.

# %% auto #0
__all__ = ['MULTI_LABEL_SUFFIXES', 'DOMAIN_RULES', 'INTENT_CUES', 'SPAM_MIRRORS', 'host', 'registrable_domain', 'norm_url',
           'domain_matches', 'blocked_matches', 'classify', 'site_domains', 'drop_spam', 'authority_rerank',
           'cap_per_domain', 'snippet_similarity', 'diversity', 'curate']

# %% ../nbs/06_quality.ipynb #b57cdbf4
import math, re
from collections import Counter
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

# %% ../nbs/06_quality.ipynb #0170b1df
#: Registry suffixes that take three labels rather than two, so `bbc.co.uk` does not collapse to
#: `co.uk` and put every British site under one roof. An approximation of the public suffix list,
#: deliberately: the real one is ~10k entries and a moving target.
MULTI_LABEL_SUFFIXES = frozenset({
    'ac.at', 'co.at', 'gv.at', 'or.at', 'priv.at',
    'com.au', 'net.au', 'org.au', 'edu.au', 'gov.au', 'asn.au', 'id.au',
    'com.br', 'com.cn', 'edu.cn', 'gov.cn', 'net.cn', 'org.cn',
    'com.hk', 'edu.hk', 'gov.hk', 'org.hk',
    'co.in', 'edu.in', 'firm.in', 'gen.in', 'gov.in', 'ind.in', 'net.in', 'org.in',
    'ac.jp', 'co.jp', 'ed.jp', 'go.jp', 'ne.jp', 'or.jp',
    'com.mx', 'com.my', 'edu.my',
    'ac.nz', 'co.nz', 'net.nz', 'org.nz', 'govt.nz',
    'com.sg', 'edu.sg', 'gov.sg',
    'com.tr', 'com.ua',
    'ac.uk', 'co.uk', 'gov.uk', 'ltd.uk', 'me.uk', 'net.uk', 'org.uk', 'plc.uk', 'sch.uk',
    'co.za', 'org.za', 'gov.za',
})

def host(url:str) -> str:
    "The lowercase hostname of `url`, without `www.` or a trailing dot. `''` when there isn't one."
    try: h = urlsplit(url if '//' in (url or '') else f'//{url or ""}').hostname or ''
    except ValueError: return ''
    h = h.strip().rstrip('.').lower()
    return h[4:] if h.startswith('www.') else h

def registrable_domain(url:str) -> str:
    """The site behind `url` — `docs.python.org` -> `python.org`, `bbc.co.uk` -> `bbc.co.uk`.

    An IP address and a single-label host are returned unchanged: there is nothing to strip, and
    guessing would merge unrelated hosts.
    """
    h = host(url)
    if not h or re.fullmatch(r'[\d.]+|\[[0-9a-f:]+\]', h): return h
    labels = [x for x in h.split('.') if x]
    if len(labels) < 3: return '.'.join(labels)
    return '.'.join(labels[-3:] if '.'.join(labels[-2:]) in MULTI_LABEL_SUFFIXES else labels[-2:])

# %% ../nbs/06_quality.ipynb #3243a53b
#: Parameters that identify a *click*, never a page. Dropping them is what makes the same article
#: shared from six places dedup to one.
_TRACKING = re.compile(r'^(utm_|fbclid|gclid|dclid|msclkid|yclid|mkt_tok|mc_[ce]id|igshid|'
                       r'vero_id|oly_(anon|enc)_id|_ga$|ref$|source$)')

_DFLT_PORT = {'http': 80, 'https': 443, 'ftp': 21}

def norm_url(u:str) -> str:
    """Canonical form for dedup: no scheme, no fragment, no tracking params, no `www.`, no default
    port, no trailing slash — and the surviving query sorted.

    The scheme goes entirely, unlike most canonicalisers: `http://x.com/a` and `https://x.com/a` are
    one page, and this string is only ever used as a key.
    """
    try: s = urlsplit(u)
    except ValueError: return u
    try: port = s.port
    except ValueError: port = None
    h = (s.hostname or '').rstrip('.').lower()
    h = h[4:] if h.startswith('www.') else h
    if ':' in h: h = f'[{h}]'                                   # ipv6 literal
    if port is not None and port != _DFLT_PORT.get(s.scheme.lower()): h = f'{h}:{port}'
    qs = sorted((k, v) for k, v in parse_qsl(s.query, keep_blank_values=True) if not _TRACKING.match(k))
    return urlunsplit(('', h, s.path.rstrip('/') or '/', urlencode(qs), ''))

# %% ../nbs/06_quality.ipynb #04f248d1
#: Boost/demote domains per intent class. Keyed by class because authority is not global: a changelog
#: beats a forum on `release`, and the reverse is true on `community`.
DOMAIN_RULES = {
    'docs': dict(
        boost=('docs.', 'developer.', 'devdocs.', 'api.', 'github.com', 'readthedocs.io',
               'readthedocs.org', 'rust-lang.org', 'python.org', 'mozilla.org', 'w3.org',
               'ietf.org', 'rfc-editor.org'),
        demote=('medium.com', 'dev.to', 'reddit.com', 'stackoverflow.com', 'youtube.com',
                'geeksforgeeks.org', 'w3schools.com', 'tutorialspoint.com'),
    ),
    'policy': dict(
        # Suffix rules do the real work here: one `.gov.au` covers every Australian agency, which a
        # list of named departments never would.
        boost=('.gov', '.gov.au', '.gov.uk', '.govt.nz', '.gov.in', '.gov.sg', '.gov.za',
               '.gc.ca', '.europa.eu', '.int', '.mil', '.edu', '.ac.uk', '.edu.au',
               'legislation.gov.uk', 'abcb.gov.au', 'standards.org.au', 'standards.org',
               'iso.org', 'nist.gov', 'oecd.org', 'who.int', 'eur-lex.europa.eu'),
        # Lead-generation marketplaces are legitimate businesses and the wrong answer to a question
        # about rules: they sell quotes, and they outrank the regulator that wrote the rule.
        demote=('scribd.com', 'researchgate.net', 'slideshare.net', 'academia.edu', 'medium.com',
                'youtube.com', 'quora.com', 'pinterest.com', 'hipages.com.au', 'oneflare.com.au',
                'airtasker.com', 'serviceseeking.com.au', 'checkatrade.com', 'houzz.com',
                'angi.com', 'thumbtack.com'),
    ),
    'release': dict(
        boost=('github.com', 'blog.', 'news.', 'anthropic.com', 'openai.com', 'blog.google',
               'ai.google.dev', 'ai.meta.com', 'nvidia.com', 'microsoft.com', 'apple.com',
               'mistral.ai', 'tailscale.com'),
        demote=('youtube.com', 'medium.com', 'reddit.com', 'linkedin.com', 'facebook.com'),
    ),
    'security': dict(
        boost=('nvd.nist.gov', 'cve.org', 'cve.mitre.org', 'github.com/advisories', 'security.',
               'cert.', 'kb.cert.org', 'openwall.com', '.gov'),
        demote=('youtube.com', 'medium.com', 'reddit.com', 'linkedin.com'),
    ),
    'community': dict(
        # Deliberately the inverse of the others: the question is what people found, not what a
        # vendor published.
        boost=('reddit.com', 'news.ycombinator.com', 'stackexchange.com', 'stackoverflow.com',
               'forum.', 'forums.', 'community.', 'discourse.'),
        demote=('pinterest.com', 'quora.com', 'answers.com'),
    ),
}

def domain_matches(domain:str, rule:str) -> bool:
    """Does `domain` match an authority `rule`?

    `docs.` matches a leading label, `.gov.au` matches a suffix, anything else matches exactly or as
    a true subdomain. Never a bare `startswith`: that would hand `openai.com.evil.example` the boost
    meant for `openai.com`.
    """
    if not domain or not rule: return False
    if rule.endswith('.'): return domain.startswith(rule)
    if rule.startswith('.'): return domain.endswith(rule)
    if '/' in rule: return domain == rule.split('/', 1)[0]
    return domain == rule or domain.endswith(f'.{rule}')

def blocked_matches(domain:str, rule:str) -> bool:
    """Strict matcher for block and allow lists: exact domain or true subdomain, nothing else.

    Separate from `domain_matches` on purpose — a blocklist must not grow a prefix or suffix clause,
    or `newbedev.com.evil.example` blocks and, worse, an allow-rule rescues far more than it names.
    """
    return bool(domain) and (domain == rule or domain.endswith(f'.{rule}'))

# %% ../nbs/06_quality.ipynb #3e1b3546
#: Cue words per intent class. Matched on word boundaries against the lowercased query.
INTENT_CUES = {
    'docs':      ('docs', 'documentation', 'api reference', 'reference manual', 'man page',
                  'how do i use', 'syntax', 'parameters', 'sdk', 'changelog api'),
    'policy':    ('regulation', 'regulations', 'regulatory', 'compliance', 'legislation', 'statute',
                  'law', 'laws', 'legal', 'permit', 'permits', 'planning permission', 'building code',
                  'building codes', 'building regulations', 'standard', 'standards', 'certification',
                  'licence', 'license required', 'zoning', 'council approval', 'tax rules'),
    'release':   ('release notes', 'changelog', 'release date', 'latest version', 'new version',
                  'announced', 'announcement', 'ships with', 'now available', 'launch'),
    'security':  ('cve', 'vulnerability', 'vulnerabilities', 'advisory', 'exploit', 'patch',
                  'security fix', 'zero day', 'rce'),
    'community': ('reddit', 'forum', 'hacker news', 'opinions', 'experiences', 'anyone else',
                  'worth it', 'real world', 'in practice', 'complaints', 'reviews from'),
}

_cue_rx = None
def _cue_pats():
    "One compiled pattern per class, built once."
    global _cue_rx
    if _cue_rx is None:
        _cue_rx = {k: re.compile('|'.join(rf'(?<![a-z0-9]){re.escape(c)}(?![a-z0-9])' for c in cues))
                   for k, cues in INTENT_CUES.items()}
    return _cue_rx

def classify(q:str) -> str:
    """The intent class a query is asking for, or `None` when it says nothing or says two things.

    Abstaining is the useful behaviour: a wrong class reranks *against* the answer, which is worse
    than not reranking. A tie is a genuine ambiguity — "reddit release notes" is both, so it is
    neither — and returns `None` rather than picking.
    """
    ql = (q or '').lower()
    hits = {k: len(rx.findall(ql)) for k, rx in _cue_pats().items()}
    hits = {k: n for k, n in hits.items() if n}
    if not hits: return None
    top = max(hits.values())
    winners = [k for k, n in hits.items() if n == top]
    return winners[0] if len(winners) == 1 else None

# %% ../nbs/06_quality.ipynb #c3423b47
#: Sites that republish other people's answers. Removed rather than demoted: they add nothing over the
#: original, and fused metasearch actively promotes them — being optimised for every engine at once is
#: what they are for, and RRF reads that as consensus.
SPAM_MIRRORS = (
    # Stack Overflow / Q&A scrapers
    'newbedev.com', 'stackoom.com', 'stackovergo.com', 'syntaxfix.com', 'copyprogramming.com',
    'devcodef1.com', 'exceptionshub.com', 'code-examples.net', 'i-harness.com',
    'fixmycodeerror.com', 'stacklesson.com', 'itecnote.com', 'codeprozone.com',
    # GitHub issue / readme mirrors
    'githubmemory.com', 'gitmemory.com', 'issueexplorer.com', 'bleepcoder.com', 'gitanswer.com',
    # Documentation mirrors
    'w3cub.com', 'devdoc.net',
)

_SITE_OP = re.compile(r'\bsite:([a-z0-9][a-z0-9.-]*)', re.I)

def site_domains(q:str, include=()) -> list:
    """Domains the caller explicitly constrained the search to — `site:` operators plus `include`.

    An explicit constraint is intent. Constrained domains are exempt from spam filtering, and their
    presence turns domain capping off: a search told to look at one site must not be reranked away
    from it.
    """
    ds = [d.lower().rstrip('.') for d in _SITE_OP.findall(q or '')]
    ds += [str(d).strip().lower() for d in (include or []) if str(d).strip()]
    return sorted(set(ds))

def _url(h) -> str: return h.get('href') or h.get('url') or '' if isinstance(h, dict) else str(h)

def drop_spam(hits:list, blocked=(), allowed=()) -> tuple:
    "Remove hits from mirror domains. Returns `(kept, removed_domains)`; `allowed` rescues a domain."
    rules = tuple(SPAM_MIRRORS) + tuple(str(d).strip().lower() for d in blocked if str(d).strip())
    ok = tuple(str(d).strip().lower() for d in allowed if str(d).strip())
    kept, removed = [], []
    for h in hits:
        d = host(_url(h))
        if d and not any(blocked_matches(d, r) for r in ok) and any(blocked_matches(d, r) for r in rules):
            removed.append(d); continue
        kept.append(h)
    return kept, sorted(set(removed))

# %% ../nbs/06_quality.ipynb #884e65fc
def authority_rerank(hits:list, cls:str) -> tuple:
    """Reorder `hits` by the `cls` rules, keeping the existing order as the tiebreak.

    Returns `(hits, report)`. `cls=None` or an unknown class is a no-op, reported as such, so a caller
    never has to check before calling.
    """
    rules = DOMAIN_RULES.get(cls or '')
    if not hits or not rules:
        return hits, dict(intent=cls, applied=False, boosted=[], demoted=[])
    boosted, demoted, scored = [], [], []
    for i, h in enumerate(hits):
        d = host(_url(h))
        s = (len(hits) - i) * 0.01                       # keep the incoming order as the tiebreak
        if any(domain_matches(d, r) for r in rules['boost']):  s += 10.0; boosted.append(d)
        if any(domain_matches(d, r) for r in rules['demote']): s -= 6.0;  demoted.append(d)
        scored.append((s, i, h))
    out = [h for _, _, h in sorted(scored, key=lambda t: (-t[0], t[1]))]
    return out, dict(intent=cls, applied=[_url(h) for h in out] != [_url(h) for h in hits],
                     boosted=sorted(set(boosted)), demoted=sorted(set(demoted)),
                     top_before=host(_url(hits[0])), top_after=host(_url(out[0])))

def cap_per_domain(hits:list, max_per:int=2) -> tuple:
    """Move a domain's overflow behind the head so one site cannot own the page.

    Returns `(hits, n_demoted)`. Nothing is dropped: the fifth page from one publisher is still
    evidence, it just should not push out the second publisher.
    """
    if max_per < 1 or len(hits) < 3: return hits, 0
    head, tail, seen = [], [], Counter()
    for h in hits:
        d = registrable_domain(_url(h))
        if d and seen[d] >= max_per: tail.append(h); continue
        seen[d] += 1; head.append(h)
    return head + tail, len(tail)

# %% ../nbs/06_quality.ipynb #cd5f778f
_WORD = re.compile(r'[^\W_]+', re.UNICODE)

def _trigrams(text:str) -> set:
    w = _WORD.findall((text or '').casefold())
    return {tuple(w[i:i+3]) for i in range(len(w) - 2)} if len(w) >= 3 else set()

def snippet_similarity(a:str, b:str) -> float:
    "Jaccard over word trigrams. Text shorter than three words scores 0 — no evidence, not a match."
    x, y = _trigrams(a), _trigrams(b)
    return len(x & y) / len(x | y) if x and y else 0.0

def _text(h) -> str:
    if not isinstance(h, dict): return ''
    return ' '.join(str(h.get(k) or '') for k in ('title', 'body', 'content', 'snippet', 'md'))

def diversity(hits:list, threshold:float=0.6) -> dict:
    """Describe a result set: domain spread, url duplication, near-duplicate text, dominant publisher.

    Pure description — this never reorders or drops anything, which is why it is always safe to run and
    always reported. `score` weights domain spread highest because that is the failure that survives
    every other check: five distinct urls from one site are five urls and one source.
    """
    hits = [h for h in hits if isinstance(h, dict)]
    n = len(hits)
    if not n: return dict(score=0.0, n=0, domains=0, dominant_domain=None, dup_urls=0, near_dups=0)
    doms = Counter(d for d in (registrable_domain(_url(h)) for h in hits) if d)
    seen, dup_urls = set(), 0
    for h in hits:
        k = norm_url(_url(h))
        if k in seen: dup_urls += 1
        elif k: seen.add(k)
    txt = [_text(h) for h in hits]
    pairs = n * (n - 1) // 2
    near = sum(1 for i in range(n) for j in range(i) if snippet_similarity(txt[j], txt[i]) >= threshold)
    dom_div, url_uniq = (len(doms) / n), 1.0 - dup_urls / n
    content = 1.0 if not pairs else 1.0 - near / pairs
    top = doms.most_common(1)[0] if doms else None
    return dict(score=round(0.5*dom_div + 0.3*max(0., url_uniq) + 0.2*max(0., content), 4),
                n=n, domains=len(doms), dup_urls=dup_urls, near_dups=near,
                dominant_domain=dict(domain=top[0], share=round(top[1]/n, 4)) if top else None)

# %% ../nbs/06_quality.ipynb #2026423d
def curate(q:str,                  # the query, read for intent and `site:` constraints
           hits:list,              # search hits (dicts with `href`/`url`, `title`, `body`)
           intent:str='auto',      # an intent class, 'auto' to classify, or None to skip authority
           max_per_domain:int=2,   # per-registrable-domain cap; 0 disables
           blocked=(), allowed=(), # extra mirror domains, and rescues from the built-in list
           rerank:bool=True,       # False: describe only, return `hits` untouched
          ) -> tuple:
    """Filter, rerank and describe a result set. Returns `(hits, report)`.

    A query naming its own `site:` is left alone apart from the report: it already said where to look.
    """
    sites = site_domains(q)
    rep = dict(intent=None, site_constrained=sites, dropped=[], demoted=0, authority=None)
    if not hits:
        return hits, dict(rep, diversity=diversity([]))
    out = hits
    if rerank:
        if not sites:
            out, rep['dropped'] = drop_spam(out, blocked=blocked, allowed=allowed)
        cls = classify(q) if intent == 'auto' else intent
        out, rep['authority'] = authority_rerank(out, cls)
        rep['intent'] = cls
        if max_per_domain and not sites:
            out, rep['demoted'] = cap_per_domain(out, max_per_domain)
    else:
        rep['intent'] = classify(q) if intent == 'auto' else intent
    rep['diversity'] = diversity(out)
    return out, rep
