"""web search for AI agents — text, images, news & videos via ddgs, plus direct Google via a stealth browser

Docs: https://vedicreader.github.io/fossick/search.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_search.ipynb.

# %% auto #0
__all__ = ['TEXT_BACKENDS', 'REGION_WORDS', 'TIMELIMITS', 'text', 'images', 'news', 'videos', 'books', 'DATE_META', 'ddgs_env',
           'get_ddgs', 'backends', 'rrf', 'bm25', 'flashrank_scores', 'rerank', 'infer_region', 'search', 'extract',
           'google', 'page_date', 'usable', 'focus', 'research']

# %% ../nbs/02_search.ipynb #f90e2dd9
import json, os, re, sys
from math import log
from urllib.parse import quote_plus, urlsplit, urlunsplit, parse_qsl, urlencode
from fastcore.all import first, bind
from fastcore.parallel import parallel
from scrapling import Selector
from ddgs import DDGS
from .core import to_md, fetch, fossick_cache, _blocked, search_yt
from .quality import norm_url, curate as _curate, host

# %% ../nbs/02_search.ipynb #7cf01c5d
_warned = set()
def _warn(key:str, msg:str):
    "Print `msg` to stderr once per process — a silently empty result set is worse than a noisy one."
    if key not in _warned:
        _warned.add(key)
        print(f'fossick: {msg}', file=sys.stderr)

def ddgs_env() -> dict:
    "Proxy + CA settings for ddgs, read from the environment (`HTTPS_PROXY`, `SSL_CERT_FILE`, …)."
    ev = lambda *ks: first(os.environ.get(k) for k in ks if os.environ.get(k))
    ca = ev('FOSSICK_CA_BUNDLE', 'SSL_CERT_FILE', 'REQUESTS_CA_BUNDLE', 'CURL_CA_BUNDLE')
    return dict(proxy=ev('DDGS_PROXY', 'HTTPS_PROXY', 'https_proxy'), verify=ca or True)

_ddgs = None
def get_ddgs(timeout:int=10):
	global _ddgs
	if _ddgs is None: _ddgs = DDGS(timeout=timeout, **ddgs_env())
	return _ddgs

# %% ../nbs/02_search.ipynb #921db403a2b19be1
TEXT_BACKENDS = ('google', 'brave', 'duckduckgo', 'mojeek', 'yahoo', 'startpage')

def backends(category:str='text') -> list:
    "Every ddgs backend available for `category`."
    from ddgs.engines import ENGINES
    return sorted(ENGINES.get(category, {}))

def _engine_hits(be:str, q:str, region='us-en', page=1, timeout=8, tries=2, **kw) -> list:
    "One backend's results **in its own rank order**, tagged with `engine` and `rank`. `kw` reaches ddgs (`timelimit`, `safesearch`)."
    from ddgs.engines import ENGINES
    cls = ENGINES['text'].get(be)
    if cls is None: return []
    for _ in range(tries):
        try:
            hits = cls(timeout=timeout, **ddgs_env()).search(q, region=region, page=page, **kw) or []
            if hits: return [dict(h.__dict__, engine=be, rank=i+1) for i, h in enumerate(hits)]
        except Exception: pass
    return []

def _backend_lists(q:str, backends, region='us-en', timeout=8, pages=1, **kw) -> list:
    "One rank-ordered list per backend, pulling `pages` result pages from each. Every (backend, page) runs in parallel."
    jobs = [(be, pg) for be in backends for pg in range(1, pages+1)]
    if not jobs: return []
    got = parallel(lambda j: (j, _engine_hits(j[0], q, region=region, page=j[1], timeout=timeout, **kw)),
                   jobs, n_workers=len(jobs), threadpool=True)
    by_be = {}
    for (be, pg), hits in got: by_be.setdefault(be, {})[pg] = hits
    out = []
    for be in backends:
        merged, seen = [], set()
        for pg in sorted(by_be.get(be, {})):
            for h in by_be[be][pg]:
                if (key := norm_url(h.get('href') or h.get('url') or '')) in seen: continue  # page 2 repeats page 1
                seen.add(key)
                merged.append(dict(h, rank=len(merged)+1))    # rank runs on across pages, so RRF sees one list
        if merged: out.append(merged)
    return out

# %% ../nbs/02_search.ipynb #694a35e3
def rrf(lists:list,      # ranked result lists, one per backend
        k:int=60,        # RRF damping constant
       ) -> list:
    "Reciprocal rank fusion: score each url as `sum 1/(k+rank)` across the lists it appears in."
    score, best, engines = {}, {}, {}
    for hits in lists:
        for i, h in enumerate(hits):
            if not (key := norm_url(h.get('href') or h.get('url') or '')): continue
            score[key] = score.get(key, 0.0) + 1/(k + h.get('rank', i+1))
            engines.setdefault(key, []).append(h.get('engine', ''))
            cur = best.get(key)                                  # keep the longest snippet we were given
            if cur is None or len(h.get('body') or '') > len(cur.get('body') or ''): best[key] = h
    out = sorted(score, key=lambda u: -score[u])
    return [dict(best[u], score=round(score[u], 6), engines=[e for e in engines[u] if e]) for u in out]


# %% ../nbs/02_search.ipynb #97ebb463
_word = re.compile(r'[a-z0-9]+')
def _toks(s:str) -> list: return _word.findall((s or '').lower())

def bm25(q:str, docs:list, k1:float=1.5, b:float=0.75) -> list:
    "BM25 scores for `docs` against `q`, with idf computed from `docs` themselves (no index needed)."
    qt = {t for t in _toks(q) if len(t) > 1}
    dts = [_toks(d) for d in docs]
    if not (qt and dts): return [0.0]*len(docs)
    N, avg = len(dts), (sum(map(len, dts))/len(dts)) or 1.0
    idf = {}
    for t in qt:
        df = sum(1 for d in dts if t in d)
        if df: idf[t] = log(1 + (N - df + 0.5)/(df + 0.5))
    out = []
    for dt in dts:
        tf, dl, s = {}, len(dt), 0.0
        for t in dt: tf[t] = tf.get(t, 0) + 1
        for t, iv in idf.items():
            if f := tf.get(t, 0): s += iv * f*(k1+1)/(f + k1*(1 - b + b*dl/avg))
        out.append(s)
    return out

def _hit_text(h:dict) -> str:
    "Title + snippet + the url's own words — a slug like `/enabling-wal-mode` is real evidence."
    u = h.get('href') or h.get('url') or ''
    body = h.get('body') or h.get('content') or ''
    return ' '.join((h.get('title', ''), body, re.sub(r'[/\-_.]', ' ', urlsplit(u).path)))

_ranker = None
def flashrank_scores(q:str, texts:list, model:str=None, cache_dir:str=None) -> list|None:
    "Cross-encoder scores from flashrank, or None when it isn't installed (`pip install flashrank`)."
    global _ranker
    try: from flashrank import Ranker, RerankRequest
    except ImportError: return None
    if _ranker is None:
        _ranker = Ranker(**({'model_name': model} if model else {}),
                         cache_dir=cache_dir or str(fossick_cache('flashrank')))
    rank = getattr(_ranker, 'rerank', None) or _ranker.rank        # 0.2.x renamed rank -> rerank
    out = rank(RerankRequest(query=q, passages=[dict(id=i, text=t) for i, t in enumerate(texts)]))
    s = [0.0]*len(texts)
    for d in out: s[int(d['id'])] = float(d['score'])
    return s

def _unit(xs:list) -> list:
    "Min-max to 0..1 so two scorers on different scales can be blended."
    lo, hi = min(xs), max(xs)
    return [0.5]*len(xs) if hi - lo < 1e-9 else [(x-lo)/(hi-lo) for x in xs]

def rerank(q:str,               # search query
           hits:list,           # fused hits (from `rrf`) or any list of result dicts
           n:int=None,          # keep the top n (None = all)
           method:str='none',   # none | lexical | flashrank | auto
           mix:float=0.4,       # weight on the retrieval score vs the reranker (1 = ignore the reranker)
          ) -> list:
    "Re-order hits by relevance to `q`, blending the reranker with the retrieval score."
    if not hits or method == 'none': return hits[:n] if n else hits
    texts, rs = [_hit_text(h) for h in hits], None
    if method in ('auto', 'flashrank'):
        try: rs = flashrank_scores(q, texts)
        except Exception:
            if method == 'flashrank': raise
            rs = None                                      # 'auto' degrades to lexical, never to nothing
    if rs is None:
        if method == 'flashrank': raise ImportError('flashrank is not installed: pip install fossick[rerank]')
        rs = bm25(q, texts)
    ret = _unit([h.get('score', 0.0) for h in hits])
    rel = _unit(rs)
    out = sorted(range(len(hits)), key=lambda i: -(mix*ret[i] + (1-mix)*rel[i]))
    hits = [dict(hits[i], rerank=round(rel[i], 4)) for i in out]
    return hits[:n] if n else hits

# %% ../nbs/02_search.ipynb #677a80fd
#: Country words worth acting on: the ones where the answer itself changes with the country —
#: law, price, availability, what is even for sale. Keyed by ddgs region (`country-lang`).
REGION_WORDS = {
    'au-en': ('australia', 'australian', 'aussie'),
    'ca-en': ('canada', 'canadian'),
    'ie-en': ('ireland', 'irish'),
    'in-en': ('india', 'indian'),
    'nz-en': ('new zealand', 'nz'),
    'sg-en': ('singapore', 'singaporean'),
    'uk-en': ('uk', 'u.k.', 'united kingdom', 'britain', 'british', 'england', 'scotland',
              'scottish', 'wales', 'welsh', 'northern ireland'),
    'us-en': ('usa', 'u.s.', 'u.s.a.', 'united states', 'america', 'american'),
    'za-en': ('south africa', 'south african'),
    'ae-en': ('uae', 'u.a.e.', 'dubai', 'abu dhabi'),
    # Non-English markets: the country's name only. A demonym here is usually the language.
    'br-pt': ('brazil',), 'de-de': ('germany', 'deutschland'), 'es-es': ('spain',),
    'fr-fr': ('france',), 'it-it': ('italy',), 'jp-jp': ('japan',),
    'mx-es': ('mexico',), 'nl-nl': ('netherlands', 'holland'),
}

#: `timelimit` values every ddgs text engine understands.
TIMELIMITS = ('d', 'w', 'm', 'y')

_region_rx = None
def _region_pats():
    "The alternation and its region lookup, built once. Longest phrase first, so `u.s.a.` beats `u.s.`."
    global _region_rx
    if _region_rx is None:
        pairs = sorted(((w, r) for r, ws in REGION_WORDS.items() for w in ws), key=lambda t: -len(t[0]))
        rx = re.compile('|'.join(f'(?<![a-z0-9])({re.escape(w)})(?![a-z0-9])' for w, _ in pairs))
        _region_rx = (rx, [r for _, r in pairs])
    return _region_rx

def infer_region(q:str,             # the query, read for a country
                 dflt:str='us-en',  # when it names none
                ) -> str:
    """The ddgs region a query asks for in its own words — 'rebuild my garage in australia' -> 'au-en'.

    Deliberately conservative: only country words count, and a query naming two countries resolves to
    the one mentioned first, which is where the question usually is. Everything else is `dflt`, so a
    caller who knows better passes `region=` and is never second-guessed.
    """
    rx, regions = _region_pats()
    m = rx.search((q or '').lower())
    return regions[m.lastindex - 1] if m else dflt

def _region(q:str, region:str) -> str:
    "Resolve `region='auto'` (or None) against the query; anything explicit passes straight through."
    return infer_region(q) if region in (None, 'auto') else region


# %% ../nbs/02_search.ipynb #780933b0
def _fused(q, n, backends, region, timeout, k, method, pages, kw=()):
    "Fan out, fuse, rerank. Raises when every backend failed, so a transient outage isn't cached for 15 minutes."
    lists = _backend_lists(q, backends, region=region, timeout=timeout, pages=pages, **dict(kw))
    if not (out := rerank(q, rrf(lists, k=k), n=n, method=method)):
        raise ValueError('every backend returned nothing')
    return out

def _search_fused(q, n, backends, region, timeout, k, method, pages, kw=()):
    try: return _fused(q, n, backends, region, timeout, k, method, pages, kw)
    except ValueError as e:
        _warn('search', f'search({q!r}) got nothing: {e}')
        return []

def _search_ddgs(q, category, kw):
    try: return getattr(get_ddgs(), category)(q, **dict(kw))
    except Exception as e:
        _warn(f'search/{category}', f'search({q!r}, {category!r}) failed: {type(e).__name__}: {e}')
        return []

def search(q:str,                  # search query
           category:str='text',    # text | images | news | videos | books
           n:int=10,               # number of results to return
           fuse:bool=True,         # fan out across backends and fuse with RRF (text only)
           backend:str=None,       # restrict to a single ddgs backend, e.g. 'google'
           method:str='none',      # rerank method: none | lexical | flashrank | auto
           pages:int=1,            # result pages to pull from each backend (raises the candidate pool)
           region:str='auto',      # ddgs region, or 'auto' to read the country off the query
           timelimit:str=None,     # d | w | m | y — only results from the last day/week/month/year
           timeout:int=8,
           **kw,                   # extra kwargs passed to ddgs (max_results, safesearch, page)
          ) -> list:
    "Search the web. Text results are fused across backends with RRF; pass method='lexical' or 'flashrank' to rerank."
    if not (q and q.strip()): return []
    assert category in ('text', 'images', 'news', 'videos', 'books'), f'Invalid category: {category}'
    n = kw.pop('max_results', None) or n
    region = _region(q, region)
    if category == 'videos': return search_yt(q, n, **kw)
    if timelimit: kw['timelimit'] = timelimit
    if category == 'text' and fuse:
        bes = (backend,) if backend else TEXT_BACKENDS
        return _search_fused(q, n, tuple(bes), region, timeout, 60, method, max(pages, 1),
                             tuple(sorted(kw.items())))
    kw = dict(kw, max_results=n, region=region)
    if backend: kw['backend'] = backend
    return _search_ddgs(q, category, tuple(sorted(kw.items())))

text = bind(search, category='text')
images = bind(search, category='images')
news = bind(search, category='news')
videos = bind(search, category='videos')
books = bind(search, category='books')

def extract(url, **kw): return get_ddgs().extract(url, **kw)

# %% ../nbs/02_search.ipynb #61e5cac2
def _parse_google(html:str, n:int) -> list:
    "Parse organic results from a rendered Google SERP into dicts (title, url, content)."
    sel = Selector(html)
    out, seen = [], set()
    for h3 in sel.css('h3'):
        a = h3.parent
        while a is not None and a.tag != 'a': a = a.parent          # nearest ancestor anchor
        if a is None: continue
        href = a.attrib.get('href', '')
        if not href.startswith('http') or 'google.' in href or href in seen: continue
        box = a
        for _ in range(4): box = box.parent if box.parent is not None else box   # climb to result container
        snip = first(box.css('div.VwiC3b'))                         # Google's snippet block
        seen.add(href)
        out.append(dict(title=h3.get_all_text().strip(), href=href, rank=len(out)+1, engine='google',
                        content=snip.get_all_text().strip() if snip else '', score=float(n - len(out))))
        if len(out) >= n: break
    return out

def _google(q:str, n:int, lang:str, gl:str=None, tbs:str=None) -> list:
    "Stealth-browser Google fetch+parse, memoized. Raises on empty so throttled/failed calls aren't cached."
    # `gl` biases ranking towards a country; `cr` would *exclude* everything else, which throws away
    # the authoritative .com page about Australian rules along with the noise.
    url = f'https://www.google.com/search?q={quote_plus(q)}&hl={lang}&num={n+2}'
    if gl: url += f'&gl={gl}'
    if tbs: url += f'&tbs={tbs}'
    pg = fetch(url, stealthy=True, network_idle=True)
    res = _parse_google(pg.html_content, n) if pg.status == 200 else []
    if not res: raise ValueError('no google results')
    return res

def _google_cached(q:str, n:int, lang:str, gl:str=None, tbs:str=None) -> list: return _google(q, n, lang, gl, tbs)

def google(q:str,                # search query
           n:int=10,             # number of results
           lang:str=None,        # `hl`; defaults to the language half of `region`
           region:str='auto',    # ddgs-style region, or 'auto' to read the country off the query
           timelimit:str=None,   # d | w | m | y — Google's own `tbs=qdr:` filter
          ) -> list:
    "Search Google directly via a stealth browser (real Google ranking). Returns dicts, same shape as search()."
    if not q or not q.strip(): return []
    gl, _, rlang = _region(q, region).partition('-')
    tbs = f'qdr:{timelimit}' if timelimit in TIMELIMITS else None
    try: return _google_cached(q, n, lang or rlang or 'en', gl, tbs)   # memoized on the raising call
    except ValueError: return []
    except Exception as e:
        _warn('google', f'google() is falling back to nothing: {type(e).__name__}: {e}')
        return []

# %% ../nbs/02_search.ipynb #0624580b
_MIN_CHARS = 400

#: `<meta>` names every common CMS emits for a publication date, lowercased.
DATE_META = ('article:published_time', 'og:published_time', 'citation_publication_date',
             'datepublished', 'dc.date.issued', 'dcterms.date', 'sailthru.date',
             'parsely-pub-date', 'pubdate', 'publish-date', 'date')

# Longest alternative first in both groups, and no digit may follow: `0?[1-9]` would
# otherwise take the '1' of '11' and turn 2019-11-02 into 2019-01-01.
_ISO = re.compile(r'(?:19|20)\d{2}[-/](?:1[0-2]|0?[1-9])(?:[-/](?:3[01]|[12]\d|0?[1-9]))?(?!\d)')

def _iso(s) -> str:
    "The first `YYYY-MM-DD` in `s`, zero-padded; day 01 when only a month is given. None if there is none."
    if not s: return None
    if not (m := _ISO.search(str(s))): return None
    p = re.split(r'[-/]', m.group(0))
    return f'{p[0]}-{p[1].zfill(2)}-{(p[2].zfill(2) if len(p) > 2 else "01")}'

def _ld_nodes(html:str):
    "Every schema.org object on the page, flattened — a `@graph` is one script tag holding a dozen."
    out = []
    for m in re.finditer(r'<script[^>]+application/ld\+json[^>]*>(.*?)</script>', html, re.S | re.I):
        try: data = json.loads(m.group(1).strip())
        except Exception: continue
        todo = data if isinstance(data, list) else [data]
        while todo:
            nd = todo.pop(0)
            if not isinstance(nd, dict): continue
            out.append(nd)
            if isinstance(g := nd.get('@graph'), list): todo += g
    return out

def page_date(page) -> str:
    """When a page says it was published, as `YYYY-MM-DD` — or None when it does not say.

    Three sources, in the order they can be trusted: schema.org JSON-LD, the publication `<meta>`
    tags, and finally a `/2024/03/` in the url. Undated is left undated rather than guessed, because
    a wrong date is worse than none: a price or a regulation you cannot place in time is a fact you
    cannot use, and `research()` puts this on every source so the reader can tell.
    """
    # Duck-typed like `core._blocked`, not via `core._html`: that one returns None for anything
    # that isn't a scrapling Response, and a page here can be any object carrying markup.
    html = page if isinstance(page, str) else (getattr(page, 'html', None) or getattr(page, 'html_content', '') or '')
    for nd in _ld_nodes(html):
        for k in ('datePublished', 'dateCreated', 'uploadDate', 'dateModified'):
            if (d := _iso(nd.get(k))): return d
    for m in re.finditer(r'<meta[^>]+>', html, re.I):
        tag = m.group(0)
        nm = re.search(r'(?:name|property|itemprop)\s*=\s*["\']([^"\']+)', tag, re.I)
        if nm and nm.group(1).strip().lower() in DATE_META:
            c = re.search(r'content\s*=\s*["\']([^"\']+)', tag, re.I)
            if c and (d := _iso(c.group(1))): return d
    if (m := re.search(r'<time[^>]+datetime\s*=\s*["\']([^"\']+)', html, re.I)) and (d := _iso(m.group(1))): return d
    url = '' if isinstance(page, str) else str(getattr(page, 'url', '') or '')
    if (m := re.search(r'/((?:19|20)\d{2}/\d{1,2})/', url)): return _iso(m.group(1))
    return None

def _why(pg) -> str:
    "Why a fetched page was unusable — surfaced in `research()['dropped']` instead of vanishing."
    if pg is None: return 'fetch failed'
    if (st := getattr(pg, 'status', 0)) != 200: return f'http {st}'
    if getattr(pg, 'tier', '') == 'blocked' or _blocked(pg): return 'bot wall / challenge page'
    return 'no readable content'

def usable(pg, min_chars:int=_MIN_CHARS) -> bool:
    "Did this fetch return a readable page, or an error / bot wall / empty JS shell?"
    return pg is not None and getattr(pg, 'status', 0) == 200 \
        and getattr(pg, 'tier', '') != 'blocked' and not _blocked(pg)

def _split_blocks(md:str, max_len:int=1200) -> list:
    # The length cap matters: an un-paragraphed wall of text is a single block, and a block bigger
    # than the whole character budget can never be selected, so the page contributes nothing.
    "Markdown -> blocks: split on blank lines, glue a heading to the text under it, cap the length."
    parts, out = [p.strip() for p in re.split(r'\n\s*\n', md) if p.strip()], []
    for p in parts:
        if out and out[-1].lstrip().startswith('#') and len(out[-1]) < max_len: out[-1] += '\n\n' + p
        else: out.append(p)
    res = []
    for p in out:
        while len(p) > max_len:
            cut = (p.rfind('. ', 0, max_len) + 1) or max_len       # prefer a sentence boundary
            res.append(p[:cut].strip()); p = p[cut:].strip()
        if p: res.append(p)
    return res

def focus(md:str,            # page markdown
          q:str,             # query to keep relevant to
          chars:int=4000,    # character budget
          reserve:float=0.3, # fraction of the budget spent on the top of the page before ranking
          lead:float=0.6,    # extra score for blocks near the top (intros define things)
         ) -> str:
    "Keep the parts of `md` that answer `q`, in document order, within `chars`."
    if not md or len(md) <= chars: return md
    bl = _split_blocks(md)
    if len(bl) < 2: return md[:chars]
    keep, used = set(), 0
    for i, b in enumerate(bl):                     # a reference page often answers in its opening
        if used + len(b) > chars*reserve: break
        keep.add(i); used += len(b)
    sc = bm25(q, bl)
    top = max(sc) or 1.0
    sc = [s + lead*top*(1 - i/len(bl)) for i, s in enumerate(sc)]
    for i in sorted(range(len(bl)), key=lambda i: -sc[i]):
        if i in keep or used + len(bl[i]) > chars: continue
        keep.add(i); used += len(bl[i])
        if used >= chars*0.95: break
    if not keep: return max(zip(sc, bl), key=lambda t: t[0])[1][:chars]   # nothing fit: best block, clipped
    out, prev = [], -1
    for i in sorted(keep):
        if prev >= 0 and i > prev + 1: out.append('…')
        out.append(bl[i]); prev = i
    return '\n\n'.join(out)

def _fetch_batch(urls:list, concurrency:int=8, **kw) -> list:
    "fetch() each url in parallel, returning None where it raised — one dead host mustn't kill the batch."
    def _one(u):
        try: return fetch(u, **kw)
        except Exception: return None
    return list(parallel(_one, urls, n_workers=min(concurrency, len(urls) or 1), threadpool=True))

def research(q:str,                 # search query
             n:int=5,               # number of readable sources to gather
             engine:str='search',   # 'search' (fused metasearch) or 'google' (stealth browser ranking)
             sel:str=None,          # CSS selector to narrow each page before markdown
             chars:int=4000,        # max markdown chars kept per page
             auto:bool=True,        # auto-escalate fetching (plain->heavy->stealthy->session) per page
             region:str='auto',     # ddgs region, or 'auto' to read the country off the query
             timelimit:str=None,    # d | w | m | y — only sources from the last day/week/month/year
             curated:bool=True,     # drop mirror domains and rank by source authority before reading
             intent:str='auto',     # authority class ('policy', 'docs', …), 'auto' to read it off `q`
             focused:bool=True,     # keep query-relevant passages instead of the first `chars` chars
             candidates:int=None,   # how many hits to draw on when backfilling (default 3n)
             pages:int=1,           # result pages per backend (raise it when `candidates` exceeds one page)
             concurrency:int=8,
             **kw,                  # extra kwargs passed to fetch()
            ) -> dict:
    "Query -> read the top `n` *readable* results -> a cited markdown corpus. Returns {query, sources, digest, dropped, region, curation}."
    if not (q and q.strip()):
        return dict(query=q, sources=[], digest='', dropped=[], region=_region(q, region), curation=None)
    cand = candidates or max(3*n, n+5)
    region = _region(q, region)
    hits = (google(q, n=cand, region=region, timelimit=timelimit) if engine == 'google'
            else search(q, n=cand, region=region, timelimit=timelimit, pages=pages))
    # Curate before fetching, not after: `research` reads the candidates in order, so the ordering
    # *is* the choice of which pages get read. Filtering afterwards would have paid for them first.
    hits, curation = _curate(q, hits, intent=intent) if curated else (hits, None)
    todo, seen = [], set()
    for h in hits:
        u = h.get('href') or h.get('url')
        if u and (key := norm_url(u)) not in seen:
            seen.add(key); todo.append((h, u))
    sources, dropped, i = [], [], 0
    while len(sources) < n and i < len(todo):
        batch = todo[i:i + (n - len(sources))]; i += len(batch)
        for (h, u), pg in zip(batch, _fetch_batch([u for _, u in batch], concurrency, sel=sel, auto=auto, **kw)):
            title = h.get('title') or u
            md = ''
            if usable(pg):
                try: md = to_md(pg, sel=sel)
                except Exception: md = ''
            if len(md.strip()) < _MIN_CHARS:
                dropped.append(dict(title=title, href=u, reason=_why(pg))); continue
            sources.append(dict(title=title, href=u, tier=getattr(pg, 'tier', 'plain'),
                                date=page_date(pg),
                                md=focus(md, q, chars) if focused else md[:chars]))
    sources = sources[:n]
    # The date goes in the digest, not just the dict: the model reading this is the one that has to
    # notice the price it is quoting was published in 2018.
    digest = '\n\n---\n\n'.join(
        f'## {s["title"]}\n{s["href"]}' + (f'\npublished: {s["date"]}' if s['date'] else '') + f'\n\n{s["md"]}'
        for s in sources)
    return dict(query=q, sources=sources, digest=digest, dropped=dropped, region=region,
                curation=curation)

