"""private web search through a local SearXNG instance

Docs: https://vedicreader.github.io/fossicksearch.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_search.ipynb.

# %% auto #0
__all__ = ['searxng_start', 'searxng_stop', 'Result', 'search']

# %% ../nbs/02_search.ipynb #00000002
import os, time, atexit, shutil
import httpx
from fastcore.all import AttrDictDefault, L, Path
from .core import save_path, http_get
from dockeasy import env_get, env_set, Compose

# %% ../nbs/02_search.ipynb #00000005
_SEARXNG_URL   = 'http://localhost:8080'
_SEARXNG_NAME  = 'fossick-searxng'
_SEARXNG_NET   = 'fossick-net'
_SEARXNG_DIR   = save_path('searxng')
_COMPOSE_PATH  = str(_SEARXNG_DIR / 'docker-compose.yml')

def _wait_for_searxng(url:str, timeout:int=30, interval:float=0.5):
    "Poll SearXNG until HTTP 200 or raise RuntimeError on timeout."
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            if httpx.get(url, timeout=2).status_code == 200: return
        except Exception: pass
        time.sleep(interval)
    raise RuntimeError(f'SearXNG did not start within {timeout}s at {url}. Is Docker running?')

# %% ../nbs/02_search.ipynb #00000006
def searxng_start(settings:Path=None) -> str:
    "Start SearXNG + Redis via Compose. `settings` overrides the bundled searxng_settings.yml. Idempotent."
    try:
	    if (url:=env_get('SEARXNG_URL')) and http_get(url).status_code == 200: return url
	    if http_get(_SEARXNG_URL).status_code == 200: return _SEARXNG_URL
    except Exception: pass
    _SEARXNG_DIR.mkdir(parents=True, exist_ok=True)
    f = __file__ if '__file__' in globals() else '.'
    src = Path(settings) if settings else Path(f).parent / 'searxng_settings.yml'
    shutil.copy(src, _SEARXNG_DIR / 'settings.yml')
    (Compose()
        .network(_SEARXNG_NET)
        .svc('redis',
             image='redis:7-alpine',
             command='redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --save ""',
             networks=[_SEARXNG_NET],
             restart='unless-stopped')
        .svc('searxng',
             image='searxng/searxng:latest',
             ports={'8080': '8080'},
             volumes={str(_SEARXNG_DIR): '/etc/searxng'},
             env={'SEARXNG_SECRET': 'fossick'},
             container_name=_SEARXNG_NAME,
             depends_on=['redis'],
             networks=[_SEARXNG_NET])
        .up(detach=True, path=_COMPOSE_PATH))
    _wait_for_searxng(_SEARXNG_URL)
    env_set('SEARXNG_URL', _SEARXNG_URL)
    return _SEARXNG_URL

def searxng_stop():
    "Stop SearXNG + Redis if we started them. No-op otherwise."
    from dockeasy import Compose
    try: Compose().down(path=_COMPOSE_PATH)
    except Exception: pass

atexit.register(searxng_stop)

# %% ../nbs/02_search.ipynb #00000008
class Result(AttrDictDefault):
    "One search result. Fields: title, url, snippet, score, engines, provider, ts."

# SearXNG category by query intent
_category_map = dict(academic='science', code='it', recent='news', default='general')
_intents = dict(
    academic=['research', 'paper', 'study', 'arxiv', 'doi', 'journal',
              'citation', 'how does', 'why is', 'explain', 'mechanism'],
    code=['github', 'stackoverflow', 'npm', 'pypi', 'repo'],
    recent=['today', 'yesterday', 'this week', 'latest', 'breaking',
              'current', 'just announced', '2025', '2026'])

def _intent(q:str) -> tuple:
    "Return (intent, searxng_category) for query q. Requires >=2 signals to route away from general."
    ql = q.lower()
    scores = {k: sum(1 for p in ps if p in ql) for k, ps in _intents.items()}
    intent = max(scores, key=scores.get) if max(scores.values()) >= 2 else 'default'
    return intent, _category_map.get(intent, 'general')

# %% ../nbs/02_search.ipynb #00000010
def _searxng(q:str, n:int=10, category:str=None, engines:str=None) -> L:
    "Search via SearXNG JSON API. Returns L of Result."
    try:
        url = searxng_start()
        params = {'q': q, 'format': 'json', 'pageno': 1}
        if category: params['categories'] = category
        if engines:  params['engines']    = engines
        r = http_get(f'{url}/search', params=params)
        if r.status_code != 200: return L()
        mk_res = lambda x: Result(title=x.get('title', ''),
            url=x.get('url', ''),snippet=x.get('content', ''),
            score=x.get('score', 0.0), engines=x.get('engines', []),
            provider='searxng', ts=time.time())
        return L(r.json().get('results', [])[:n]).map(mk_res)
    except Exception as e:
        print(f'searxng error: {e}')
        return L()

# %% ../nbs/02_search.ipynb #00000015
def search(q:str,
           n:int=10,           # max results
           category:str=None,  # override SearXNG category (general/science/it/news)
           engines:str=None,   # comma-sep engine names passed to SearXNG
          ) -> L:
    "Search the web. Returns L of Result sorted by relevance."
    if not q or not q.strip(): return L()
    intent, cat = _intent(q)
    cat = category or cat
    return _searxng(q, n, category=cat, engines=engines)
