# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_shop.ipynb.

# %% auto #0
__all__ = ['SHOP_JS', 'SITES', 'FIELD_MAP', 'PAY_RX', 'site_hint', 'ShopError', 'match_fields', 'Shop', 'shop']

# %% ../nbs/05_shop.ipynb #2d92e9e68b664faf
import json, time, re, asyncio, difflib, html
from urllib.parse import quote_plus, urlparse
from fastcore.all import patch, store_attr, first
from fastcdp import *
from .cdp import cdp_connect, syncy

# %% ../nbs/05_shop.ipynb #d23993dd45b41a5e
SHOP_JS = r'''
window.__fk = (() => {
const PRICE_RX = /(?:AU\$|NZ\$|US\$|CA\$|\$|€|£|₹|¥)\s?\d[\d,]*(?:\.\d{1,2})?|\d[\d,]*(?:\.\d{1,2})?\s?(?:AUD|USD|EUR|GBP|NZD|CAD)\b/;
const ADD_RX  = /^(?:add|add\s?\+|\+\s?add|add to (?:cart|bag|basket|trolley|order|box)|add item|add one|quick add|quick buy|buy now|order now)\b/i;
const NOTADD_RX = /add to (list|wish|registry|favou?rites|compare)|save for later|remove|delete|view details/i;
const OOS_RX  = /out of stock|sold out|currently unavailable|notify me|back in stock|temporarily out/i;
const TOAST_RX = /added to (your )?(cart|bag|basket|trolley|order)|added!|item added|added successfully|now in your (cart|bag|basket)/i;
const UTIL_RX = /\/(cart|checkout|login|signin|sign-in|register|account|help|wishlist|favourites|compare|quickview|quick-view|size-guide|sizing|reviews?|questions|blog|news|policies|pages|terms|privacy|contact|about|offer-listing|sell|gift)(\/|$|\?)|[?&](sort|order|page|filter|view)=/i;
const KEEP_Q  = /^(variant|variant_id|id|product_id|productid|sku|pid|item|itemid|p|colour|color|size)$/i;
const CARTHREF_RX = /\/(cart|basket|trolley|bag|checkout\/cart|gp\/cart)(\/|$|\?|\.)/i;
const COUNT_RX = /count|badge|bubble|indicator|num|items\b/i;
const SEARCH_SEL = 'input[type=search], [role=searchbox], input[name=q], input[name=s], input[name=search], input[name=searchTerm], input[name=search_query], input[name=query], input[name=keyword], input[name=k], input[placeholder*=search i], input[aria-label*=search i]';

const rect = el => (el && el.getBoundingClientRect ? el.getBoundingClientRect() : {width: 0, height: 0});
const shown = el => {   // laid out at all. Deliberately ignores opacity: grids that fade cards in on
  if (!el) return false; // scroll are still real, and requiring opacity>0 hides most of the page.
  const r = rect(el);
  return (r.width > 0 || r.height > 0) && getComputedStyle(el).visibility !== 'hidden';
};
const txt = el => (el && (el.innerText || el.textContent) || '').replace(/\s+/g, ' ').trim();
const num = s => {
  const m = String(s == null ? '' : s)
    .replace(/(\d)[ \t\u00a0]+(\d{2})(?!\d)/g, '$1.$2')   // "$27 82" -> "$27.82" (split fraction span)
    .replace(/\s+/g, '').match(PRICE_RX);
  if (!m) return null;
  const n = parseFloat(m[0].replace(/[^\d.,]/g, '').replace(/,(?=\d{3}(\D|$))/g, '').replace(',', '.'));
  return isFinite(n) ? n : null;
};
const priceOf = el => {   // explicit price markup first — amazon splits $12.99 across spans
  for (const sel of ['.a-offscreen', '[itemprop=price]', 'meta[itemprop=price]', '[data-price]', '[class*=price i]']) {
    for (const e of el.querySelectorAll(sel)) {
      const v = num(e.getAttribute('content') || e.getAttribute('data-price') || txt(e));
      if (v) return v;
    }
  }
  return num(txt(el));
};
const norm = href => {   // same-origin URL, tracking params and /ref= segments dropped
  try {
    const u = new URL(href, location.href);
    if (u.origin !== location.origin) return null;
    u.hash = '';
    u.pathname = u.pathname.replace(/\/ref=[^/]*$/, '').replace(/\/+$/, '');
    [...u.searchParams.keys()].forEach(k => { if (!KEEP_Q.test(k)) u.searchParams.delete(k); });
    return u.pathname && u.pathname !== '/' ? u.origin + u.pathname + (u.search || '') : null;
  } catch (e) { return null; }
};
const shape = url => {   // /x/dp/B008S6GEB2 -> /*/dp/* ; /products/291-apples-fuji -> /products/*
  try {
    return new URL(url).pathname.split('/').filter(Boolean)
      .map(s => (/\d/.test(s) || s.length > 24 || s.includes('-') ? '*' : s)).join('/');
  } catch (e) { return ''; }
};
const inChrome = el => !!el.closest('header, nav, footer, [role=navigation], [role=banner], [role=contentinfo]');

const findBtn = card => {
  let loose = null;
  for (const b of card.querySelectorAll('button, input[type=submit], input[type=button], a[href], [role=button]')) {
    if (b.disabled || !shown(b)) continue;
    const label = (b.value || b.getAttribute('aria-label') || txt(b) || b.title || '').trim();
    if (NOTADD_RX.test(label) || /wish|compare|subscribe/i.test(label)) continue;
    if (ADD_RX.test(label)) return b;
    const key = [b.className, b.name, b.id, b.getAttribute('data-testid')].join(' ');
    if (!loose && /add[-_]?to|addto|add[-_]?cart|add[-_]?item/i.test(key) &&
        !/remove|delete|wish|compare/i.test(key)) loose = b;
  }
  return loose;
};
const findQty = card => {
  for (const e of card.querySelectorAll('select, input[type=number], input[name*=quant i], input[name*=qty i], input[aria-label*=quant i]')) {
    if (!shown(e)) continue;
    const key = [e.name, e.id, e.className, e.getAttribute('aria-label'), txt(e.closest('label'))].join(' ');
    if (e.tagName === 'SELECT' && !/qty|quantity/i.test(key)) continue;
    return {el: e, kind: e.tagName === 'SELECT' ? 'select' : 'input'};
  }
  const plus = [...card.querySelectorAll('button, [role=button]')].find(b => shown(b) &&
    /^\+$|increase|increment|add one more|plus/i.test((b.getAttribute('aria-label') || txt(b) || b.className)));
  return plus ? {el: plus, kind: 'stepper'} : null;
};
const titleOf = (card, els) => {
  for (const sel of ['h1', 'h2', 'h3', 'h4', '[itemprop=name]', '[class*=title i]', '[class*=product-name i]', '[class*=name i]']) {
    const t = txt(card.querySelector(sel));
    if (t && t.length > 2 && num(t) === null) return t.slice(0, 160);
  }
  const byText = els.map(e => txt(e)).filter(t => t.length > 2 && num(t) === null).sort((a, b) => b.length - a.length)[0];
  if (byText) return byText.slice(0, 160);
  const byAlt = els.map(e => ((e.querySelector('img') || {}).alt) || e.getAttribute('aria-label') || '')
                   .sort((a, b) => b.length - a.length)[0];
  return (byAlt || '').slice(0, 160);
};
const variantId = card => {   // shopify add-to-cart forms carry the variant id in input[name=id]
  const f = card.querySelector('form[action*="/cart/add"], form[action*="/cart"]');
  const i = (f || card).querySelector('input[name=id]:not([disabled]), select[name=id]');
  return /^\d{6,}$/.test((i && i.value) || '') ? i.value : null;
};

function rawCards(shapeFilter) {
  const groups = new Map(), linkHref = new Map();
  for (const a of document.querySelectorAll('a[href]')) {
    const raw = a.getAttribute('href') || '';
    if (/^(#|javascript:|mailto:|tel:)/.test(raw)) continue;
    const h = norm(raw);
    if (!h || UTIL_RX.test(h) || !shown(a)) continue;
    if (!a.querySelector('img, picture, svg') && txt(a).length < 3) continue;   // icon-only utility links
    if (!groups.has(h)) groups.set(h, []);
    groups.get(h).push(a);
    linkHref.set(a, h);
  }
  // Count only links that passed the filter above. Re-deriving hrefs here would re-admit
  // href="#", which resolves to the current page and can collide with a real candidate —
  // that stops the climb one level short and loses the add button.
  const nHrefs = el => {
    const s = new Set();
    for (const a of el.querySelectorAll('a[href]')) { const h = linkHref.get(a); if (h) s.add(h); }
    return s.size;
  };
  const seen = new Set(), out = [];
  for (const [h, els] of groups) {
    let card = els[0], up = 0;
    while (card.parentElement && up < 12) {
      const p = card.parentElement;
      if (p === document.body || nHrefs(p) > 1) break;
      card = p; up++;
    }
    if (seen.has(card) || card === document.body) continue;
    const price = priceOf(card), btn = findBtn(card), title = titleOf(card, els);
    if (!title || title.length < 3) continue;
    if (price === null && !btn) continue;
    if (inChrome(card) && !btn) continue;
    seen.add(card);
    out.push({card, url: h, title, price, btn, qty: findQty(card), vid: variantId(card)});
  }
  if (shapeFilter !== false && out.length >= 4) {   // drop stragglers: keep the dominant URL shape
    const tally = {};
    out.forEach(c => { const s = shape(c.url); tally[s] = (tally[s] || 0) + 1; });
    const best = Object.entries(tally).sort((a, b) => b[1] - a[1])[0];
    if (best && best[1] >= out.length / 2) return out.filter(c => shape(c.url) === best[0]);
  }
  return out;
}

function isPdp() {
  if (window.ShopifyAnalytics && ((window.ShopifyAnalytics.meta || {}).page || {}).pageType === 'product') return true;
  const og = document.querySelector('meta[property="og:type"]');
  if (og && /product/i.test(og.content || '')) return true;
  for (const s of document.querySelectorAll('script[type="application/ld+json"]')) {
    try {
      const j = JSON.parse(s.textContent);
      const arr = [].concat(Array.isArray(j) ? j : [j], j['@graph'] || []);
      if (arr.some(o => o && /Product/i.test(String(o['@type'] || '')))) return true;
    } catch (e) {}
  }
  return false;
}
function single() {   // the one buyable thing on a product-detail page
  const btn = findBtn(document.body);
  const h1 = document.querySelector('h1');
  if (!btn && !h1) return [];
  const scope = (h1 && h1.closest('main, [role=main], form, article, section')) || document.body;
  const title = txt(h1) || (document.querySelector('meta[property="og:title"]') || {}).content || document.title;
  return [{card: scope, url: norm(location.href) || location.href, title: (title || '').trim().slice(0, 160),
           price: priceOf(scope), btn, qty: findQty(scope), vid: variantId(scope)}];
}

function tag(list) {
  ['data-fk', 'data-fk-add', 'data-fk-qty'].forEach(a =>
    document.querySelectorAll('[' + a + ']').forEach(e => e.removeAttribute(a)));
  return list.map((c, i) => {
    c.card.setAttribute('data-fk', i);
    if (c.btn) c.btn.setAttribute('data-fk-add', i);
    if (c.qty) c.qty.el.setAttribute('data-fk-qty', i);
    return {i, title: c.title, price: c.price, url: c.url, add: !!c.btn,
            add_label: c.btn ? (c.btn.value || c.btn.getAttribute('aria-label') || txt(c.btn) || '').trim().slice(0, 40) : null,
            qty: c.qty ? c.qty.kind : null, vid: c.vid, related: c.related || null,
            oos: OOS_RX.test(txt(c.card)) || null};
  });
}
function products(limit) {
  const grid = rawCards();
  let list = grid;
  if (isPdp() || grid.length < 2) {   // main product first, recommendations flagged `related`
    const s = single();
    if (s.length && s[0].title) {
      const rest = grid.filter(c => c.url !== s[0].url);
      rest.forEach(c => { c.related = true; });
      list = s.concat(rest);
    }
  }
  return tag(list.slice(0, limit || 60));
}

function badges() {
  // Three tiers, strongest first: an explicit count node, a link to the cart page, a cart-named
  // control. Arbitrary page text is never trusted — "Filter Basket" in a product title is not a badge.
  const tiers = [[], [], []], seen = new Set();
  const grab = el => {
    const m = [el.getAttribute('aria-label'), el.title, txt(el)].filter(Boolean).join(' ').match(/(\d+)/);
    return m ? parseInt(m[1]) : null;
  };
  const push = (t, el, src) => {
    const n = grab(el);
    if (n === null || n > 999 || seen.has(el) || el.closest('[data-fk]')) return;
    const body = [el.getAttribute('aria-label'), txt(el)].filter(Boolean).join(' ');
    if (PRICE_RX.test(body) && !/\bitems?\b|\bcount\b/i.test(body)) return;   // that is a price
    seen.add(el);
    tiers[t].push({n, tier: t, src: (src || '').replace(/\s+/g, ' ').trim().slice(0, 50)});
  };
  for (const el of document.querySelectorAll('[id],[class],[data-cart-count],[data-testid]')) {
    if (!shown(el) || el.children.length > 2 || /^(INPUT|SELECT|TEXTAREA|OPTION)$/.test(el.tagName)) continue;
    const key = [el.id, el.className, el.getAttribute('data-testid')].join(' ');
    if (/cart|basket|trolley|bag/i.test(key) && COUNT_RX.test(key)) push(0, el, key);
  }
  for (const a of document.querySelectorAll('a[href]'))
    if (shown(a) && CARTHREF_RX.test(a.getAttribute('href') || '')) push(1, a, txt(a) || a.getAttribute('href'));
  for (const el of document.querySelectorAll('a, button, [role=button], [role=link]')) {
    if (!shown(el)) continue;
    const nm = (el.getAttribute('aria-label') || txt(el) || '').trim();
    if (nm.length > 60 && !/\b(cart|basket|trolley|bag)\b/i.test(el.getAttribute('aria-label') || '')) continue;
    if (/\b(cart|basket|trolley|bag)\b/i.test(nm)) push(2, el, nm);
  }
  return tiers.find(t => t.length) || [];
}
function totals() {
  const rx = /(sub[- ]?total|order total|cart total|estimated total|basket total|trolley total)/i;
  for (const el of document.querySelectorAll('*')) {
    if (el.children.length > 3 || !shown(el)) continue;
    const t = txt(el);
    if (t.length > 70 || !rx.test(t)) continue;
    const v = num(t) != null ? num(t) : (num(txt(el.nextElementSibling)) != null ? num(txt(el.nextElementSibling)) : num(txt(el.parentElement)));
    if (v) return v;
  }
  return null;
}
const mode = ns => {   // the reading most sources agree on, not the biggest one
  const t = {};
  ns.forEach(n => { t[n] = (t[n] || 0) + 1; });
  return Object.entries(t).sort((a, b) => b[1] - a[1] || b[0] - a[0])[0][0] * 1;
};
function cart() {
  const b = badges();
  return {count: b.length ? mode(b.map(x => x.n)) : null, subtotal: totals(),
          badges: b.slice(0, 4), url: location.href, title: document.title};
}
const findRm = row => [...row.querySelectorAll('button, input[type=submit], a, [role=button]')].find(b => shown(b) &&
  /^(remove|delete|trash|✕|×|✖)|remove (item|from)|delete (item|from)/i.test(
    (b.getAttribute('aria-label') || b.value || txt(b) || b.className)));
function lines() {
  ['data-fk-line', 'data-fk-lineqty', 'data-fk-rm'].forEach(a =>
    document.querySelectorAll('[' + a + ']').forEach(e => e.removeAttribute(a)));
  // A cart line is a product card you can change or remove but not add. Scanning for rows that
  // merely contain a price also matches the "customers also bought" carousels on a cart page.
  let rows = rawCards(false).map(c => c.card).filter(r => (findQty(r) || findRm(r)) && !findBtn(r));
  if (!rows.length) rows = [...document.querySelectorAll('tr, li, [class*=line-item i], [class*=lineitem i], [class*=cart-item i], [class*=cart__item i], [class*=basket-item i]')]
    .filter(r => shown(r) && PRICE_RX.test(txt(r)) && txt(r).length < 400 && (findQty(r) || findRm(r)) &&
                 !r.querySelector('tr, li, [class*=cart-item i], [class*=line-item i]'));
  return rows.map((r, i) => {
    r.setAttribute('data-fk-line', i);
    const q = findQty(r), rm = findRm(r);
    if (q) q.el.setAttribute('data-fk-lineqty', i);
    if (rm) rm.setAttribute('data-fk-rm', i);
    return {i, text: txt(r).slice(0, 120), price: priceOf(r),
            qty: q ? (q.el.value || null) : null, qty_kind: q ? q.kind : null, remove: !!rm};
  });
}
function err(scope) {   // the site's own complaint after a failed action
  const root = (scope == null ? null : document.querySelector('[data-fk="' + scope + '"]')) || document.body;
  const sels = '[role=alert], [class*=error i], [class*=failure i], [class*=warning i], [class*=notice i]';
  for (const el of [...root.querySelectorAll(sels), ...document.querySelectorAll(sels)]) {
    if (!shown(el)) continue;
    const t = txt(el);
    if (t.length > 3 && t.length < 200) return t.slice(0, 160);
  }
  return null;
}
function toast(scope) {   // "Added to cart" style confirmation; compare before/after, it can pre-exist
  const root = (scope == null ? null : document.querySelector('[data-fk="' + scope + '"]')) || document.body;
  for (const el of root.querySelectorAll('*')) {
    if (!shown(el) || el.children.length > 2) continue;
    const t = txt(el);
    if (t.length < 120 && TOAST_RX.test(t)) return t.slice(0, 80);
  }
  for (const el of document.querySelectorAll('[role=status], [role=alert], [aria-live]')) {
    const t = txt(el);
    if (t && TOAST_RX.test(t)) return t.slice(0, 80);
  }
  return null;
}

function platform() {
  if (window.Shopify || document.querySelector('script[src*="cdn.shopify"], link[href*="cdn.shopify"]')) return 'shopify';
  if (window.wc_add_to_cart_params || /woocommerce/.test(document.body.className)) return 'woocommerce';
  if (window.BCData) return 'bigcommerce';
  if (window.Magento || document.querySelector('script[src*="/mage/"]')) return 'magento';
  if (window.__NEXT_DATA__) return 'next';
  return null;
}
const dialogs = () => [...document.querySelectorAll('[role=dialog], [aria-modal=true], dialog[open]')]
  .filter(d => { const r = rect(d); return shown(d) && r.width > 120 && r.height > 60 && txt(d).length > 10; });
function blockers() {
  const out = [], body = txt(document.body).slice(0, 5000), dlg = dialogs();
  const dtxt = dlg.map(txt).join(' ').slice(0, 2000);
  if (/accept (all )?cookies|we use cookies|cookie (policy|settings|preferences)/i.test(body)) out.push('cookie-banner');
  if (/postcode|post code|zip code|choose (a )?store|select (a )?store|set (your )?location|delivery suburb/i.test(dtxt)) out.push('location-required');
  if (/(sign in|log in|login) to (continue|add|shop|order|see prices)|members only/i.test(body) ||
      [...document.querySelectorAll('input[type=password]')].some(shown)) out.push('login-required');
  if (document.querySelector('iframe[src*=recaptcha], iframe[src*=turnstile], iframe[src*=hcaptcha], #px-captcha, #challenge-form')) out.push('captcha');
  if (dlg.length) out.push('modal-open');
  return [...new Set(out)];
}
function dismiss() {
  const RX = /^(accept( all)?( cookies)?|allow all|i agree|agree|got it|ok(ay)?|close|no thanks|not now|dismiss|reject all|decline|continue without)\b/i;
  const hit = [];
  const scopes = [...dialogs(), ...document.querySelectorAll('[id*=cookie i],[class*=cookie i],[class*=consent i],[id*=consent i],[class*=gdpr i]')].filter(shown);
  for (const s of scopes.slice(0, 8)) {
    const b = [...s.querySelectorAll('button, [role=button], a')].find(x => shown(x) && RX.test((x.getAttribute('aria-label') || txt(x)).trim()));
    if (b) { hit.push(((b.getAttribute('aria-label') || txt(b)) || '').trim().slice(0, 40)); b.click(); }
  }
  return hit;
}

function labelOf(el) {
  let l = el.id ? document.querySelector('label[for="' + CSS.escape(el.id) + '"]') : null;
  if (!l) l = el.closest('label');
  if (!l && el.getAttribute('aria-labelledby')) l = document.getElementById(el.getAttribute('aria-labelledby').split(' ')[0]);
  return (l ? txt(l).slice(0, 80) : '') || el.getAttribute('aria-label') || el.placeholder || '';
}
function fields() {
  document.querySelectorAll('[data-fk-f]').forEach(e => e.removeAttribute('data-fk-f'));
  const out = [];
  let i = 0;
  for (const el of document.querySelectorAll('input, select, textarea')) {
    if (!shown(el) || ['hidden', 'submit', 'button', 'image', 'reset'].includes(el.type)) continue;
    el.setAttribute('data-fk-f', i);
    out.push({i: i++, tag: el.tagName.toLowerCase(), type: el.type || null, name: el.name || null,
              id: el.id || null, autocomplete: el.getAttribute('autocomplete') || null, label: labelOf(el),
              required: !!el.required, value: el.type === 'password' ? null : (el.value || ''),
              options: el.tagName === 'SELECT' ? [...el.options].slice(0, 80).map(o => ({v: o.value, t: txt(o)})) : null});
  }
  return out;
}
function setVal(el, v) {   // native setter + events, so React/Vue controlled inputs actually update
  const P = el.tagName === 'SELECT' ? HTMLSelectElement : el.tagName === 'TEXTAREA' ? HTMLTextAreaElement : HTMLInputElement;
  try { el.focus(); } catch (e) {}
  if (el.type === 'checkbox' || el.type === 'radio') { if (el.checked !== !!v) el.click(); return el.checked; }
  Object.getOwnPropertyDescriptor(P.prototype, 'value').set.call(el, v);
  ['input', 'change', 'blur'].forEach(t => el.dispatchEvent(new Event(t, {bubbles: true})));
  return el.value;
}
function pick(el, v) {
  const w = String(v).toLowerCase().trim();
  const o = [...el.options].find(o => o.value.toLowerCase() === w || txt(o).toLowerCase() === w) ||
            [...el.options].find(o => txt(o).toLowerCase().includes(w) || (o.value || '').toLowerCase().includes(w));
  return o ? setVal(el, o.value) : null;
}
function fill(idx, v) {
  const el = document.querySelector('[data-fk-f="' + idx + '"]');
  if (!el) return null;
  return el.tagName === 'SELECT' ? pick(el, v) : setVal(el, v);
}
function setQty(attr, i, n) {
  const el = document.querySelector('[' + attr + '="' + i + '"]');
  if (!el) return null;
  if (el.tagName === 'SELECT') return pick(el, String(n));
  return setVal(el, String(n));
}
function searchBox(q) {
  const el = [...document.querySelectorAll(SEARCH_SEL)].find(shown);
  if (!el) return null;
  el.setAttribute('data-fk-search', '1');
  if (q != null) setVal(el, q);
  return {name: el.name || null, form: !!el.form, id: el.id || null};
}
function submitSearch() {
  const el = document.querySelector('[data-fk-search]');
  if (!el) return null;
  if (el.form) { el.form.submit(); return 'form'; }
  return null;
}
async function variants() {
  const m = (window.ShopifyAnalytics && window.ShopifyAnalytics.meta && window.ShopifyAnalytics.meta.product) ||
            (window.meta && window.meta.product);
  let out = m && m.variants
    ? m.variants.map(v => ({id: String(v.id), name: v.name || v.public_title || '', price: v.price / 100, available: null}))
    : null;
  const h = location.pathname.match(/\/products\/([^/?#]+)/);
  if (h) try {                       // /products/<handle>.js is the only source with stock per variant
    const r = await fetch('/products/' + h[1] + '.js', {headers: {Accept: 'application/json'}});
    if (r.ok) {
      const p = await r.json();
      out = p.variants.map(v => ({id: String(v.id), name: v.public_title || v.title || '', price: v.price / 100,
                                  available: !!v.available}));
    }
  } catch (e) {}
  return out;
}
return {products, cart, lines, toast, err, platform, blockers, dismiss, fields, fill, setQty,
        searchBox, submitSearch, variants, price: num, cartLink: () => {
          const a = [...document.querySelectorAll('a[href]')].find(a => CARTHREF_RX.test(a.getAttribute('href') || ''));
          return a ? new URL(a.getAttribute('href'), location.href).href : null;
        }};
})();
'__fk ready'
'''

# %% ../nbs/05_shop.ipynb #28811a08044ce470
SITES = {
    'coles.com.au':         dict(search='https://www.coles.com.au/search/products?q={q}', cart='https://www.coles.com.au/trolley',
                                 note='pick a store first; bot-walled from datacentre IPs'),
    'woolworths.com.au':    dict(search='https://www.woolworths.com.au/shop/search/products?searchTerm={q}',
                                 cart='https://www.woolworths.com.au/shop/mytrolley',
                                 note='set a delivery suburb first; bot-walled from datacentre IPs'),
    'amazon.':              dict(search='https://{host}/s?k={q}', cart='https://{host}/gp/cart/view.html'),
    'ceresfairfood.org.au': dict(search='https://members.ceresfairfood.org.au/products/search?q={q}',
                                 cart='https://members.ceresfairfood.org.au/cart', note='members shop: log in to add'),
}

def site_hint(url:str) -> dict:
    "Hints (`search`, `cart`, `note`) for the host of `url`; `{}` when the site is not listed."
    host = urlparse(url).netloc.lower()
    for k, v in SITES.items():
        if k in host: return {kk: (vv.replace('{host}', host) if isinstance(vv, str) else vv) for kk, vv in v.items()}
    return {}

# %% ../nbs/05_shop.ipynb #e1e1a809aa332a3d
class ShopError(RuntimeError):
    "A shop action could not be carried out (bad index, no add control, JS error)."
    pass

async def _js(page, expr):
    "Evaluate `expr` in `page`, awaiting promises, and return the decoded value."
    r = await page.runtime.evaluate(expression=expr, awaitPromise=True, returnByValue=True)
    if isinstance(r, dict) and 'exceptionDetails' in r:
        d = r['exceptionDetails']
        raise ShopError((d.get('exception') or {}).get('description') or d.get('text') or 'JS error')
    return (r or {}).get('value')

def _jsarg(o): return json.dumps(o, default=str)

@patch
async def shop_prep(page:Page, force:bool=False) -> str:
    "Inject the shop helpers (idempotent, and re-injects after a navigation). Returns the platform."
    if force or not await _js(page, '!!(window.__fk && window.__fk.products)'):
        await _js(page, SHOP_JS)
    return await _js(page, '__fk.platform()')

@patch
async def shop_products(page:Page, limit:int=40) -> list:
    "Products on the current page as `[{i, title, price, url, add, qty, oos, vid}]`. `i` feeds `shop_add`."
    await page.shop_prep()
    return await _js(page, f'__fk.products({int(limit)})') or []

@patch
async def shop_cart(page:Page, lines:bool=False) -> dict:
    "Current cart: `{count, subtotal, source}` (+ `lines` if asked). Uses Shopify's `/cart.js` when available."
    plat = await page.shop_prep()
    if plat == 'shopify':
        c = await _js(page, "(async()=>{const r=await fetch('/cart.js',{headers:{Accept:'application/json'}});"
                            "if(!r.ok) return null; const c=await r.json();"
                            "return {count:c.item_count, subtotal:c.total_price/100, currency:c.currency,"
                            "lines:c.items.map((it,n)=>({i:n, title:it.title, qty:it.quantity,"
                            "price:it.final_line_price/100, key:it.key}))};})()")
        if c:
            for l in c.get('lines') or []: l['title'] = html.unescape(l.get('title') or '')  # cart.js escapes it
            return dict(c, source='shopify/cart.js', url=await _js(page, 'location.href'))
    d = await _js(page, '__fk.cart()') or {}
    if lines: d['lines'] = await _js(page, '__fk.lines()') or []
    return dict(d, source='dom')

@patch
async def shop_lines(page:Page) -> list:
    "Cart line items read from the page: `[{i, text, price, qty, remove}]`. Run this on the cart page."
    await page.shop_prep()
    return await _js(page, '__fk.lines()') or []

@patch
async def shop_blockers(page:Page) -> list:
    "What is standing in the way: `cookie-banner`, `location-required`, `login-required`, `captcha`, `modal-open`."
    await page.shop_prep()
    return await _js(page, '__fk.blockers()') or []

@patch
async def shop_dismiss(page:Page) -> list:
    "Click through cookie/consent banners and closable modals. Returns the labels it clicked."
    await page.shop_prep()
    return await _js(page, '__fk.dismiss()') or []

# %% ../nbs/05_shop.ipynb #2f3bf9b41b58c95a
def _sig(c:dict) -> tuple:
    "Comparable fingerprint of a cart reading."
    ls = c.get('lines') or []
    return (c.get('count'), c.get('subtotal'), len(ls),
            tuple(sorted((l.get('title') or l.get('text') or '', l.get('qty')) for l in ls)))

def _changed(before:dict, after:dict) -> str:
    "Which cart signal moved between two readings, or '' if none did."
    if before.get('count') != after.get('count') and after.get('count') is not None: return 'count'
    if before.get('subtotal') != after.get('subtotal') and after.get('subtotal') is not None: return 'subtotal'
    if _sig(before)[2:] != _sig(after)[2:]: return 'lines'
    return ''

async def _watch(page, before, tout=12, scope=None, toast0=None):
    "Poll the cart until a signal moves; falls back to a newly-appeared confirmation toast."
    end = time.time() + tout
    after = before
    while time.time() < end:
        await asyncio.sleep(0.4)
        try: after = await page.shop_cart(lines=bool(before.get('lines')))
        except Exception: continue
        if (how := _changed(before, after)): return True, after, how
        t = await _js(page, f'__fk.toast({_jsarg(scope)})')
        if t and t != toast0: return True, after, f'toast: {t}'
    return (None if before.get('count') is None and before.get('subtotal') is None else False), after, ''

def _match(items:list, want) -> dict:
    "Resolve `want` (index or name) against `items`, raising with the real options rather than guessing."
    if isinstance(want, int) or (isinstance(want, str) and want.isdigit()):
        i = int(want)
        hit = first(p for p in items if p['i'] == i)
        if hit is None: raise ShopError(f'no product #{i}; page has {len(items)}')
        return hit
    w = str(want).lower()
    exact = [p for p in items if w == (p['title'] or '').lower()]
    subs  = [p for p in items if w in (p['title'] or '').lower()]
    if not (exact or subs):
        close = difflib.get_close_matches(w, [(p['title'] or '') for p in items], n=3, cutoff=0.5)
        raise ShopError(f'no product matching {want!r}. Closest: {close or "none"}. '
                        f'Titles: {[p["title"] for p in items][:12]}')
    pool = exact or subs
    return sorted(pool, key=lambda p: (bool(p.get('related')), len(p['title'] or '')))[0]

# %% ../nbs/05_shop.ipynb #371625ec2d63e166
@patch
async def shop_add(page:Page, item, qty:int=1, variant:str=None, open_product:bool=True, tout:int=12) -> dict:
    """Add `item` (index from `shop_products`, or a title) to the cart and verify it landed.

    Returns `{ok, item, how, before, after}`. `ok=True` only when a cart signal actually moved;
    `ok=None` means the site exposes no signal to check, and `ok=False` means nothing changed.
    On a Shopify site this posts to `/cart/add.js`, which needs no clicking and no guessing."""
    plat = await page.shop_prep()
    items = await page.shop_products()
    if not items: return dict(ok=False, error='no products found on this page', url=await _js(page, 'location.href'))
    it = _match(items, item)
    lines = plat == 'shopify'
    before = await page.shop_cart(lines=lines)
    toast0, err0 = await _js(page, f'__fk.toast({it["i"]})'), await _js(page, f'__fk.err({it["i"]})')

    if plat == 'shopify':
        vid, vs = it.get('vid'), None
        if not vid:
            if it['url'] != await _js(page, 'location.href'): await _goto(page, it['url'])
            vs = await _js(page, '__fk.variants()')
            ok_vs = [v for v in (vs or []) if v.get('available') is not False]
            if len(ok_vs) == 1: vid = ok_vs[0]['id']
            elif vs and variant:
                pool = ok_vs or vs
                hit = first(v for v in pool if str(variant).lower() in (v['name'] or '').lower())
                if hit is None: return dict(ok=False, need='variant', item=it, variants=ok_vs,
                                            error=f'no in-stock variant matching {variant!r}')
                vid = hit['id']
        if vid:
            r = await _js(page, "(async()=>{const r=await fetch('/cart/add.js',{method:'POST',"
                                "headers:{'Content-Type':'application/json',Accept:'application/json'},"
                                f"body:JSON.stringify({{items:[{{id:{_jsarg(str(vid))},quantity:{int(qty)}}}]}})}});"
                                "return {status:r.status, body:(await r.text()).slice(0,300)};})()")
            after = await page.shop_cart(lines=lines)
            ok = _changed(before, after)
            return dict(ok=bool(ok), how=ok or f'cart/add.js -> {r.get("status")}', item=it, qty=qty,
                        variant_id=str(vid), before=before, after=after,
                        error=None if ok else r.get('body'))
        if vs: return dict(ok=False, need='variant', item=it, variants=ok_vs, sold_out=len(vs) - len(ok_vs),
                           error='pick one of `variants` (in stock only): shop_add(item, variant="...")')

    if not it['add'] and open_product and it['url'] != await _js(page, 'location.href'):
        await _goto(page, it['url'])
        items = await page.shop_products()
        if items:
            try: it = _match(items, it['title'])
            except ShopError: it = items[0]      # the product page's own product is always index 0
        before = await page.shop_cart(lines=lines)
        toast0, err0 = await _js(page, f'__fk.toast({it["i"]})'), await _js(page, f'__fk.err({it["i"]})')
    if not it['add']:
        return dict(ok=False, error='no add-to-cart control on this product', item=it,
                    hint='the site may need a size/variant chosen first — see shop_fields()')

    clicks, set_to = 1, None
    if qty > 1:
        if it['qty'] in ('select', 'input'):
            set_to = await _js(page, f'__fk.setQty("data-fk-qty",{it["i"]},{int(qty)})')
        if set_to is None: clicks = qty          # no usable qty control: click add qty times
    bid = await page.node_for(f'[data-fk-add="{it["i"]}"]')
    if bid is None: return dict(ok=False, error='add control vanished before the click', item=it)
    for n in range(clicks):
        await page.click_settle(bid, timeout=6)
        if n + 1 < clicks:
            await asyncio.sleep(0.6)
            await page.shop_prep()
            bid = await page.node_for(f'[data-fk-add="{it["i"]}"]') or bid
    ok, after, how = await _watch(page, before, tout=tout, scope=it['i'], toast0=toast0)
    out = dict(ok=ok, how=how or None, item=it, qty=qty, clicks=clicks, qty_set=set_to,
               before=before, after=after)
    if not ok:
        e = await _js(page, f'__fk.err({it["i"]})')
        out['page_error'] = e if e != err0 else None
        out['blockers'] = await page.shop_blockers()
        out['error'] = out['page_error'] or ('no cart signal on this page to verify against'
                       if ok is None else 'cart did not change after the click')
    return out

# %% ../nbs/05_shop.ipynb #6934d1d5bcdc48be
async def _goto(page, url, tout:int=25):
    "Navigate and tolerate a chatty page that never goes network-idle; re-injects the helpers."
    try: await page.goto(url, timeout=tout)
    except Exception: pass
    await asyncio.sleep(0.3)
    await page.shop_prep(force=True)
    return await _js(page, 'location.href')

@patch
async def shop_cart_page(page:Page, url:str=None) -> dict:
    "Open the cart page (hint, on-page cart link, then `/cart`) and return the cart with its lines."
    cur = await _js(page, 'location.href')
    plat = await page.shop_prep()
    origin = f'{urlparse(cur).scheme}://{urlparse(cur).netloc}'
    url = url or site_hint(cur).get('cart') or (f'{origin}/cart' if plat == 'shopify' else None) \
              or await _js(page, '__fk.cartLink()') or f'{origin}/cart'
    await _goto(page, url)
    return await page.shop_cart(lines=True)

@patch
async def shop_qty(page:Page, line, qty:int, tout:int=12) -> dict:
    "Set the quantity of cart line `line` (index from `shop_lines`, or Shopify line key). Verified."
    plat = await page.shop_prep()
    before = await page.shop_cart(lines=True)
    if plat == 'shopify':
        key = line if isinstance(line, str) and not str(line).isdigit() else \
              first(l.get('key') for l in (before.get('lines') or []) if l.get('i') == int(line))
        if key:
            await _js(page, "(async()=>{await fetch('/cart/change.js',{method:'POST',"
                            "headers:{'Content-Type':'application/json'},"
                            f"body:JSON.stringify({{id:{_jsarg(key)},quantity:{int(qty)}}})}});}})()")
            after = await page.shop_cart(lines=True)
            how = _changed(before, after)
            return dict(ok=bool(how), how=how or None, line=line, qty=qty, before=before, after=after)
    lines = await page.shop_lines()
    ln = first(l for l in lines if l['i'] == int(line))
    if ln is None: raise ShopError(f'no cart line #{line}; cart page shows {len(lines)}')
    if not ln['qty_kind']: return dict(ok=False, error='no quantity control on this line', line=ln)
    await _js(page, f'__fk.setQty("data-fk-lineqty",{int(line)},{int(qty)})')
    ok, after, how = await _watch(page, before, tout=tout)
    return dict(ok=ok, how=how or None, line=ln, qty=qty, before=before, after=after)

@patch
async def shop_remove(page:Page, line, tout:int=12) -> dict:
    "Remove cart line `line`. Verified the same way as `shop_add`."
    plat = await page.shop_prep()
    if plat == 'shopify': return await page.shop_qty(line, 0, tout=tout)
    before = await page.shop_cart(lines=True)
    lines = await page.shop_lines()
    ln = first(l for l in lines if l['i'] == int(line))
    if ln is None: raise ShopError(f'no cart line #{line}; cart page shows {len(lines)}')
    bid = await page.node_for(f'[data-fk-rm="{int(line)}"]')
    if bid is None: return dict(ok=False, error='no remove control on this line', line=ln)
    await page.click_settle(bid, timeout=6)
    ok, after, how = await _watch(page, before, tout=tout)
    return dict(ok=ok, how=how or None, line=ln, before=before, after=after)

# %% ../nbs/05_shop.ipynb #e0bcd40f05c5a254
#: canonical profile key -> (autocomplete tokens, name/id fragments, label synonyms)
FIELD_MAP = {
    'first_name': (('given-name',), ('firstname', 'first_name', 'fname', 'first-name', 'givenname'),
                   ('first name', 'given name', 'forename')),
    'last_name':  (('family-name',), ('lastname', 'last_name', 'lname', 'last-name', 'surname', 'familyname'),
                   ('last name', 'family name', 'surname')),
    'name':       (('name',), ('fullname', 'full_name', 'yourname'), ('full name', 'your name', 'name on')),
    'email':      (('email',), ('email', 'e-mail'), ('email', 'e-mail')),
    'phone':      (('tel', 'tel-national'), ('phone', 'mobile', 'tel', 'contactnumber'),
                   ('phone', 'mobile', 'telephone', 'contact number')),
    'company':    (('organization',), ('company', 'organisation', 'organization', 'business'),
                   ('company', 'organisation', 'business name')),
    'address1':   (('address-line1', 'street-address'), ('address1', 'address_1', 'street', 'addressline1', 'address'),
                   ('address', 'street address', 'address line 1')),
    'address2':   (('address-line2',), ('address2', 'address_2', 'addressline2', 'apartment', 'unit'),
                   ('address line 2', 'apartment', 'unit', 'suite')),
    'city':       (('address-level2',), ('city', 'suburb', 'town', 'locality'), ('city', 'suburb', 'town')),
    'state':      (('address-level1',), ('state', 'province', 'region', 'county'),
                   ('state', 'province', 'region', 'territory', 'county')),
    'postcode':   (('postal-code',), ('postcode', 'postal', 'zip', 'zipcode', 'post_code'),
                   ('postcode', 'postal code', 'zip', 'post code')),
    'country':    (('country', 'country-name'), ('country',), ('country',)),
    'card_name':  (('cc-name',), ('ccname', 'cardholder', 'card_name', 'nameoncard'), ('name on card', 'cardholder')),
    'card_number': (('cc-number',), ('cardnumber', 'ccnumber', 'card_number'), ('card number', 'credit card')),
    'card_exp':   (('cc-exp',), ('expiry', 'exp-date', 'cardexpiry'), ('expiry', 'expiration')),
    'card_month': (('cc-exp-month',), ('expmonth', 'exp_month'), ('expiry month', 'month')),
    'card_year':  (('cc-exp-year',), ('expyear', 'exp_year'), ('expiry year', 'year')),
    'card_cvc':   (('cc-csc',), ('cvc', 'cvv', 'csc', 'securitycode'), ('cvc', 'cvv', 'security code')),
    'notes':      ((), ('note', 'comment', 'instruction', 'message'),
                   ('note', 'comment', 'delivery instruction', 'message')),
}
PAY_RX = re.compile(r'\b(pay|payment|place order|complete order|submit order|confirm (order|purchase|payment)'
                    r'|buy now|purchase)\b', re.I)

def _score(f:dict, key:str) -> int:
    "How well form field `f` matches canonical profile key `key` (0 = not at all)."
    ac, names, labels = FIELD_MAP[key]
    tok = (f.get('autocomplete') or '').lower().split()
    tok = [t for t in tok if t not in ('on', 'off', 'shipping', 'billing')]
    if tok and any(t in ac for t in tok): return 100
    if tok and ac and tok[-1] not in ac: return 0     # a real, different autocomplete token: not this field
    nm = re.sub(r'[^a-z0-9]', '', ((f.get('name') or '') + (f.get('id') or '')).lower())
    if any(re.sub(r'[^a-z0-9]', '', n) in nm for n in names if n): return 60
    lb = (f.get('label') or '').lower()
    if lb and any(s in lb for s in labels): return 40
    return 0

def match_fields(fields:list, profile:dict) -> dict:
    "Best field for each profile key: `{key: field}`. One field per key, highest score wins."
    out, used = {}, set()
    pairs = sorted(((_score(f, k), len(f.get('label') or ''), k, f) for k in profile if k in FIELD_MAP
                    for f in fields), key=lambda t: (-t[0], t[1]))
    for sc, _, k, f in pairs:
        if sc == 0 or k in out or f['i'] in used: continue
        if k.startswith('card_') and not (f.get('type') in ('text', 'tel', 'number', None) or f['tag'] == 'select'): continue
        out[k] = f
        used.add(f['i'])
    return out

# %% ../nbs/05_shop.ipynb #11c29c961de00e22
@patch
async def shop_fields(page:Page) -> list:
    "Every visible form field with its label, `autocomplete` token, value and `<select>` options."
    await page.shop_prep()
    return await _js(page, '__fk.fields()') or []

@patch
async def shop_set(page:Page, i:int, value) -> dict:
    "Set form field `i` (index from `shop_fields`) to `value`; returns what the field holds afterwards."
    await page.shop_prep()
    got = await _js(page, f'__fk.fill({int(i)},{_jsarg(value)})')
    return dict(i=i, wanted=value, got=got, ok=got is not None)

@patch
async def shop_fill(page:Page, profile:dict, submit:str=None, confirm:bool=False) -> dict:
    """Fill a checkout form from a profile dict, then re-read the form to confirm what stuck.

    Keys are canonical (`first_name, last_name, email, phone, address1, address2, city, state,
    postcode, country, company, notes, card_*`) and are matched to fields by `autocomplete` token
    first. Returns `{filled, failed, unmatched, fields}`. `submit=` clicks that button by name;
    a payment-looking button additionally needs `confirm=True`."""
    if submit and PAY_RX.search(submit) and not confirm:
        raise ShopError(f'{submit!r} looks like it completes a payment — pass confirm=True to click it')
    fields = await page.shop_fields()
    hit = match_fields(fields, profile)
    filled, failed = {}, {}
    for k, f in hit.items():
        got = await _js(page, f'__fk.fill({f["i"]},{_jsarg(profile[k])})')
        (filled if got is not None else failed)[k] = dict(i=f['i'], label=f['label'] or f['name'], got=got)
    after = {f['i']: f for f in await page.shop_fields()}
    # A <select> holds the option's value ('VIC') where the profile said 'Victoria', and inputs with
    # a mask reformat what they were given — so compare against what the fill returned, loosely.
    same = lambda a, b: re.sub(r'\W', '', str(a)).lower() == re.sub(r'\W', '', str(b)).lower()
    for k, v in list(filled.items()):
        cur = (after.get(v['i']) or {}).get('value')
        v['confirmed'] = bool(cur) and (same(cur, v['got']) or same(cur, profile[k])
                                        or str(profile[k]).lower()[:20] in str(cur).lower())
    out = dict(filled=filled, failed=failed, unmatched=[k for k in profile if k not in hit],
               fields=[f for f in fields if f['i'] not in {v['i'] for v in hit.values()}])
    if submit:
        tree = await page.ax_tree()
        bid = tree.find_id(role='button', name=submit) or tree.find_id(role='link', name=submit)
        if bid is None: raise ShopError(f'no button/link named {submit!r}')
        await page.click_settle(bid)
        out['submitted'] = submit
        out['url'] = await _js(page, 'location.href')
    return out

# %% ../nbs/05_shop.ipynb #1be0c9dcf69b06bb
class Shop:
    "A shopping session on the persistent debug Chrome: search, add, verify, check out."
    def __init__(self, page, port:int=9223): store_attr()

    def _run(self, coro, tout=180): return syncy(coro, tout=tout)
    @property
    def url(self) -> str: return self._run(_js(self.page, 'location.href'))
    def __repr__(self):
        try: c = self.cart()
        except Exception: return f'<Shop {self.url}>'
        return f"<Shop {self.url} | cart: {c.get('count')} items, subtotal {c.get('subtotal')}>"

    def goto(self, url:str) -> str:
        "Navigate to `url`."
        return self._run(_goto(self.page, url))
    def platform(self) -> str: return self._run(self.page.shop_prep())
    def blockers(self) -> list: return self._run(self.page.shop_blockers())
    def dismiss(self) -> list: return self._run(self.page.shop_dismiss())
    def snapshot(self, **kw) -> str: return self._run(self.page.snapshot(**kw))
    def md(self, sel:str=None) -> str: return self._run(self.page.md(sel=sel))

    def search(self, q:str, limit:int=40) -> list:
        "Search the store for `q` (site's search URL if known, else its own search box) and list products."
        url = site_hint(self.url).get('search')
        if url: self.goto(url.format(q=quote_plus(q)))
        elif self.platform() == 'shopify':
            u = urlparse(self.url)
            self.goto(f'{u.scheme}://{u.netloc}/search?q={quote_plus(q)}')
        else: self._run(self.page.shop_typed_search(q))
        return self.products(limit)

    def products(self, limit:int=40) -> list:
        "Products on the current page, numbered for `add`."
        return self._run(self.page.shop_products(limit))
    def find(self, q:str, limit:int=40) -> list:
        "Products on the current page whose title contains `q`."
        return [p for p in self.products(limit) if q.lower() in (p['title'] or '').lower()]

    def add(self, item, qty:int=1, variant:str=None, **kw) -> dict:
        "Add a product (index or title) and report whether the cart actually changed."
        return self._run(self.page.shop_add(item, qty=qty, variant=variant, **kw))
    def cart(self, lines:bool=False) -> dict: return self._run(self.page.shop_cart(lines=lines))
    def cart_page(self, url:str=None) -> dict:
        "Open the cart page and return its contents."
        return self._run(self.page.shop_cart_page(url))
    def lines(self) -> list: return self._run(self.page.shop_lines())
    def set_qty(self, line, qty:int) -> dict: return self._run(self.page.shop_qty(line, qty))
    def remove(self, line) -> dict: return self._run(self.page.shop_remove(line))

    def fields(self) -> list:
        "Ground truth for the form on this page: label, autocomplete token, value, select options."
        return self._run(self.page.shop_fields())
    def set(self, i:int, value) -> dict: return self._run(self.page.shop_set(i, value))
    def fill(self, profile:dict, submit:str=None, confirm:bool=False) -> dict:
        "Fill a checkout form from a profile dict; never clicks a payment button without `confirm=True`."
        return self._run(self.page.shop_fill(profile, submit=submit, confirm=confirm))

@patch
async def shop_typed_search(page:Page, q:str):
    "Type `q` into whatever search box the page has and submit it (no search URL needed)."
    await page.shop_prep()
    box = await _js(page, f'__fk.searchBox({_jsarg(q)})')
    if not box: raise ShopError('no search box found on this page — pass a search URL to goto() instead')
    bid = await page.node_for('[data-fk-search]')
    if bid is not None:
        await page.DOM.focus(backendNodeId=bid)
        for t, k in (('keyDown', 'Enter'), ('keyUp', 'Enter')):
            await page.input.dispatchKeyEvent(type=t, key=k, code=k, windowsVirtualKeyCode=13,
                                              nativeVirtualKeyCode=13, text='\r' if t == 'keyDown' else '')
    await asyncio.sleep(1.2)
    gone = not await _js(page, '!!(window.__fk && window.__fk.products)')   # navigated away: Enter worked
    if not gone and not await _js(page, '__fk.products(3)'):
        await _js(page, '__fk.submitSearch()')                              # no results: submit the form itself
        await asyncio.sleep(1.2)
    await page.shop_prep(force=True)
    return await _js(page, 'location.href')

def shop(url:str=None, port:int=9223, headless:bool=None, extra_flags=None) -> Shop:
    "Open a `Shop` on the persistent debug Chrome (starting one if needed), optionally at `url`."
    async def _open():
        cdp = await cdp_connect(port=port, headless=bool(headless), extra_flags=extra_flags)
        pg = await cdp.new_page() if url is None else await cdp.open_page(url)
        await pg.shop_prep(force=True)
        return pg
    return Shop(syncy(_open(), tout=180), port=port)
