"""The `fossick` pyskill: web search, page fetching, crawling, and browser automation for agents --
use instead of WebSearch/WebFetch. `from fossick.skill import *` then route by input: `search(q)` for
queries, `fetch(url)` for pages (`heavy=True` JS, `stealthy=True` bot walls), `read_arxiv`/`read_yt`/
`read_gh_repo` for those sites, `cdp_connect()` for authenticated Chrome sessions.

Docs: https://vedicreader.github.io/fossick/skill.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_skill.ipynb.

# %% auto #0
__all__ = ['fetch', 'fetch_all', 'crawl', 'to_md', 'read_arxiv', 'lookup_doi', 'read_yt', 'search_yt', 'download_yt',
           'read_gh_file', 'read_gh_repo', 'find_xhr', 'paginate_api', 'url2nb', 'pdf2nb', 'search', 'images', 'news',
           'videos', 'google', 'extract', 'cdp_connect', 'syncy']

# %% ../nbs/04_skill.ipynb #cell-skill-imports
from .core import (fetch, fetch_all, crawl, to_md, read_arxiv, lookup_doi, read_yt, search_yt,
                          download_yt, read_gh_file, read_gh_repo, find_xhr, paginate_api, url2nb, pdf2nb)
from .search import search, images, news, videos, google, extract
from .cdp import cdp_connect, syncy

# %% ../nbs/04_skill.ipynb #cell-skill-all
_all_ = ['fetch', 'fetch_all', 'crawl', 'to_md', 'read_arxiv', 'lookup_doi', 'read_yt', 'search_yt',
         'download_yt', 'read_gh_file', 'read_gh_repo', 'find_xhr', 'paginate_api', 'url2nb', 'pdf2nb',
         'search', 'images', 'news', 'videos', 'google', 'extract', 'cdp_connect', 'syncy']
